//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resource {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resource() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource", typeof(Resource).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_accept {
        get {
            object obj = ResourceManager.GetObject("btn_accept", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_cancel {
        get {
            object obj = ResourceManager.GetObject("btn_cancel", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_close {
        get {
            object obj = ResourceManager.GetObject("btn_close", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_copy {
        get {
            object obj = ResourceManager.GetObject("btn_copy", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_create_new {
        get {
            object obj = ResourceManager.GetObject("btn_create_new", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_down {
        get {
            object obj = ResourceManager.GetObject("btn_down", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_excel {
        get {
            object obj = ResourceManager.GetObject("btn_excel", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_exit {
        get {
            object obj = ResourceManager.GetObject("btn_exit", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_expand {
        get {
            object obj = ResourceManager.GetObject("btn_expand", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_expand2 {
        get {
            object obj = ResourceManager.GetObject("btn_expand2", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_export {
        get {
            object obj = ResourceManager.GetObject("btn_export", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_filter {
        get {
            object obj = ResourceManager.GetObject("btn_filter", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_help {
        get {
            object obj = ResourceManager.GetObject("btn_help", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_jump {
        get {
            object obj = ResourceManager.GetObject("btn_jump", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_left {
        get {
            object obj = ResourceManager.GetObject("btn_left", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_load {
        get {
            object obj = ResourceManager.GetObject("btn_load", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_mail {
        get {
            object obj = ResourceManager.GetObject("btn_mail", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_organizer {
        get {
            object obj = ResourceManager.GetObject("btn_organizer", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_pause {
        get {
            object obj = ResourceManager.GetObject("btn_pause", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_play {
        get {
            object obj = ResourceManager.GetObject("btn_play", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_preview {
        get {
            object obj = ResourceManager.GetObject("btn_preview", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_print {
        get {
            object obj = ResourceManager.GetObject("btn_print", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_properties {
        get {
            object obj = ResourceManager.GetObject("btn_properties", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_rec_delete {
        get {
            object obj = ResourceManager.GetObject("btn_rec_delete", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_rec_edit {
        get {
            object obj = ResourceManager.GetObject("btn_rec_edit", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_rec_new {
        get {
            object obj = ResourceManager.GetObject("btn_rec_new", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_redo {
        get {
            object obj = ResourceManager.GetObject("btn_redo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_right {
        get {
            object obj = ResourceManager.GetObject("btn_right", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_save {
        get {
            object obj = ResourceManager.GetObject("btn_save", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_save_image {
        get {
            object obj = ResourceManager.GetObject("btn_save_image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_scroll {
        get {
            object obj = ResourceManager.GetObject("btn_scroll", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_search {
        get {
            object obj = ResourceManager.GetObject("btn_search", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_size_to_fit {
        get {
            object obj = ResourceManager.GetObject("btn_size_to_fit", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_slideshow {
        get {
            object obj = ResourceManager.GetObject("btn_slideshow", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_start {
        get {
            object obj = ResourceManager.GetObject("btn_start", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_stop {
        get {
            object obj = ResourceManager.GetObject("btn_stop", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_stop1 {
        get {
            object obj = ResourceManager.GetObject("btn_stop1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_table {
        get {
            object obj = ResourceManager.GetObject("btn_table", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_tools {
        get {
            object obj = ResourceManager.GetObject("btn_tools", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_tree_ancestry {
        get {
            object obj = ResourceManager.GetObject("btn_tree_ancestry", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_tree_both {
        get {
            object obj = ResourceManager.GetObject("btn_tree_both", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_tree_descendants {
        get {
            object obj = ResourceManager.GetObject("btn_tree_descendants", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_undo {
        get {
            object obj = ResourceManager.GetObject("btn_undo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_up {
        get {
            object obj = ResourceManager.GetObject("btn_up", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_volume_max {
        get {
            object obj = ResourceManager.GetObject("btn_volume_max", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_volume_middle {
        get {
            object obj = ResourceManager.GetObject("btn_volume_middle", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_volume_min {
        get {
            object obj = ResourceManager.GetObject("btn_volume_min", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_volume_mute {
        get {
            object obj = ResourceManager.GetObject("btn_volume_mute", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_zoom_in {
        get {
            object obj = ResourceManager.GetObject("btn_zoom_in", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap btn_zoom_out {
        get {
            object obj = ResourceManager.GetObject("btn_zoom_out", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap chart_controls {
        get {
            object obj = ResourceManager.GetObject("chart_controls", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Byte[].
    /// </summary>
    public static byte[] FreeSans {
        get {
            object obj = ResourceManager.GetObject("FreeSans", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Byte[].
    /// </summary>
    public static byte[] FreeSansBold {
        get {
            object obj = ResourceManager.GetObject("FreeSansBold", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    /// </summary>
    public static System.Drawing.Icon icon_gedkeeper {
        get {
            object obj = ResourceManager.GetObject("icon_gedkeeper", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap icon_gedkeeper1 {
        get {
            object obj = ResourceManager.GetObject("icon_gedkeeper1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap image_tips_light {
        get {
            object obj = ResourceManager.GetObject("image_tips_light", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_female_140 {
        get {
            object obj = ResourceManager.GetObject("pi_female_140", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_female_200 {
        get {
            object obj = ResourceManager.GetObject("pi_female_200", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_female_400 {
        get {
            object obj = ResourceManager.GetObject("pi_female_400", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_male_140 {
        get {
            object obj = ResourceManager.GetObject("pi_male_140", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_male_200 {
        get {
            object obj = ResourceManager.GetObject("pi_male_200", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pi_male_400 {
        get {
            object obj = ResourceManager.GetObject("pi_male_400", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap pnl_video {
        get {
            object obj = ResourceManager.GetObject("pnl_video", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap rg_shield_max {
        get {
            object obj = ResourceManager.GetObject("rg_shield_max", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap rg_shield_mid {
        get {
            object obj = ResourceManager.GetObject("rg_shield_mid", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap rg_shield_none {
        get {
            object obj = ResourceManager.GetObject("rg_shield_none", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap sym_female {
        get {
            object obj = ResourceManager.GetObject("sym_female", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap sym_male {
        get {
            object obj = ResourceManager.GetObject("sym_male", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_barbed_wire {
        get {
            object obj = ResourceManager.GetObject("tg_barbed_wire", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_george_cross {
        get {
            object obj = ResourceManager.GetObject("tg_george_cross", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_islam_sym {
        get {
            object obj = ResourceManager.GetObject("tg_islam_sym", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_latin_cross {
        get {
            object obj = ResourceManager.GetObject("tg_latin_cross", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_oldritual_cross {
        get {
            object obj = ResourceManager.GetObject("tg_oldritual_cross", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_orthodox_cross {
        get {
            object obj = ResourceManager.GetObject("tg_orthodox_cross", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_soldier {
        get {
            object obj = ResourceManager.GetObject("tg_soldier", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_soldier_fall {
        get {
            object obj = ResourceManager.GetObject("tg_soldier_fall", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tg_veteran_rear {
        get {
            object obj = ResourceManager.GetObject("tg_veteran_rear", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
