# Hardware platforms
x86-64 := x86-64
x86 := x86
any := any
# Software platforms
windows := windows
linux := linux
# Release types
debug := debug
release := release
# .NET version
dotnet20 := dotnet20
dotnet46 := dotnet46
# Projects
gkcommon := GKCommon
gedkeeper2 := GEDKeeper2
gksampleplugin := GKSamplePlugin
gkcalculatorplugin := GKCalculatorPlugin
gkcalendarplugin := GKCalendarPlugin
gkflowinputplugin := GKFlowInputPlugin
gkimageviewerplugin := GKImageViewerPlugin
gklifeplugin := GKLifePlugin
gknamesbookplugin := GKNamesBookPlugin
gknavigatorplugin := GKNavigatorPlugin
gkpedigreeimporterplugin := GKPedigreeImporterPlugin
gktextsearchplugin := GKTextSearchPlugin
gktimelineplugin := GKTimeLinePlugin
gktreevizplugin := GKTreeVizPlugin
