<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
        <OutputPath>..\..\..\plugins\</OutputPath>
        <OutputType>Library</OutputType>

        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <Import Project="..\..\GKConfigurations3.targets" />

    <ItemGroup>
        <Reference Include="BSLib">
            <HintPath>..\..\libs\netstd\BSLib.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\GKCore\GKCore.nstd.csproj" />
        <ProjectReference Include="..\..\GKv3\GKComponents\GKComponents.csproj" />
        <ProjectReference Include="..\..\GKCortex\GKCortex.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Eto.Forms" Version="2.10.0" />
        <PackageReference Include="Eto.Serialization.Xaml" Version="2.10.0" />
        <PackageReference Include="SmartComponents.LocalEmbeddings" Version="0.1.0-preview10148" />
    </ItemGroup>

    <ItemGroup>
        <None Include="GKMCPPlugin.enu">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="GKMCPPlugin.rus">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
