coverage:
  disable_default_path_fixes: true
  precision: 2
  round: nearest
  range: 60..100

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true


comment:
  layout: "header, diff, changes, suggestions, sunburst, tree"
  behavior: default
