/*
 *  "GEDKeeper", the personal genealogical database editor.
 *  Copyright (C) 2009-2025 by Sergey V. Zhdanovskih.
 *
 *  This file is part of "GEDKeeper".
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using BSLib;
using GKCore.Interfaces;

namespace GKCore
{
    public enum LSID
    {
        /* 000 */ None,
        /* 001 */ First,

        /* 001 */ MIFile = 1,
        /* 002 */ MIEdit = 2,
        /* 003 */ MIPedigree,
        /* 004 */ MIService,
        /* 005 */ MIWindow,
        /* 006 */ MIHelp,
        /* 007 */ MIFileNew,
        /* 008 */ MIFileLoad,
        /* 009 */ MIMRUFiles,
        /* 010 */ MIFileSave,
        /* 011 */ MIFileClose,
        /* 012 */ MIFileProperties,
        /* 013 */ MIExport,
        /* 014 */ MIExportToFamilyBook,
        /* 015 */ MIFileSaveAs,
        /* 016 */ ExportTable,
        /* 017 */ MIExit,
        /* 018 */ Import,
        /* 019 */ Clear,
        /* 020 */ MIRecordAdd,
        /* 021 */ MIRecordEdit,
        /* 022 */ MIRecordDelete,

        /* 023 */ Deprecated_023, // deprecated

        /* 024 */ MITreeAncestors,
        /* 025 */ MITreeDescendants,
        /* 026 */ MITreeBoth,
        /* 027 */ MIPedigreeDescend,

        /* 028 */ Deprecated_028, // deprecated

        /* 029 */ MIMap,
        /* 030 */ MIStats,
        /* 031 */ MIPedigreeAscend,

        /* 032 */ PN_Aboville,
        /* 033 */ PN_Kobrin_Konovalov,
        /* 034 */ PN_Sosa_Stradonitz,

        /* 035 */ MIOrganizer,
        /* 036 */ MIScripts,

        /* 037 */ Deprecated_037, // deprecated

        /* 038 */ MITreeTools = 38,
        /* 039 */ MIFilter,
        /* 040 */ MIOptions,
        /* 041 */ MIWinCascade,
        /* 042 */ MIWinHTile,
        /* 043 */ MIWinVTile,
        /* 044 */ MIWinMinimize,

        /* 045 */ Deprecated_045, // deprecated
        /* 046 */ Deprecated_046, // deprecated
        /* 047 */ Deprecated_047, // deprecated
        /* 048 */ Deprecated_048, // deprecated

        /* 049 */ MIContext,
        /* 050 */ MIAbout,
        /* 051 */ SBRecords,
        /* 052 */ SBFiltered,

        /* 053 */ RPIndividuals,
        /* 054 */ RPFamilies,
        /* 055 */ RPNotes,
        /* 056 */ RPMultimedia,
        /* 057 */ RPSources,
        /* 058 */ RPRepositories,
        /* 059 */ RPGroups,
        /* 060 */ RPResearches,
        /* 061 */ RPTasks,
        /* 062 */ RPCommunications,
        /* 063 */ RPLocations,

        /* 064 */ UnkFemale,
        /* 065 */ UnkMale,
        /* 066 */ SexU,
        /* 067 */ SexM,
        /* 068 */ SexF,
        /* 069 */ SexX,
        /* 070 */ FileSaveQuery,
        /* 071 */ ParentsQuery,
        /* 072 */ PersonDeleteQuery,
        /* 073 */ FamilyDeleteQuery,
        /* 074 */ NoteDeleteQuery,
        /* 075 */ SourceDeleteQuery,
        /* 076 */ MediaDeleteQuery,
        /* 077 */ RepositoryDeleteQuery,
        /* 078 */ GroupDeleteQuery,
        /* 079 */ ResearchDeleteQuery,
        /* 080 */ TaskDeleteQuery,
        /* 081 */ CommunicationDeleteQuery,
        /* 082 */ LocationDeleteQuery,
        /* 083 */ Address,
        /* 084 */ Events,
        /* 085 */ Surname,
        /* 086 */ GivenName,
        /* 087 */ Patronymic,
        /* 088 */ Sex,
        /* 089 */ Nickname,
        /* 090 */ SurnamePrefix,
        /* 091 */ NamePrefix,
        /* 092 */ NameSuffix,
        /* 093 */ Patriarch,
        /* 094 */ Bookmark,
        /* 095 */ Association,
        /* 096 */ Relation,
        /* 097 */ Person,

        /* 098 */ DlgAccept,
        /* 099 */ DlgCancel,
        /* 100 */ DlgClose,

        /* 101 */ DlgSelect,
        /* 102 */ DlgAppend,
        /* 103 */ GeneralName,
        /* 104 */ WinPersonEdit,
        /* 105 */ WinCheckSex,
        /* 106 */ WinRecordSelect,
        /* 107 */ WinSourceCitEdit,
        /* 108 */ WinUserRefEdit,
        /* 109 */ Note,
        /* 110 */ Source,
        /* 111 */ Page,
        /* 112 */ Certainty,
        /* 113 */ Reference,
        /* 114 */ Type,
        /* 115 */ Family,
        /* 116 */ Husband,
        /* 117 */ Wife,
        /* 118 */ Status,
        /* 119 */ Childs,
        /* 120 */ DetachHusbandQuery,
        /* 121 */ DetachWifeQuery,
        /* 122 */ DetachChildQuery,
        /* 123 */ BirthDate,
        /* 124 */ DeathDate,
        /* 125 */ Restriction,
        /* 126 */ Title,
        /* 127 */ Members,
        /* 128 */ WinGroupEdit,
        /* 129 */ DetachMemberQuery,
        /* 130 */ MediaView,
        /* 131 */ Stage,
        /* 132 */ Telephone,
        /* 133 */ Mail,
        /* 134 */ WebSite,
        /* 135 */ Repository,
        /* 136 */ Progress,
        /* 137 */ TimePassed,
        /* 138 */ TimeRemain,
        /* 139 */ TimeTotal,
        /* 140 */ Date,
        /* 141 */ Text,
        /* 142 */ ShortTitle,
        /* 143 */ Author,
        /* 144 */ Publication,
        /* 145 */ Common,
        /* 146 */ DetachRepositoryQuery,
        /* 147 */ StoreType,
        /* 148 */ File,
        /* 149 */ View,
        /* 150 */ LogHint,
        /* 151 */ Father,
        /* 152 */ Mother,
        /* 153 */ Parents,
        /* 154 */ Spouses,
        /* 155 */ Associations,
        /* 156 */ UserRefs,
        /* 157 */ Cal_Gregorian,
        /* 158 */ Cal_Julian,
        /* 159 */ Cal_Hebrew,
        /* 160 */ Cal_Islamic,
        /* 161 */ Cal_Persian,
        /* 162 */ Cal_Indian,
        /* 163 */ Cal_Bahai,
        /* 164 */ Cal_French,
        /* 165 */ Cal_Roman,
        /* 166 */ Unknown,
        /* 167 */ Summary,
        /* 168 */ Other,
        /* 169 */ Submission,
        /* 170 */ Submitter,
        /* 171 */ Location,
        /* 172 */ Latitude,
        /* 173 */ Longitude,
        /* 174 */ Show,
        /* 175 */ SearchCoords,
        /* 176 */ Search,
        /* 177 */ SelectCoords,
        /* 178 */ SelectName,
        /* 179 */ Priority,
        /* 180 */ Percent,
        /* 181 */ StartDate,
        /* 182 */ StopDate,
        /* 183 */ Goal,
        /* 184 */ Theme,
        /* 185 */ Corresponder,
        /* 186 */ Group,
        /* 187 */ DetachTaskQuery,
        /* 188 */ DetachCommunicationQuery,
        /* 189 */ DetachGroupQuery,
        /* 190 */ WinResearchEdit,
        /* 191 */ WinTaskEdit,
        /* 192 */ WinCommunicationEdit,
        /* 193 */ Error,
        /* 194 */ LuaStartFailed,
        /* 195 */ DateFormatInvalid,
        /* 196 */ AdCountry,
        /* 197 */ AdState,
        /* 198 */ AdCity,
        /* 199 */ AdPostalCode,
        /* 200 */ Telephones,

        /* 201 */ EMails,
        /* 202 */ WebSites,
        /* 203 */ Value,
        /* 204 */ Event,
        /* 205 */ Place,
        /* 206 */ Cause,
        /* 207 */ Agency,
        /* 208 */ PatFemale,
        /* 209 */ PatMale,
        /* 210 */ NotSelectedPerson,
        /* 211 */ IsNotDefinedSex,
        /* 212 */ IsNotFamilies, /* not used */
        /* 213 */ AncestorsNumberIsInvalid,
        /* 214 */ DescendantsNumberIsInvalid,
        /* 215 */ GenerationsVisible,
        /* 216 */ Unlimited,
        /* 217 */ Spouse,
        /* 218 */ MarriageDate,
        /* 219 */ DetachFatherQuery,
        /* 220 */ DetachMotherQuery,
        /* 221 */ DetachSpouseQuery,
        /* 222 */ DetachParentsQuery,
        /* 223 */ TM_Both,
        /* 224 */ TM_Ancestors,
        /* 225 */ TM_Descendants,
        /* 226 */ TM_TraceSelected,
        /* 227 */ DoEdit,
        /* 228 */ FamilyAdd,
        /* 229 */ SpouseAdd,
        /* 230 */ SonAdd,
        /* 231 */ DaughterAdd,
        /* 232 */ DoDelete,
        /* 233 */ RebuildTree,
        /* 234 */ RebuildKinships,
        /* 235 */ Links,
        /* 236 */ PlaceAndAttribute,
        /* 237 */ LMarriage,
        /* 238 */ LFamily,
        /* 239 */ Namesakes,
        /* 240 */ RemoveEventQuery,
        /* 241 */ DetachNoteQuery,
        /* 242 */ DetachMultimediaQuery,
        /* 243 */ DetachSourceQuery,
        /* 244 */ RemoveAssociationQuery,
        /* 245 */ RemoveUserRefQuery,
        /* 246 */ LoadGedComFailed,
        /* 247 */ CheckGedComFailed,
        /* 248 */ BirthDays,
        /* 249 */ DaysRemained,
        /* 250 */ Interface,
        /* 251 */ Trees,
        /* 252 */ Pedigrees,
        /* 253 */ SaveCoding,
        /* 254 */ Addresses,
        /* 255 */ Mails,
        /* 256 */ Webs,
        /* 257 */ Internet,
        /* 258 */ ProxyUse,
        /* 259 */ ProxyServer,
        /* 260 */ ProxyPort,
        /* 261 */ ProxyLogin,
        /* 262 */ Password,
        /* 263 */ PasswordIsNotSpecified,
        /* 264 */ StartupTips,
        /* 265 */ Language,
        /* 266 */ ListsAll,
        /* 267 */ ListPersons,
        /* 268 */ NamesFormat,
        /* 269 */ NF1,
        /* 270 */ NF2,
        /* 271 */ NF3,
        /* 272 */ DateFormat,
        /* 273 */ PlacesWithAddress,
        /* 274 */ HighlightUnparented,
        /* 275 */ HighlightUnmarried,
        /* 276 */ DefList,
        /* 277 */ ViewTree,
        /* 278 */ DiffLines,
        /* 279 */ OnlyYears,
        /* 280 */ Kinship,
        /* 281 */ SignsVisible,
        /* 282 */ TreeDecorative,
        /* 283 */ PortraitsVisible,
        /* 284 */ ChildlessExclude,
        /* 285 */ Decor,
        /* 286 */ Man,
        /* 287 */ Woman,
        /* 288 */ UnkSex,
        /* 289 */ UnHusband,
        /* 290 */ UnWife,
        /* 291 */ Font,
        /* 292 */ PedigreeGen,
        /* 293 */ IncludeAttributes,
        /* 294 */ IncludeNotes,
        /* 295 */ IncludeSources,
        /* 296 */ PedigreeFormat,
        /* 297 */ PF1,
        /* 298 */ PF2,
        /* 299 */ RecordGoto,
        /* 300 */ RecordMoveUp,

        /* 301 */ RecordMoveDown,
        /* 302 */ FullName,
        /* 303 */ BirthPlace,
        /* 304 */ DeathPlace,
        /* 305 */ Residence,
        /* 306 */ Age,
        /* 307 */ LifeExpectancy,
        /* 308 */ DaysForBirth,
        /* 309 */ Religion,
        /* 310 */ Nationality,
        /* 311 */ Education,
        /* 312 */ Occupation,
        /* 313 */ Caste,
        /* 314 */ Mili,
        /* 315 */ MiliInd,
        /* 316 */ MiliDis,
        /* 317 */ MiliRank,
        /* 318 */ Changed,
        /* 319 */ MarrRegistered,
        /* 320 */ MarrNotRegistered,
        /* 321 */ MarrDivorced,
        /* 322 */ Birth,
        /* 323 */ Adoption,
        /* 324 */ Christening,
        /* 325 */ Graduation,
        /* 326 */ Retirement,
        /* 327 */ Naturalization,
        /* 328 */ Emigration,
        /* 329 */ Immigration,
        /* 330 */ Census,
        /* 331 */ LastWill,
        /* 332 */ ProbateOfWill,
        /* 333 */ Death,
        /* 334 */ Burial,
        /* 335 */ Cremation,
        /* 336 */ Fact,
        /* 337 */ PhysicalDesc,
        /* 338 */ NationalIDNumber,
        /* 339 */ SocialSecurityNumber,
        /* 340 */ ChildsCount,
        /* 341 */ MarriagesCount,
        /* 342 */ PersonalProperty,
        /* 343 */ NobilityTitle,
        /* 344 */ Travel,
        /* 345 */ Hobby,
        /* 346 */ Award,
        /* 347 */ RK_Unk,
        /* 348 */ RK_Father,
        /* 349 */ RK_Mother,
        /* 350 */ RK_Husband,
        /* 351 */ RK_Wife,
        /* 352 */ RK_Son,
        /* 353 */ RK_Daughter,
        /* 354 */ RK_Grandfather,
        /* 355 */ RK_Grandmother,
        /* 356 */ RK_Grandson,
        /* 357 */ RK_Granddaughter,
        /* 358 */ RK_Brother,
        /* 359 */ RK_Sister,
        /* 360 */ RK_SonInLaw,
        /* 361 */ RK_DaughterInLaw,
        /* 362 */ RK_HusbandFather,
        /* 363 */ RK_HusbandMother,
        /* 364 */ RK_WifeFather,
        /* 365 */ RK_WifeMother,
        /* 366 */ RK_Uncle_FatherBrother,
        /* 367 */ RK_Aunt_FatherSister,
        /* 368 */ RK_Nephew,
        /* 369 */ RK_Niece,
        /* 370 */ RK_CousinM,
        /* 371 */ RK_CousinF,
        /* 372 */ RK_BrotherInLaw_H,
        /* 373 */ RK_SisterInLaw_H,
        /* 374 */ RK_BrotherInLaw_W,
        /* 375 */ RK_SisterInLaw_W,
        /* 376 */ RK_GreatPrefix,
        /* 377 */ RK_Uncle_MotherBrother,
        /* 378 */ RK_Aunt_MotherSister,
        /* 379 */ RK_Stepfather,
        /* 380 */ RK_Stepmother,
        /* 381 */ TooMuchWidth,
        /* 382 */ Backward,
        /* 383 */ Forward,
        /* 384 */ Prev,
        /* 385 */ Next,
        /* 386 */ YouKnowWhat,
        /* 387 */ LoadingLocations,
        /* 388 */ NotSelected,
        /* 389 */ MapSelection,
        /* 390 */ MapSelOnAll,
        /* 391 */ MSBirthPlaces,
        /* 392 */ MSDeathPlaces,
        /* 393 */ MSResiPlace,
        /* 394 */ MapSelOnSelected,
        /* 395 */ SaveImage,

        /* 396 */ FormatUnsupported, // may be deprecated
        /* 397 */ DataLoadError, // may be deprecated

        /* 398 */ DocPrint,
        /* 399 */ DocPreview,
        /* 400 */ Generation,

        /* 401 */ CondContains,
        /* 402 */ CondNotContains,
        /* 403 */ DK_0,
        /* 404 */ DK_1,
        /* 405 */ DK_2,
        /* 406 */ DK_3,
        /* 407 */ DK_4,
        /* 408 */ DK_5,
        /* 409 */ DK_6,
        /* 410 */ DK_7,
        /* 411 */ DK_8,
        /* 412 */ DK_9,
        /* 413 */ FEvt_1,
        /* 414 */ FEvt_2,
        /* 415 */ FEvt_3,
        /* 416 */ FEvt_4,
        /* 417 */ FEvt_5,
        /* 418 */ FEvt_6,
        /* 419 */ FEvt_7,
        /* 420 */ FEvt_8,
        /* 421 */ FEvt_9,
        /* 422 */ STRef,
        /* 423 */ STArc,
        /* 424 */ STStg,
        /* 425 */ DefaultValue,
        /* 426 */ MT_02,
        /* 427 */ MT_03,
        /* 428 */ MT_04,
        /* 429 */ MT_05,
        /* 430 */ MT_06,
        /* 431 */ MT_07,
        /* 432 */ MT_08,
        /* 433 */ MT_09,
        /* 434 */ MT_10,
        /* 435 */ MT_11,
        /* 436 */ MT_12,
        /* 437 */ MT_13,
        /* 438 */ MT_14,
        /* 439 */ MT_15,
        /* 440 */ Prt_1,
        /* 441 */ Prt_2,
        /* 442 */ Prt_3,
        /* 443 */ Prt_4,
        /* 444 */ Prt_5,
        /* 445 */ RStat_1,
        /* 446 */ RStat_2,
        /* 447 */ RStat_3,
        /* 448 */ RStat_4,
        /* 449 */ RStat_5,
        /* 450 */ RStat_6,
        /* 451 */ Com_1,
        /* 452 */ Com_2,
        /* 453 */ Com_3,
        /* 454 */ Com_4,
        /* 455 */ Com_5,
        /* 456 */ Com_6,
        /* 457 */ CD_1,
        /* 458 */ CD_2,
        /* 459 */ G_1,
        /* 460 */ G_2,
        /* 461 */ G_3,
        /* 462 */ G_4,
        /* 463 */ Cert_1,
        /* 464 */ Cert_2,
        /* 465 */ Cert_3,
        /* 466 */ Cert_4,
        /* 467 */ Research,
        /* 468 */ Task,
        /* 469 */ Communication,
        /* 470 */ IDsCorrect,
        /* 471 */ FormatCheck,
        /* 472 */ EmfFilter,
        /* 473 */ MainBaseSize,
        /* 474 */ SyncFin,
        /* 475 */ PatSearch,
        /* 476 */ LinksSearch,
        /* 477 */ MediaFileNotLoaded,
        /* 478 */ Scale,
        /* 479 */ GEDCOMFilter,
        /* 480 */ AllFilter,
        /* 481 */ ImagesFilter,
        /* 482 */ ScriptsFilter,
        /* 483 */ TreeImagesFilter,
        /* 484 */ DeathCauses,
        /* 485 */ ExpPedigree,
        /* 486 */ Parameter,
        /* 487 */ Total,
        /* 488 */ ManSum,
        /* 489 */ WomanSum,
        /* 490 */ FieldsFilter,

        /* 491 */ Year,
        /* 492 */ PDFFilter,
        /* 493 */ RTFFilter,
        /* 494 */ HTMLFilter,
        /* 495 */ FileBackup,
        /* 496 */ BackupOnlyPrev,
        /* 497 */ BranchCut,
        /* 498 */ Not,
        /* 499 */ BCut_Years,
        /* 500 */ BCut_Persons,
        /* 501 */ SrcAll,
        /* 502 */ SrcNot,
        /* 503 */ SrcAny,

        /* 504 */ MasterBase,
        /* 505 */ OtherBase,
        /* 506 */ CurrentBase,
        /* 507 */ IncludedSourceFilter,
        /* 508 */ IncludedGroupFilter,
        /* 509 */ DuplicatesSearch,
        /* 510 */ ValueInvalid,
        /* 511 */ Operation,
        /* 512 */ TreeCompare,
        /* 513 */ TreeMerge,
        /* 514 */ TreeSplit,
        /* 515 */ MergeDuplicates,
        /* 516 */ SearchUnlinkedNamesakes,
        /* 517 */ FragmentSearch,
        /* 518 */ TreeCheck,
        /* 519 */ PatriarchsSearch,
        /* 520 */ PlacesManager,
        /* 521 */ SearchMatches,
        /* 522 */ CheckFamiliesConnection,
        /* 523 */ All,
        /* 524 */ OnlyAlive,
        /* 525 */ OnlyDied,
        /* 526 */ AliveBefore,
        /* 527 */ OnlyMans,
        /* 528 */ OnlyWomans,
        /* 529 */ NameMask,
        /* 530 */ PlaceMask,
        /* 531 */ EventMask,
        /* 532 */ OnlyPatriarchs,
        /* 533 */ DateInvalid,
        /* 534 */ People,
        /* 535 */ Years,
        /* 536 */ Decennial,
        /* 537 */ HowBirthes,
        /* 538 */ HowDeads,
        /* 539 */ Living,
        /* 540 */ Deads,
        /* 541 */ AvgAge,
        /* 542 */ AvgLife,
        /* 543 */ AvgChilds,
        /* 544 */ AvgBorn,
        /* 545 */ AvgMarriagesCount,
        /* 546 */ AvgMarriagesAge,
        /* 547 */ AncestorsCount,
        /* 548 */ DescendantsCount,
        /* 549 */ GenerationsCount,
        /* 550 */ BirthYears,
        /* 551 */ BirthYearsDec,
        /* 552 */ DeathYears,
        /* 553 */ DeathYearsDec,
        /* 554 */ DistrChilds,
        /* 555 */ AgeFirstborn,
        /* 556 */ MarriagesAge,
        /* 557 */ DiffSpouses,
        /* 558 */ SelAll,
        /* 559 */ SelFamily,
        /* 560 */ SelAncestors,
        /* 561 */ SelDescendants,
        /* 562 */ RecMerge,
        /* 563 */ RM_Search,
        /* 564 */ RM_Skip,
        /* 565 */ RM_Records,
        /* 566 */ RM_SearchPersons,

        /* 567 */ RM_DirectMatching, // deprecated
        /* 568 */ RM_IndistinctMatching,
        /* 569 */ RM_OnlyNP, // deprecated

        /* 570 */ RM_BirthYear,
        /* 571 */ RM_NameAccuracy,
        /* 572 */ RM_YearInaccuracy,
        /* 573 */ Repair,
        /* 574 */ MinGenerations,
        /* 575 */ SetPatFlag,
        /* 576 */ InsertIntoBook,
        /* 577 */ SimilarSurnames,
        /* 578 */ SimilarNames,
        /* 579 */ RecsDeleted,
        /* 580 */ Record,
        /* 581 */ Problem,
        /* 582 */ Solve,
        /* 583 */ PersonLonglived,
        /* 584 */ PersonSexless,
        /* 585 */ LiveYearsInvalid,
        /* 586 */ StrangeSpouse,
        /* 587 */ StrangeParent,
        /* 588 */ Descendants,
        /* 589 */ Generations,
        /* 590 */ LinksCount,
        /* 591 */ PlacesPrepare,
        /* 592 */ PlaceAlreadyInBook,
        /* 593 */ DNAMarkers,
        /* 594 */ AAF_1,
        /* 595 */ AAF_2,
        /* 596 */ EmptyFamily,
        /* 597 */ BackupEachRevision,
        /* 598 */ Loading,
        /* 599 */ FileSaveError,
        /* 600 */ FillColor,

        /* 601 */ FillImage,
        /* 602 */ TreeIndividualsCount,
        /* 603 */ LogView,
        /* 604 */ AncestorsCircle,
        /* 605 */ Circle,
        /* 606 */ TextColor,
        /* 607 */ BackColor,
        /* 608 */ LinesColor,
        /* 609 */ RestrictNone,
        /* 610 */ RestrictLocked,
        /* 611 */ RestrictConfidential,
        /* 612 */ RestrictPrivacy,
        /* 613 */ LogSend,
        /* 614 */ Charts,
        /* 615 */ SizeToFit,
        /* 616 */ ZoomIn,
        /* 617 */ ZoomOut,
        /* 618 */ SetIsDead,
        /* 619 */ DefineSex,
        /* 620 */ Plugins,
        /* 621 */ TM_TraceKinships,
        /* 622 */ NoMatchesFound,
        /* 623 */ FindPrevious,
        /* 624 */ FindNext,
        /* 625 */ CertaintyIndex,
        /* 626 */ BirthByMonth,
        /* 627 */ Month,
        /* 628 */ DlgReset,
        /* 629 */ Field,
        /* 630 */ Condition,
        /* 631 */ DoNotSetSource,
        /* 632 */ Slideshow,
        /* 633 */ PrevRec,
        /* 634 */ NextRec,
        /* 635 */ GenerationFailed,
        /* 636 */ Start,
        /* 637 */ Stop,
        /* 638 */ Demography,
        /* 639 */ Names,
        /* 640 */ NTAka,
        /* 641 */ NTBirth,
        /* 642 */ NTImmigrant,
        /* 643 */ NTMaiden,
        /* 644 */ NTMarried,
        /* 645 */ RemoveNameQuery,
        /* 646 */ RemoveNameFailed,
        /* 647 */ Quote,
        /* 648 */ BookmarkMerged,
        /* 649 */ ShowDatesCalendar,
        /* 650 */ RecordDuplicate,
        /* 651 */ DuplicateWarning,
        /* 652 */ ShowDatesSigns,
        /* 653 */ FileNewTip,
        /* 654 */ FileLoadTip,
        /* 655 */ FileSaveTip,
        /* 656 */ RecordAddTip,
        /* 657 */ RecordEditTip,
        /* 658 */ RecordDeleteTip,
        /* 659 */ FilterTip,
        /* 660 */ TreeAncestorsTip,
        /* 661 */ TreeDescendantsTip,
        /* 662 */ TreeBothTip,
        /* 663 */ PedigreeTip,
        /* 664 */ AscendNumbering,
        /* 665 */ DescendNumbering,
        /* 666 */ StatsTip,
        /* 667 */ ImageSaveTip,
        /* 668 */ ModesTip,
        /* 669 */ NewScriptTip,
        /* 670 */ LoadScriptTip,
        /* 671 */ SaveScriptTip,
        /* 672 */ RunScriptTip,
        /* 673 */ PortraitAddTip,
        /* 674 */ PortraitDeleteTip,
        /* 675 */ ParentsAddTip,
        /* 676 */ ParentsEditTip,
        /* 677 */ ParentsDeleteTip,
        /* 678 */ FatherAddTip,
        /* 679 */ FatherDeleteTip,
        /* 680 */ FatherSelTip,
        /* 681 */ MotherAddTip,
        /* 682 */ MotherDeleteTip,
        /* 683 */ MotherSelTip,
        /* 684 */ NameCopyTip,
        /* 685 */ HusbandAddTip,
        /* 686 */ HusbandDeleteTip,
        /* 687 */ HusbandSelTip,
        /* 688 */ WifeAddTip,
        /* 689 */ WifeDeleteTip,
        /* 690 */ WifeSelTip,
        /* 691 */ PersonAttachTip,
        /* 692 */ PlaceAddTip,
        /* 693 */ PlaceDeleteTip,
        /* 694 */ ShowOnMapTip,
        /* 695 */ SourceAddTip,
        /* 696 */ GoalSelectTip,
        /* 697 */ NewDBFileNeedToSave,
        /* 698 */ FileWithSameNameAlreadyExists,
        /* 699 */ ItsNotGEDSECCompatibleFile,
        /* 700 */ ThisPersonHasSeveralFamilies,

        /* 701 */ UploadErrorInExcel,
        /* 702 */ PersonsFilter,
        /* 703 */ LinesVisible,
        /* 704 */ MatchType,
        /* 705 */ MatchInternal,
        /* 706 */ MathExternal,
        /* 707 */ Analyze,
        /* 708 */ Match,
        /* 709 */ WithoutDates,
        /* 710 */ PatriarchsDiagram,
        /* 711 */ FamilyBook,
        /* 712 */ TableOfContents,
        /* 713 */ PersonalRecords,
        /* 714 */ Indexes,
        /* 715 */ NotDeterminedPersonSex,
        /* 716 */ Autosave,
        /* 717 */ Minutes,
        /* 718 */ IncludeGenerations,
        /* 719 */ HideEmptySegments,
        /* 720 */ DescendantsCircle,
        /* 721 */ PortraitSelect,
        /* 722 */ RelationshipCalculator,
        /* 723 */ RelationshipMask,
        /* 724 */ BirthdayToday,
        /* 725 */ BirthdayTomorrow,
        /* 726 */ BloodGroup,
        /* 727 */ HairColor,
        /* 728 */ EyesColor,
        /* 729 */ MDNAHaplogroup,
        /* 730 */ YDNAHaplogroup,
        /* 731 */ RecordIsLocked,
        /* 732 */ MaidenSurname,
        /* 733 */ MarriedSurname,
        /* 734 */ AdditionalNames, // TODO: better text
        /* 735 */ ExtendedWomanSurnames,
        /* 736 */ WSF_Maiden_Married,
        /* 737 */ WSF_Married_Maiden,
        /* 738 */ WSF_Maiden,
        /* 739 */ WSF_Married,
        /* 740 */ HusbSign,
        /* 741 */ WifeSign,
        /* 742 */ Geocoder,
        /* 743 */ FatherAdd,
        /* 744 */ MotherAdd,
        /* 745 */ DefaultPortraits,
        /* 746 */ RemovableMediaWarningMessage,
        /* 747 */ RemovableMediaWarningOption,
        /* 748 */ LoadRecentFiles,
        /* 749 */ HolidayToday,
        /* 750 */ HolidayTomorrow,
        /* 751 */ DaysRemainedBeforeHoliday,
        /* 752 */ Holidays,
        /* 753 */ EmbeddedMediaPlayer,
        /* 754 */ AllowMediaDirectReferences,
        /* 755 */ CopyingFile,
        /* 756 */ Actions,
        /* 757 */ SelectAndCopy,
        /* 758 */ NumberSym,
        /* 759 */ Reports,
        /* 760 */ InvertedTree,
        /* 761 */ MarriagesDates,
        /* 762 */ AutoCheckUpdates,
        /* 763 */ ArcText,
        /* 764 */ TreesAlbum,
        /* 765 */ ShowPlaces,
        /* 766 */ HideUnknownSpouses,
        /* 767 */ Spacings,
        /* 768 */ Margins,
        /* 769 */ BranchDist,
        /* 770 */ GenDist,
        /* 771 */ SpouseDist,
        /* 772 */ ImageSize,
        /* 773 */ DetectedDataLoop,
        /* 774 */ FatherAsChild,
        /* 775 */ MotherAsChild,
        /* 776 */ DuplicateChildrenInFamily,
        /* 777 */ SelectColor,
        /* 778 */ AutoSortChildren,
        /* 779 */ AutoSortSpouses,
        /* 780 */ CheckTreeSize,
        /* 781 */ PLT_Adopted,
        /* 782 */ PLT_Birth,
        /* 783 */ PLT_Foster,
        /* 784 */ CharsetDetection,
        /* 785 */ LinkageType,
        /* 786 */ HeWasBorn,
        /* 787 */ SheWasBorn,
        /* 788 */ GedMLFilter,
        /* 789 */ ChildWithoutParents,
        /* 790 */ FamilyRecordWithoutFamily,
        /* 791 */ MediaFileDeleteQuery,
        /* 792 */ StgNotFound,
        /* 793 */ FileNotFound,
        /* 794 */ AllowMediaRelativeReferences,
        /* 795 */ MediaStoreDefault,
        /* 796 */ AllowDeleteMediaFileFromStgArc,
        /* 797 */ AllowDeleteMediaFileFromRefs,
        /* 798 */ DeleteMediaFileWithoutConfirm,
        /* 799 */ MediaRecordWithoutFiles,
        /* 800 */ ArcNotFound,

        /* 801 */ RI_GeorgeKnight = 801,
        /* 802 */ USSR_WWII_Combatant,
        /* 803 */ USSR_WWII_KilledInBattle,
        /* 804 */ USSR_WWII_WorkerInRear,
        /* 805 */ USSR_Repressed,
        /* 806 */ Religion_Islam,
        /* 807 */ Religion_Catholicism,
        /* 808 */ Religion_Orthodoxy,
        /* 809 */ Religion_TheOldBelievers,

        /* 810 */ STRel,
        /* 811 */ BackupRevisionsMaxCount,
        /* 812 */ FirstCapitalLetterInNames,
        /* 813 */ DefaultDepth,
        /* 814 */ WarningOfDialogUnsavedChanges,
        /* 815 */ WarnForClosingDialog,
        /* 816 */ DottedLinesOfAdoptedChildren,
        /* 817 */ GoToPersonRecord,
        /* 818 */ STWeb,
        /* 819 */ SeparateDatesAndPlacesLines,
        /* 820 */ Details,
        /* 821 */ CopyXRef,
        /* 822 */ BoldNames,

        /* 823 */ Baptism,
        /* 824 */ BarMitzvah,
        /* 825 */ BatMitzvah,
        /* 826 */ Blessing,
        /* 827 */ AdultChristening,
        /* 828 */ Confirmation,
        /* 829 */ FirstCommunion,
        /* 830 */ Ordination,
        /* 831 */ GeoSearchCountryRestriction,
        /* 832 */ SeparateDepth,
        /* 833 */ Ancestors,
        /* 834 */ MatchesNotFound,
        /* 835 */ ShortKinshipForm,
        /* 836 */ SurnameFirstInOrder,
        /* 837 */ Borders,
        /* 838 */ UpdateToLatestVersion,
        /* 839 */ Providers,
        /* 840 */ Coordinates,
        /* 841 */ LoadPlaces,
        /* 842 */ OnlyLocality,
        /* 843 */ GoToPrimaryBranch,
        /* 844 */ MinimizingWidth,
        /* 845 */ ContinueQuestion,
        /* 846 */ ShowAge,
        /* 847 */ SurnameInCapitals,
        /* 848 */ SvgFilter,
        /* 849 */ CertaintyAlgorithm,
        /* 850 */ LocalizedCalendarSignaturesOptLabel,
        /* 851 */ LocalizedCalendarSignaturesValues,
        /* 852 */ Copy,
        /* 853 */ Cut,
        /* 854 */ Paste,
        /* 855 */ PersonHasHalfLinkOfSpouseToFamily,
        /* 856 */ PersonHasHalfLinkOfChildToFamily,
        /* 857 */ FamilyHasHalfLinkOfHusbandToPerson,
        /* 858 */ FamilyHasHalfLinkOfWifeToPerson,
        /* 859 */ FamilyHasHalfLinkOfChildToParentsFamily,
        /* 860 */ GarbledSpouses,
        /* 861 */ USSR_CPSUMember,
        /* 862 */ RepoRecsMergeWarning,
        /* 863 */ UseExtraControls,
        /* 864 */ SeveralFamiliesOfParents,
        /* 865 */ Specials,
        /* 866 */ UseInlineImagesInSvg,
        /* 867 */ UseExtendedNotes,
        /* 868 */ KeepRichNames,
        /* 869 */ ChartWindowsShowMode,
        /* 870 */ ExtendedTree,
        /* 871 */ FanMode,
        /* 872 */ OpenInNewWindow,
        /* 873 */ UnknownPlaceOfPerson,
        /* 874 */ CheckPersonPlaces,
        /* 875 */ HighlightInaccessibleFiles,
        /* 876 */ DifferenceBetweenSpousesIsAbnormallyHigh,
        /* 877 */ DifferenceBetweenSiblingsIsAbnormallyHigh,

        /* 878 */ FindAndReplace,
        /* 879 */ Find,
        /* 880 */ ReplaceWith,
        /* 881 */ MatchCase,
        /* 882 */ MatchWildcards,
        /* 883 */ WholeWord,
        /* 884 */ Replace,
        /* 885 */ ReplaceAll,
        /* 886 */ Property,

        /* 887 */ Themes,
        /* 888 */ URTreeNoteType,
        /* 889 */ ShowTreeNotes,
        /* 890 */ NoGoalRecordSpecified,
        /* 891 */ InvalidFileName,
        /* 892 */ SearchAndFilterByAllNames,
        /* 893 */ DataQuality,
        /* 894 */ DQHint,
        /* 895 */ Refresh,
        /* 896 */ ResetFilter,
        /* 897 */ ShortenDateRanges,
        /* 898 */ PressEnterToSaveFilter,

        /* 899 */ AnniversaryToday,
        /* 900 */ AnniversaryTomorrow,
        /* 901 */ AnniversaryDaysRemained,
        /* 902 */ SourceYear,
        /* 903 */ AgeAtYear,
        /* 904 */ KeepInfoPansOverallSize,
        /* 905 */ XRefVisible,

        /* 906 */ RK_FathersWife,
        /* 907 */ RK_MothersHusband,
        /* 908 */ Swap,
        /* 909 */ FilesOverwriteWarn,
        /* 910 */ SameCardsWidth,

        /* 911 */ RK_Uncle_AuntHusband,
        /* 912 */ RK_Aunt_UncleWife,
        /* 913 */ HideDescSpouses,

        /* 914 */ RE_Blood,
        /* 915 */ RE_Uterine,
        /* 916 */ RE_Adoptive,
        /* 917 */ RE_Adopted,
        /* 918 */ RE_CommonLaw,

        /* 919 */ Reserved_919,
        /* 920 */ Reserved_920,

        /* 921 */ KinshipDegree_01,
        /* 922 */ KinshipDegree_02,
        /* 923 */ KinshipDegree_03,
        /* 924 */ KinshipDegree_04,
        /* 925 */ KinshipDegree_05,
        /* 926 */ KinshipDegree_06,
        /* 927 */ KinshipDegree_07,
        /* 928 */ KinshipDegree_08,
        /* 929 */ KinshipDegree_09,
        /* 930 */ KinshipDegree_10,

        /* 931 */ ExtendedKinships,
        /* 932 */ UseSurnamesInPersonSelectionFilter,
        /* 933 */ UseBirthDatesInPersonSelectionFilter,
        /* 934 */ FactValueIsInvalid,
        /* 935 */ Portrait,
        /* 936 */ CensusAnalysis,
        /* 937 */ PersonCanBeFoundInCensus,
        /* 938 */ History,
        /* 939 */ PeriodsOverlap,
        /* 940 */ ExtendedLocations,
        /* 941 */ PhotosBatchAdding,
        /* 942 */ AddedNPhotos,
        /* 943 */ TopLevelLinks,
        /* 944 */ RemoveTopLevelLinkQuery,
        /* 945 */ HelpIsNotAvailable,
        /* 946 */ AddressLine,

        /* 947 */ CWSM_Default,
        /* 948 */ CWSM_Maximize,
        /* 949 */ CWSM_LeftHalf,
        /* 950 */ CWSM_RightHalf,

        /* 951 */ RI_Recruit,
        /* 952 */ ReversePlacesOrder,
        /* 953 */ EL_AbbreviatedNames,
        /* 954 */ DottedLinesOfCommonLawSpouses,
        /* 955 */ ShowNumberOfSubstructures,
        /* 956 */ CleanImagesCache,
        /* 957 */ TrackSelectedLines,
        /* 958 */ TrackMatchedSources,
        /* 959 */ NoteWithoutLinks,
        /* 960 */ SourceWithoutLinks,
        /* 961 */ CheckLinks,

        /* 962 */ EventTypes,
        /* 963 */ Count,
        /* 964 */ Enabled,
        /* 965 */ Tag,
        /* 966 */ Description,
        /* 967 */ TagTypeWarning,
        /* 968 */ EventDefinition,
        /* 969 */ FullNameOnOneLine,
        /* 970 */ MatchPatternMethod,

        /* 971 */ TBS_Single,
        /* 972 */ TBS_Double,
        /* 973 */ TBS_Triple,
        /* 974 */ TBS_Sunken3D,
        /* 975 */ TBS_Raised3D,
        /* 976 */ TBS_SingleSquareCuts,
        /* 977 */ TBS_DoubleSquareCuts,
        /* 978 */ TBS_SingleRoundCuts,
        /* 979 */ TBS_DoubleRoundCuts,
        /* 980 */ TBS_SingleBevels,
        /* 981 */ TBS_DoubleBevels,
        /* 982 */ TBS_CrossCorners,

        /* 983 */ SelList,
        /* 984 */ SubordinateLocationsLinks,
        /* 985 */ LocExpert,
        /* 986 */ EventDates,
        /* 987 */ DoAdd,
        /* 988 */ Entry,
        /* 989 */ IncludeSourcePages,
        /* 990 */ Navigation,
        /* 991 */ IncludePortraits,
        /* 992 */ PartialViewTip,
        /* 993 */ CallNumber,
        /* 994 */ CallNumbers,
        /* 995 */ RemoveCallNumberQuery,
        /* 996 */ RepositoryIsNotSpecified,
        /* 997 */ ParentsAge,
        /* 998 */ SimpleSingleSurnames,
        /* 999 */ MapOfPlaces,
        /* 1000 */ MapOfPersons,
        /* 1001 */ SearchPlacesWithoutCoords,
        /* 1002 */ LocationsAndMaps,
        /* 1003 */ TextEffect,
        /* 1004 */ TE_Simple,
        /* 1005 */ TE_Sunken,
        /* 1006 */ TE_Raised,
        /* 1007 */ TE_Glow,
        /* 1008 */ Padding,
        /* 1009 */ DateDesignations,
        /* 1010 */ MourningEdges,
        /* 1011 */ UseAdditionalDates,
        /* 1012 */ CursorCoords,
        /* 1013 */ CondContainsMask,
        /* 1014 */ CondNotContainsMask,
        /* 1015 */ MoveFiles,
        /* 1016 */ InvalidLink,
        /* 1017 */ DisplayFullFileName,
        /* 1018 */ NoteMaxSizeExceeded,

        /* 000 */ Last = NoteMaxSizeExceeded
    }


    public static class LangMan
    {
        public const int LS_DEF_CODE = 1033;
        public const string LS_DEF_SIGN = "enu";
        public const string LS_DEF_NAME = "English";

        private static readonly string[] LSDefList = new string[]
        {
            /* 001 */ "File",
            /* 002 */ "Edit",
            /* 003 */ "Pedigree",
            /* 004 */ "Service",
            /* 005 */ "&Windows",
            /* 006 */ "Help",
            /* 007 */ "New",
            /* 008 */ "Open...",
            /* 009 */ "Reopen",
            /* 010 */ "Save",
            /* 011 */ "Close",
            /* 012 */ "Properties",
            /* 013 */ "Export",
            /* 014 */ "Book of families...",
            /* 015 */ "Save As...",
            /* 016 */ "Export table...",
            /* 017 */ "Exit",
            /* 018 */ "Import",
            /* 019 */ "Clear",
            /* 020 */ "Add record",
            /* 021 */ "Edit record",
            /* 022 */ "Delete record",
            /* 023 */ "<?>",
            /* 024 */ "Ancestors tree",
            /* 025 */ "Descendants tree",
            /* 026 */ "Complete tree",
            /* 027 */ "Descending pedigree",
            /* 028 */ "<?>",
            /* 029 */ "Maps",
            /* 030 */ "Statistics",
            /* 031 */ "Ascending pedigree",
            /* 032 */ "d'Aboville",
            /* 033 */ "Kobrin-Konovalov",
            /* 034 */ "Sosa-Stradonitz",
            /* 035 */ "Organizer",
            /* 036 */ "Scripts...",
            /* 037 */ "<?>",
            /* 038 */ "Tools...",
            /* 039 */ "Filter",
            /* 040 */ "Options",
            /* 041 */ "&Cascade",
            /* 042 */ "&Horizontal tile",
            /* 043 */ "&Vertical tile",
            /* 044 */ "&Minimize all",
            /* 045 */ "&Rearrange all",
            /* 046 */ "<?>",
            /* 047 */ "<?>",
            /* 048 */ "<?>",
            /* 049 */ "Content",
            /* 050 */ "About",
            /* 051 */ "Records",
            /* 052 */ "filtered",
            /* 053 */ "Individuals",
            /* 054 */ "Families",
            /* 055 */ "Notes",
            /* 056 */ "Multimedia",
            /* 057 */ "Sources",
            /* 058 */ "Repositories",
            /* 059 */ "Groups",
            /* 060 */ "Researches",
            /* 061 */ "Tasks",
            /* 062 */ "Communications",
            /* 063 */ "Locations",
            /* 064 */ "unknown",
            /* 065 */ "unknown",
            /* 066 */ "?",
            /* 067 */ "Male",
            /* 068 */ "Female",
            /* 069 */ "Intersex",
            /* 070 */ "Do you want to save changes to the modified file?",
            /* 071 */ "The specified parent has an existed family \"{0}\". Do you want to add the child to that family?",
            /* 072 */ "Are you sure you want to remove individual \"{0}\"?",
            /* 073 */ "Are you sure you want to remove family \"{0}\"?",
            /* 074 */ "Are you sure you want to remove note \"{0}\"?",
            /* 075 */ "Are you sure you want to remove source \"{0}\"?",
            /* 076 */ "Are you sure you want to remove multimedia \"{0}\"?",
            /* 077 */ "Are you sure you want to remove repository \"{0}\"?",
            /* 078 */ "Are you sure you want to remove group \"{0}\"?",
            /* 079 */ "Are you sure you want to remove research \"{0}\"?",
            /* 080 */ "Are you sure you want to remove task \"{0}\"?",
            /* 081 */ "Are you sure you want to remove communication \"{0}\"?",
            /* 082 */ "Are you sure you want to remove location \"{0}\"?",
            /* 083 */ "Address",
            /* 084 */ "Events",
            /* 085 */ "Surname",
            /* 086 */ "Given name",
            /* 087 */ "Patronymic",
            /* 088 */ "Sex",
            /* 089 */ "Nickname",
            /* 090 */ "Last name prefix",
            /* 091 */ "Name prefix",
            /* 092 */ "Name suffix",
            /* 093 */ "Patriarch",
            /* 094 */ "Bookmark",
            /* 095 */ "Association",
            /* 096 */ "Relation",
            /* 097 */ "Individual",
            /* 098 */ "Apply",
            /* 099 */ "Cancel",
            /* 100 */ "Close",
            /* 101 */ "Select",
            /* 102 */ "Add new",
            /* 103 */ "Name",
            /* 104 */ "Edit individual",
            /* 105 */ "Checking of sex",
            /* 106 */ "Selecting a record",
            /* 107 */ "Source citation",
            /* 108 */ "User reference",
            /* 109 */ "Note",
            /* 110 */ "Source",
            /* 111 */ "Page",
            /* 112 */ "Certainty",
            /* 113 */ "Reference",
            /* 114 */ "Type",
            /* 115 */ "Family",
            /* 116 */ "Husband",
            /* 117 */ "Wife",
            /* 118 */ "Status",
            /* 119 */ "Children",
            /* 120 */ "Are you sure you want to detach link to husband?",
            /* 121 */ "Are you sure you want to detach link to wife?",
            /* 122 */ "Are you sure you want to detach link to child?",
            /* 123 */ "Birth date",
            /* 124 */ "Death date",
            /* 125 */ "Security restriction",
            /* 126 */ "Title",
            /* 127 */ "Members",
            /* 128 */ "Edit group",
            /* 129 */ "Are you sure you want to detach link to member?",
            /* 130 */ "view",
            /* 131 */ "Stage",
            /* 132 */ "Telephone number",
            /* 133 */ "email",
            /* 134 */ "Web site",
            /* 135 */ "Repository",
            /* 136 */ "Progress",
            /* 137 */ "Elapsed time",
            /* 138 */ "Remaining time",
            /* 139 */ "Total time",
            /* 140 */ "Date",
            /* 141 */ "Text",
            /* 142 */ "Short title",
            /* 143 */ "Author",
            /* 144 */ "Published",
            /* 145 */ "Common",
            /* 146 */ "Are you sure you want to detach link to repository?",
            /* 147 */ "Store type",
            /* 148 */ "File",
            /* 149 */ "View",
            /* 150 */ "Fragment {0}: {1} individuals",
            /* 151 */ "Father",
            /* 152 */ "Mother",
            /* 153 */ "Parents",
            /* 154 */ "Spouses",
            /* 155 */ "Associations",
            /* 156 */ "User references",
            /* 157 */ "Gregorian",
            /* 158 */ "Julian",
            /* 159 */ "Hebrew",
            /* 160 */ "Islamic",
            /* 161 */ "Persian",
            /* 162 */ "Indian",
            /* 163 */ "Bahai",
            /* 164 */ "French",
            /* 165 */ "Roman",
            /* 166 */ "Unknown",
            /* 167 */ "Summary",
            /* 168 */ "Other",
            /* 169 */ "Submission",
            /* 170 */ "Submitter",
            /* 171 */ "Location",
            /* 172 */ "Latitude",
            /* 173 */ "Longitude",
            /* 174 */ "Show",
            /* 175 */ "Search coords",
            /* 176 */ "Search",
            /* 177 */ "Select coords",
            /* 178 */ "Select name",
            /* 179 */ "Priority",
            /* 180 */ "Percent",
            /* 181 */ "Started",
            /* 182 */ "Stopped",
            /* 183 */ "Goal",
            /* 184 */ "Theme",
            /* 185 */ "Corresponder",
            /* 186 */ "Group",
            /* 187 */ "Are you sure you want to detach link to task?",
            /* 188 */ "Are you sure you want to detach link to communication?",
            /* 189 */ "Are you sure you want to detach link to group?",
            /* 190 */ "Edit research",
            /* 191 */ "Edit task",
            /* 192 */ "Edit communication",
            /* 193 */ "Error",
            /* 194 */ "Lua start failed!",
            /* 195 */ "Date format is invalid",
            /* 196 */ "Country",
            /* 197 */ "State",
            /* 198 */ "City",
            /* 199 */ "Postal code",
            /* 200 */ "Telephone numbers",
            /* 201 */ "Emails",
            /* 202 */ "Web sites",
            /* 203 */ "Value",
            /* 204 */ "Event",
            /* 205 */ "Place",
            /* 206 */ "Cause",
            /* 207 */ "Agency",
            /* 208 */ "Female",
            /* 209 */ "Male",
            /* 210 */ "An individual record is not selected.",
            /* 211 */ "This individual has no sex defined.",
            /* 212 */ "This individual has no families.",
            /* 213 */ "Estimated number of ancestors {0} is more than permissible limits.",
            /* 214 */ "Estimated number of descendants {0} is more than permissible limits.",
            /* 215 */ "Generations visible:",
            /* 216 */ "unlimited",
            /* 217 */ "Spouse",
            /* 218 */ "Marriage date",
            /* 219 */ "Are you sure you want to detach link to father?",
            /* 220 */ "Are you sure you want to detach link to mother?",
            /* 221 */ "Are you sure you want to detach link to spouse?",
            /* 222 */ "Are you sure you want to detach link to parents?",
            /* 223 */ "All",
            /* 224 */ "Ancestors only",
            /* 225 */ "Descendants only",
            /* 226 */ "Trace root",
            /* 227 */ "Edit",
            /* 228 */ "Add family",
            /* 229 */ "Add spouse",
            /* 230 */ "Add son",
            /* 231 */ "Add daughter",
            /* 232 */ "Delete",
            /* 233 */ "Rebuild tree",
            /* 234 */ "Rebuild kinships",
            /* 235 */ "Links",
            /* 236 */ "Place and attribute",
            /* 237 */ "marriage",
            /* 238 */ "family",
            /* 239 */ "Namesakes",
            /* 240 */ "Remove the event?",
            /* 241 */ "Are you sure you want to detach link to note?",
            /* 242 */ "Are you sure you want to detach link to multimedia?",
            /* 243 */ "Are you sure you want to detach link to source?",
            /* 244 */ "Are you sure you want to remove the association?",
            /* 245 */ "Are you sure you want to remove reference \"{0}\"?",
            /* 246 */ "Loading of gedcom failed.",
            /* 247 */ "Check gedcom format failed.",
            /* 248 */ "Birth days",
            /* 249 */ "{1} days remain before the birthday of \"{0}\"",
            /* 250 */ "Interface",
            /* 251 */ "Trees",
            /* 252 */ "Pedigrees",
            /* 253 */ "Files encoding",
            /* 254 */ "Addresses",
            /* 255 */ "Mails",
            /* 256 */ "Webs",
            /* 257 */ "Internet",
            /* 258 */ "Use proxy",
            /* 259 */ "Server",
            /* 260 */ "Port",
            /* 261 */ "Login",
            /* 262 */ "Password",
            /* 263 */ "The password is not specified",
            /* 264 */ "Show tips on startup",
            /* 265 */ "Language",
            /* 266 */ "All lists",
            /* 267 */ "List of individuals",
            /* 268 */ "Name format in lists",
            /* 269 */ "Surname Name Patronymic",
            /* 270 */ "Surname | Name Patronymic",
            /* 271 */ "Surname | Name | Patronymic",
            /* 272 */ "Date format in lists",
            /* 273 */ "Include address into place text",
            /* 274 */ "Highlight unparented",
            /* 275 */ "Highlight unmarried",
            /* 276 */ "Default values",
            /* 277 */ "Show individuals in tree",
            /* 278 */ "Separate lines",
            /* 279 */ "Only years",
            /* 280 */ "Kinship",
            /* 281 */ "Additional symbols",
            /* 282 */ "Tree decorative",
            /* 283 */ "Show portraits",
            /* 284 */ "Hide died in childhood",
            /* 285 */ "Decor",
            /* 286 */ "Man",
            /* 287 */ "Woman",
            /* 288 */ "Unknown sex",
            /* 289 */ "Divorcee husband",
            /* 290 */ "Divorcee wife",
            /* 291 */ "Font",
            /* 292 */ "Pedigree generation",
            /* 293 */ "Include attributes of individuals",
            /* 294 */ "Include notes",
            /* 295 */ "Include sources",
            /* 296 */ "Pedigree format",
            /* 297 */ "Excess",
            /* 298 */ "Compact",
            /* 299 */ "Jump to a record",
            /* 300 */ "Move record up",
            /* 301 */ "Move record down",
            /* 302 */ "Full name",
            /* 303 */ "Birth place",
            /* 304 */ "Death place",
            /* 305 */ "Residence",
            /* 306 */ "Age",
            /* 307 */ "Lifetime",
            /* 308 */ "Days before birth",
            /* 309 */ "Religion",
            /* 310 */ "Nationality",
            /* 311 */ "Education",
            /* 312 */ "Occupation",
            /* 313 */ "Caste",
            /* 314 */ "Military Service",
            /* 315 */ "Military Induction",
            /* 316 */ "Military Discharge",
            /* 317 */ "Military Rank",
            /* 318 */ "Changed",
            /* 319 */ "Marriage registered",
            /* 320 */ "Marriage is not registered",
            /* 321 */ "Divorced",
            /* 322 */ "Birth",
            /* 323 */ "Adoption",
            /* 324 */ "Christening (child)",
            /* 325 */ "Graduation",
            /* 326 */ "Retirement",
            /* 327 */ "Naturalization",
            /* 328 */ "Emigration",
            /* 329 */ "Immigration",
            /* 330 */ "Census",
            /* 331 */ "Will",
            /* 332 */ "Probate of will",
            /* 333 */ "Death",
            /* 334 */ "Burial",
            /* 335 */ "Cremation",
            /* 336 */ "Fact",
            /* 337 */ "Physical description",
            /* 338 */ "National ID Number",
            /* 339 */ "Social security number",
            /* 340 */ "Number of children",
            /* 341 */ "Number of marriages",
            /* 342 */ "Property",
            /* 343 */ "Title",
            /* 344 */ "Travel",
            /* 345 */ "Hobby",
            /* 346 */ "Award",
            /* 347 */ "?",
            /* 348 */ "father",
            /* 349 */ "mother",
            /* 350 */ "husband",
            /* 351 */ "wife",
            /* 352 */ "son",
            /* 353 */ "daughter",
            /* 354 */ "grandfather",
            /* 355 */ "grandmother",
            /* 356 */ "grandson",
            /* 357 */ "granddaughter",
            /* 358 */ "brother",
            /* 359 */ "sister",
            /* 360 */ "son-in-law",
            /* 361 */ "daughter-in-law",
            /* 362 */ "father-in-law",
            /* 363 */ "mother-in-law",
            /* 364 */ "father-in-law",
            /* 365 */ "mother-in-law",
            /* 366 */ "uncle",
            /* 367 */ "aunt",
            /* 368 */ "nephew",
            /* 369 */ "niece",
            /* 370 */ "cousin",
            /* 371 */ "cousin",
            /* 372 */ "brother-in-law",
            /* 373 */ "sister-in-law",
            /* 374 */ "brother-in-law",
            /* 375 */ "sister-in-law",
            /* 376 */ "great",
            /* 377 */ "uncle",
            /* 378 */ "aunt",
            /* 379 */ "stepfather",
            /* 380 */ "stepmother",
            /* 381 */ "Image width is more than 65,000 pixels. Unable to save.",
            /* 382 */ "Back",
            /* 383 */ "Next",
            /* 384 */ "Previous",
            /* 385 */ "Next",
            /* 386 */ "You know that ...",
            /* 387 */ "Loading and searching places",
            /* 388 */ "(not selected)",
            /* 389 */ "Sample",
            /* 390 */ "For all people",
            /* 391 */ "Places of birth",
            /* 392 */ "Places of death",
            /* 393 */ "Places of residence",
            /* 394 */ "Only selected",
            /* 395 */ "Save image...",
            /* 396 */ "The format is not supported",
            /* 397 */ "Error loading data.",
            /* 398 */ "Print",
            /* 399 */ "Preview",
            /* 400 */ "Generation",
            /* 401 */ "contains",
            /* 402 */ "not contains",
            /* 403 */ "Exact",
            /* 404 */ "Before",
            /* 405 */ "After",
            /* 406 */ "Between",
            /* 407 */ "Period before",
            /* 408 */ "Period from",
            /* 409 */ "Period between",
            /* 410 */ "About",
            /* 411 */ "Calculated",
            /* 412 */ "Estimated",
            /* 413 */ "Engagement",
            /* 414 */ "Marriage",
            /* 415 */ "Public announcement of the marriage",
            /* 416 */ "Marriage contract",
            /* 417 */ "Obtaining permission to marry",
            /* 418 */ "Conclusion of the marriage agreement",
            /* 419 */ "Annulment of marriage",
            /* 420 */ "Filing of divorce",
            /* 421 */ "Divorce",
            /* 422 */ "Link to file",
            /* 423 */ "Saving to the archive",
            /* 424 */ "Saving to the store",
            /* 425 */ "-",
            /* 426 */ "Audio",
            /* 427 */ "Book",
            /* 428 */ "Card",
            /* 429 */ "Electronic",
            /* 430 */ "Fiche",
            /* 431 */ "Film",
            /* 432 */ "Magazine",
            /* 433 */ "Manuscript",
            /* 434 */ "Map",
            /* 435 */ "Newspaper",
            /* 436 */ "Photo",
            /* 437 */ "Tombstone",
            /* 438 */ "Video",
            /* 439 */ "- Unknown -",
            /* 440 */ "None",
            /* 441 */ "Low",
            /* 442 */ "Normal",
            /* 443 */ "High",
            /* 444 */ "Top",
            /* 445 */ "Defined",
            /* 446 */ "In progress",
            /* 447 */ "On hold",
            /* 448 */ "Problems",
            /* 449 */ "Completed",
            /* 450 */ "Withdrawn",
            /* 451 */ "Call",
            /* 452 */ "EMail",
            /* 453 */ "Fax",
            /* 454 */ "Letter",
            /* 455 */ "Tape",
            /* 456 */ "Visit",
            /* 457 */ "from",
            /* 458 */ "to",
            /* 459 */ "individual",
            /* 460 */ "family",
            /* 461 */ "source",
            /* 462 */ "other",
            /* 463 */ "Unreliable evidence",
            /* 464 */ "Questionable reliability of evidence",
            /* 465 */ "Circumstantial evidence",
            /* 466 */ "Direct and primary evidence",
            /* 467 */ "Research",
            /* 468 */ "Task",
            /* 469 */ "Correspondence",
            /* 470 */ "Correcting IDs",
            /* 471 */ "Checking format",
            /* 472 */ "Correction of identity records is required, continue?", // obsolete
            /* 473 */ "Number of objects in the master database: {0}",
            /* 474 */ "Synchronization is complete.",
            /* 475 */ "Identifying the patriarchs",
            /* 476 */ "Checking links",
            /* 477 */ "Archive not found, the data is not loaded",
            /* 478 */ "Scale",
            /* 479 */ "GEDKeeper GEDCOM files (*.ged)|*.ged|GEDKeeper GEDCOM encrypted files (*.geds)|*.geds",
            /* 480 */ "All files (*.*)|*.*",
            /* 481 */ "Images (*.bmp,*.gif,*.png,*.jpg)|*.bmp,*.gif,*.png,*.jpg",
            /* 482 */ "Scripts (*.lua)|*.lua",
            /* 483 */ "BMP files (*.bmp)|*.bmp|JPEG files (*.jpg)|*.jpg|EMF files (*.emf)|*.emf|PNG files (*.png)|*.png|GIF files (*.gif)|*.gif",
            /* 484 */ "Death causes",
            /* 485 */ "Pedigree",
            /* 486 */ "Parameter",
            /* 487 */ "Total",
            /* 488 */ "Men",
            /* 489 */ "Women",
            /* 490 */ "Fields filter",
            /* 491 */ "Year",
            /* 492 */ "PDF files (*.pdf)|*.pdf",
            /* 493 */ "RTF files (*.rtf)|*.rtf",
            /* 494 */ "HTML files (*.html)|*.html",
            /* 495 */ "Files backup",
            /* 496 */ "only previous file",
            /* 497 */ "Cutting off the branches",
            /* 498 */ "not",
            /* 499 */ "on years",
            /* 500 */ "in selected individuals",
            /* 501 */ "- all -",
            /* 502 */ "- not -",
            /* 503 */ "- any -",
            /* 504 */ "Master database",
            /* 505 */ "Database to merge",
            /* 506 */ "[current database]",
            /* 507 */ "There is a filter by a source. Do you want to add the source to a new individual?",
            /* 508 */ "There is a filter by a group. Do you want to add the group to a new individual?",
            /* 509 */ "Duplicates search",
            /* 510 */ "Invalid value",
            /* 511 */ "Operation",
            /* 512 */ "Compare databases",
            /* 513 */ "Merge databases",
            /* 514 */ "Split database",
            /* 515 */ "Merge records",
            /* 516 */ "Search unlinked namesakes",
            /* 517 */ "Check connection of families",
            /* 518 */ "Check database",
            /* 519 */ "Find the patriarchs",
            /* 520 */ "Manage places",
            /* 521 */ "Matching...",
            /* 522 */ "Check connection of families",
            /* 523 */ "all",
            /* 524 */ "living only ",
            /* 525 */ "dead only",
            /* 526 */ "Lived before",
            /* 527 */ "men only",
            /* 528 */ "women only",
            /* 529 */ "Mask of name",
            /* 530 */ "Mask of residence",
            /* 531 */ "Mask of the facts",
            /* 532 */ "Patriarchs only",
            /* 533 */ "Date is invalid",
            /* 534 */ "People",
            /* 535 */ "Years",
            /* 536 */ "Decade",
            /* 537 */ "Born",
            /* 538 */ "Died",
            /* 539 */ "Living",
            /* 540 */ "Dead",
            /* 541 */ "Average age",
            /* 542 */ "Life expectancy",
            /* 543 */ "Average number of children",
            /* 544 */ "Average age of the first child birth",
            /* 545 */ "Average number of marriages",
            /* 546 */ "Average age of marriage",
            /* 547 */ "Number of ancestors",
            /* 548 */ "Number of descendants",
            /* 549 */ "Number of generations of descendants",
            /* 550 */ "Birth years",
            /* 551 */ "Birth years (decades)",
            /* 552 */ "Death years",
            /* 553 */ "Death years (decades)",
            /* 554 */ "Distribution of the number of children",
            /* 555 */ "Age of first child birth",
            /* 556 */ "Age at marriage",
            /* 557 */ "Age difference of spouses",
            /* 558 */ "Select all links",
            /* 559 */ "Select family",
            /* 560 */ "Select ancestors",
            /* 561 */ "Select descendants",
            /* 562 */ "Merge",
            /* 563 */ "Search",
            /* 564 */ "Skip",
            /* 565 */ "Records",
            /* 566 */ "Search persons",
            /* 567 */ "Direct matching",
            /* 568 */ "Indistinct matching",
            /* 569 */ "Only by name / middle name (women only)",
            /* 570 */ "Check the year of birth",
            /* 571 */ "The accuracy of the name, %",
            /* 572 */ "Years inaccuracy",
            /* 573 */ "Repair",
            /* 574 */ "Generations of descendants, not less than",
            /* 575 */ "Set a sign",
            /* 576 */ "Register in list of locations",
            /* 577 */ "Similar surnames:",
            /* 578 */ "Similar names:",
            /* 579 */ "Selected personal records removed",
            /* 580 */ "Record",
            /* 581 */ "Problem",
            /* 582 */ "Solve",
            /* 583 */ "Perhaps died (age {0})",
            /* 584 */ "Sex is undefined",
            /* 585 */ "Year of birth more than year of death",
            /* 586 */ "The first marriage at the age of {0} years?",
            /* 587 */ "The first child was born at the age of {0} years?",
            /* 588 */ "Descendants",
            /* 589 */ "Generations",
            /* 590 */ "Number of links",
            /* 591 */ "Processing places",
            /* 592 */ "The place is already in the locations list",
            /* 593 */ "DNA markers",
            /* 594 */ "Average age of parents at the time first-born appeared, relative to parents age",
            /* 595 */ "Average age of parents at the time first-born appeared, relative to children age",
            /* 596 */ "Empty family record",
            /* 597 */ "each file revision",
            /* 598 */ "Loading",
            /* 599 */ "File saving error \"{0}\"{1}.",
            /* 600 */ "Background color...",
            /* 601 */ "Background image...",
            /* 602 */ "Persons in tree: {0}",
            /* 603 */ "View the error log",
            /* 604 */ "Ancestors Circle",
            /* 605 */ "Circle",
            /* 606 */ "Text color",
            /* 607 */ "Back color",
            /* 608 */ "Lines color",
            /* 609 */ "None",
            /* 610 */ "Locked",
            /* 611 */ "Confidential",
            /* 612 */ "Privacy",
            /* 613 */ "Send the error log",
            /* 614 */ "Charts",
            /* 615 */ "Fit window size",
            /* 616 */ "Zoom in",
            /* 617 */ "Zoom out",
            /* 618 */ "Ascertain a fact of death",
            /* 619 */ "Determine a sex",
            /* 620 */ "Plugins",
            /* 621 */ "Auto-trace relationships",
            /* 622 */ "No matches found",
            /* 623 */ "Find previous",
            /* 624 */ "Find next",
            /* 625 */ "The certainty index",
            /* 626 */ "Monthes of birth",
            /* 627 */ "Month",
            /* 628 */ "Reset",
            /* 629 */ "Field",
            /* 630 */ "Condition",
            /* 631 */ "Source is not specified",
            /* 632 */ "Slideshow",
            /* 633 */ "Previous record",
            /* 634 */ "Next record",
            /* 635 */ "Generation failed",
            /* 636 */ "Start",
            /* 637 */ "Stop",
            /* 638 */ "Demographics",
            /* 639 */ "Names",
            /* 640 */ "Name-nickname",
            /* 641 */ "Birth name",
            /* 642 */ "In immigration",
            /* 643 */ "Maiden name",
            /* 644 */ "Marriage name",
            /* 645 */ "Delete a name?",
            /* 646 */ "You cannot delete the single name",
            /* 647 */ "Quote",
            /* 648 */ "Place a bookmark on merged records",
            /* 649 */ "Show calendar near dates",
            /* 650 */ "Duplicate record",
            /* 651 */ "Attention: if you duplicate an individual, family links and associations are not copied",
            /* 652 */ "Show date type",
            /* 653 */ "Create a new tree file",
            /* 654 */ "Open the tree file",
            /* 655 */ "Save tree file",
            /* 656 */ "Add record (Ctrl+I)",
            /* 657 */ "Edit record (Ctrl+Enter)",
            /* 658 */ "Delete record (Ctrl+L)",
            /* 659 */ "Filtering list of records",
            /* 660 */ "Show a tree of ancestors",
            /* 661 */ "Show a tree of descendants",
            /* 662 */ "Show full tree",
            /* 663 */ "Pedigree",
            /* 664 */ "Ascend numbering",
            /* 665 */ "Descend numbering",
            /* 666 */ "Statistical analysis of data",
            /* 667 */ "Save the image",
            /* 668 */ "Display modes",
            /* 669 */ "Create a new script",
            /* 670 */ "Open a script",
            /* 671 */ "Save script",
            /* 672 */ "Execute the script",
            /* 673 */ "Attach the portrait",
            /* 674 */ "Detach the portrait",
            /* 675 */ "Join the family of parents",
            /* 676 */ "Edit the family of the parents",
            /* 677 */ "Disconnect family parents",
            /* 678 */ "Select or add the father",
            /* 679 */ "Disconnect father",
            /* 680 */ "Go to the record of the father",
            /* 681 */ "Select or add the mother",
            /* 682 */ "Disconnect mother",
            /* 683 */ "Go to the record of the mother",
            /* 684 */ "Copy name to clipboard",
            /* 685 */ "Select or add husband",
            /* 686 */ "Disconnect husband",
            /* 687 */ "Go to the record of the husband",
            /* 688 */ "Select or add wife",
            /* 689 */ "Disconnect wife",
            /* 690 */ "Go to the record of the wife",
            /* 691 */ "Choose an individual",
            /* 692 */ "Select or add a location",
            /* 693 */ "Remove the link to the place",
            /* 694 */ "Show the map",
            /* 695 */ "Select or add a record of source",
            /* 696 */ "Select the target record",
            /* 697 */ "If you use \"archive\" or \"storage\" type, you have to save new database file before continue",
            /* 698 */ "A file with the same name already exists",
            /* 699 */ "It's not a GEDSEC-compatible file",
            /* 700 */ "This individual has a few families. Children should be added via the spouses.",
            /* 701 */ "Export to Excel failed",
            /* 702 */ "Specific filter",
            /* 703 */ "Display lines",
            /* 704 */ "Type of comparison",
            /* 705 */ "Internal comparing (search for duplicates)",
            /* 706 */ "Comparing with another database",
            /* 707 */ "Analyze",
            /* 708 */ "Compare",
            /* 709 */ "Ignore dates",
            /* 710 */ "Chart",
            /* 711 */ "Family book",
            /* 712 */ "Table of contents",
            /* 713 */ "Records of individuals",
            /* 714 */ "Directories",
            /* 715 */ "Unable to auto-detect gender using name \"{0}\". Is it male gender?",
            /* 716 */ "Autosave every",
            /* 717 */ "minutes",
            /* 718 */ "Including number of generations",
            /* 719 */ "Hide empty segments",
            /* 720 */ "Descendants Circle",
            /* 721 */ "Choice of portrait",
            /* 722 */ "Relationship Calculator",
            /* 723 */ "{0} is {1} of {2}",
            /* 724 */ "Today is birthday of {0}",
            /* 725 */ "Tomorrow is birthday of {0}",
            /* 726 */ "Blood type",
            /* 727 */ "Hair color",
            /* 728 */ "Eyes color",
            /* 729 */ "mtDNA haplogroup",
            /* 730 */ "Y-DNA haplogroup",
            /* 731 */ "Record is locked by editor",
            /* 732 */ "Maiden surname",
            /* 733 */ "Married surname",
            /* 734 */ "Additional names",
            /* 735 */ "Extended women's surnames",
            /* 736 */ "Format \"Maiden (Married)\"",
            /* 737 */ "Format \"Married (Maiden)\"",
            /* 738 */ "Format \"Maiden\"",
            /* 739 */ "Format \"Married\"",
            /* 740 */ "H",
            /* 741 */ "W",
            /* 742 */ "Geocoder",
            /* 743 */ "Add father",
            /* 744 */ "Add mother",
            /* 745 */ "Show default portraits",
            /* 746 */ "A media file is added from the removable media. Continue?",
            /* 747 */ "Warn when adding media files from removable media",
            /* 748 */ "Load recently opened files at startup",
            /* 749 */ "Today is holiday \"{0}\"",
            /* 750 */ "Tomorrow is holiday \"{0}\"",
            /* 751 */ "{1} days remain before the holiday \"{0}\"",
            /* 752 */ "Holidays",
            /* 753 */ "Use embedded MediaPlayer",
            /* 754 */ "Allow direct references to media files",
            /* 755 */ "Copying file",
            /* 756 */ "Actions",
            /* 757 */ "Select and copy",
            /* 758 */ "№",
            /* 759 */ "Reports",
            /* 760 */ "Inverted tree",
            /* 761 */ "Dates of marriages",
            /* 762 */ "Automatically check for updates",
            /* 763 */ "Arc text",
            /* 764 */ "Album of Trees",
            /* 765 */ "Show places",
            /* 766 */ "Hide unknown spouses",
            /* 767 */ "Spacings",
            /* 768 */ "Margins",
            /* 769 */ "Branch distance",
            /* 770 */ "Generation distance",
            /* 771 */ "Spouse distance",
            /* 772 */ "Image size: {0} x {1} px",
            /* 773 */ "A data loop was detected: {0}",
            /* 774 */ "Father is listed as a child",
            /* 775 */ "Mother is listed as a child",
            /* 776 */ "There are duplicate children in the family",
            /* 777 */ "Select color",
            /* 778 */ "Autosort children",
            /* 779 */ "Autosort spouses",
            /* 780 */ "Check tree size allowed",
            /* 781 */ "Adopted",
            /* 782 */ "Birth",
            /* 783 */ "Foster",
            /* 784 */ "Detect Charset on load",
            /* 785 */ "Linkage type",
            /* 786 */ "Was born",
            /* 787 */ "Was born",
            /* 788 */ "GedML files (*.xml)|*.xml",
            /* 789 */ "Child detected without parents",
            /* 790 */ "Family record detected without family",
            /* 791 */ "Are you sure you want to remove multimedia file?",
            /* 792 */ "Storage not found",
            /* 793 */ "File \"{0}\" not found",
            /* 794 */ "Allow relative references to media files",
            /* 795 */ "Default media storage type",
            /* 796 */ "Allow delete media files from storage and archive",
            /* 797 */ "Allow delete media files by direct and relative references",
            /* 798 */ "Delete media files without confirm",
            /* 799 */ "Media record without files",
            /* 800 */ "Archive not found",

            /* 801 */ "RI:GeorgeKnight",
            /* 802 */ "USSR:WWII:Combatant",
            /* 803 */ "USSR:WWII:Killed in battle",
            /* 804 */ "USSR:WWII:Worker in rear",
            /* 805 */ "USSR:Repressed",
            /* 806 */ "Religion:Islam",
            /* 807 */ "Religion:Catholicism",
            /* 808 */ "Religion:Orthodoxy",
            /* 809 */ "Religion:The Old Believers",

            /* 810 */ "Relative link to file",
            /* 811 */ "Maximum number of backup revisions",
            /* 812 */ "First capital letter in names",
            /* 813 */ "Default depth",
            /* 814 */ "The dialog contains unsaved changes. Continue and save?",
            /* 815 */ "Warn for closing dialog with unsaved changes",
            /* 816 */ "Dotted lines of adopted children",
            /* 817 */ "Go to person record",
            /* 818 */ "Web address",
            /* 819 */ "Separate dates and places lines",
            /* 820 */ "Details",
            /* 821 */ "Copy XRef to clipboard",
            /* 822 */ "Bold font of names",

            /* 823 */ "Baptism",
            /* 824 */ "Bar mitzvah",
            /* 825 */ "Bat mitzvah",
            /* 826 */ "Blessing",
            /* 827 */ "Adult christening",
            /* 828 */ "Confirmation",
            /* 829 */ "First communion",
            /* 830 */ "Ordination",
            /* 831 */ "Restriction geo search by country",
            /* 832 */ "Separate depth",
            /* 833 */ "Ancestors",
            /* 834 */ "Matches not found",
            /* 835 */ "Short kinship form",
            /* 836 */ "Surname first in order",
            /* 837 */ "Borders",
            /* 838 */ "You've got version {0} of GEDKeeper. Would you like to update to the latest version {1}?",
            /* 839 */ "Providers",
            /* 840 */ "Coordinates",
            /* 841 */ "Load places",
            /* 842 */ "Only locality",
            /* 843 */ "Go to primary branch",
            /* 844 */ "Minimizing width",
            /* 845 */ "{0}. Continue?",
            /* 846 */ "Show age",
            /* 847 */ "Surname in capitals",
            /* 848 */ "|SVG files (*.svg)|*.svg",
            /* 849 */ "Certainty assessment algorithm",
            /* 850 */ "Localized calendar signatures",
            /* 851 */ "G|J|H|FR|R|I|?",
            /* 852 */ "Copy",
            /* 853 */ "Cut",
            /* 854 */ "Paste",
            /* 855 */ "Person `{0}` has a half link of spouse to family `{1}`",
            /* 856 */ "Person `{0}` has a half link of child to family `{1}`",
            /* 857 */ "Family `{0}` has a half link of husband to person `{1}`",
            /* 858 */ "Family `{0}` has a half link of wife to person `{1}`",
            /* 859 */ "Family `{0}` has a half link of child to parents family `{1}`",
            /* 860 */ "Family `{0}` has garbled spouses",
            /* 861 */ "USSR:CPSU member",
            /* 862 */ "Attention: when merging archive records, the name and address are not transferred! Proceed?",
            /* 863 */ "Use extra controls",
            /* 864 */ "Several families of parents `{0}`",
            /* 865 */ "Specials",
            /* 866 */ "Use inline images in SVG",
            /* 867 */ "Use extended notes",
            /* 868 */ "Keep rich names",
            /* 869 */ "Chart windows show mode",
            /* 870 */ "Extended tree",
            /* 871 */ "Fan chart (only ancestors)",
            /* 872 */ "Open in new window",
            /* 873 */ "Unknown place of person",
            /* 874 */ "Check person places",
            /* 875 */ "Highlight inaccessible files",
            /* 876 */ "The difference between spouses is abnormally high `{0}`",
            /* 877 */ "The difference between siblings is abnormally high `{0}`",

            /* 878 */ "Find and Replace",
            /* 879 */ "Find",
            /* 880 */ "Replace with",
            /* 881 */ "Match case",
            /* 882 */ "Match wildcards",
            /* 883 */ "Whole word",
            /* 884 */ "Replace",
            /* 885 */ "Replace all",
            /* 886 */ "Property",

            /* 887 */ "Themes",
            /* 888 */ "Tree note",
            /* 889 */ "Show special notes",
            /* 890 */ "No goal record specified",
            /* 891 */ "Invalid file name",
            /* 892 */ "Search and filter by all names",
            /* 893 */ "Data Quality",
            /* 894 */ "Fragment {0}, size {1}, quality {2}",
            /* 895 */ "Refresh",
            /* 896 */ "Reset filter",
            /* 897 */ "Shorten date ranges",
            /* 898 */ "Press Enter to save the filter",

            /* 899 */ "Today is jubilee of {0}",
            /* 900 */ "Tomorrow is jubilee of {0}",
            /* 901 */ "{1} days remain before the jubilee of {0}",
            /* 902 */ "Source year",
            /* 903 */ "Age at year",
            /* 904 */ "Keep overall size of info panels",
            /* 905 */ "Identifiers (XRef)",

            /* 906 */ "father's wife",
            /* 907 */ "mother's husband",
            /* 908 */ "Swap",
            /* 909 */ "Warn when overwriting files",
            /* 910 */ "Same cards width",

            /* 911 */ "uncle",
            /* 912 */ "aunt",
            /* 913 */ "Hide spouses of descendants",

            /* 914 */ "blood",
            /* 915 */ "uterine",
            /* 916 */ "adoptive",
            /* 917 */ "adopted",
            /* 918 */ "common-law",

            /* 919 */ "<?>",
            /* 920 */ "<?>",

            /* 921 */ "-",
            /* 922 */ "first",
            /* 923 */ "second",
            /* 924 */ "third",
            /* 925 */ "fourth",
            /* 926 */ "fifth",
            /* 927 */ "sixth",
            /* 928 */ "seventh",
            /* 929 */ "eighth",
            /* 930 */ "ninth",

            /* 931 */ "Extended definition of kinship",
            /* 932 */ "Use surnames in person selection filter",
            /* 933 */ "Use dates of birth in person selection filter",
            /* 934 */ "Fact value is empty or invalid",
            /* 935 */ "Portrait",
            /* 936 */ "Census analysis",
            /* 937 */ "The person can be found in the census `{0}`",
            /* 938 */ "History",
            /* 939 */ "The periods overlap. This will cause errors when searching for a place name by date.",
            /* 940 */ "Extended locations",
            /* 941 */ "Photos batch adding",
            /* 942 */ "Added {0} photos from {1}.",
            /* 943 */ "Top level links",
            /* 944 */ "Remove top level link?",
            /* 945 */ "Help is not available for this language. An English help will be shown.",
            /* 946 */ "Address (st. & h.n.)",

            /* 947 */ "Default",
            /* 948 */ "Maximize",
            /* 949 */ "Left half",
            /* 950 */ "Right half",

            /* 951 */ "RI:Recruit",
            /* 952 */ "Reverse order of places",
            /* 953 */ "Abbreviated location names",
            /* 954 */ "Dotted lines of common law spouses",
            /* 955 */ "Show number of substructures instead of check marks",
            /* 956 */ "Clean images cache",
            /* 957 */ "Highlight the lines of the selection",
            /* 958 */ "Track matching sources",
            /* 959 */ "Note without links",
            /* 960 */ "Source without links",
            /* 961 */ "Check links",

            /* 962 */ "Event types",
            /* 963 */ "Count",
            /* 964 */ "Enabled",
            /* 965 */ "Tag",
            /* 966 */ "Description",
            /* 967 */ "For custom events and facts, the type must be entered",
            /* 968 */ "Event Definition",
            /* 969 */ "Full name on one line",
            /* 970 */ "Match pattern method",

            /* 971 */ "Single",
            /* 972 */ "Double",
            /* 973 */ "Triple",
            /* 974 */ "Sunken 3D",
            /* 975 */ "Raised 3D",
            /* 976 */ "Single Square Cuts",
            /* 977 */ "Double Square Cuts",
            /* 978 */ "Single Round Cuts",
            /* 979 */ "Double Round Cuts",
            /* 980 */ "Single Bevels",
            /* 981 */ "Double Bevels",
            /* 982 */ "Cross Corners",

            /* 983 */ "Select list",
            /* 984 */ "Links to subordinate locations",
            /* 985 */ "Location Expert",
            /* 986 */ "Event dates",
            /* 987 */ "Add",
            /* 988 */ "Entry",
            /* 989 */ "Include source pages",
            /* 990 */ "Navigation",
            /* 991 */ "Include portraits",
            /* 992 */ "Partial view",
            /* 993 */ "Call number",
            /* 994 */ "Call numbers",
            /* 995 */ "Are you sure you want to remove call number \"{0}\"?",
            /* 996 */ "Repository is not specified",
            /* 997 */ "Age of parents",
            /* 998 */ "Simple form of single surnames",
            /* 999 */ "Map of places",
            /* 1000 */ "Map of persons",
            /* 1001 */ "Search in geocoders for places without coordinates (maps)",
            /* 1002 */ "Locations and Maps",
            /* 1003 */ "Text effect",
            /* 1004 */ "Simple",
            /* 1005 */ "Sunken",
            /* 1006 */ "Raised",
            /* 1007 */ "Glow",
            /* 1008 */ "Padding of text",
            /* 1009 */ "Date designations",
            /* 1010 */ "Mourning edges",
            /* 1011 */ "Use additional dates",
            /* 1012 */ "Cursor coordinates",
            /* 1013 */ "contains mask",
            /* 1014 */ "not contains mask",
            /* 1015 */ "Move files",
            /* 1016 */ "Invalid link: identical records!",
            /* 1017 */ "Display full file name in window title",
            /* 1018 */ "The maximum size allowed for a GEDCOM note has been exceeded!",
        };

        private static readonly LangManager fLangMan = new LangManager();

        public static string LS(LSID lsid)
        {
            return fLangMan.LS(lsid);
        }

        public static string LS(LSID lsid, params object[] args)
        {
            return string.Format(fLangMan.LS(lsid), args);
        }

        public static string LSS(LSID lsid, int selector)
        {
            return SysUtils.GetWordForm(fLangMan.LS(lsid), selector);
        }

        public static void DefInit()
        {
            fLangMan.DefInit(LSDefList);
        }

        public static bool LoadFromFile(string fileName, Assembly resAssembly)
        {
            return fLangMan.LoadFromFile(fileName, resAssembly);
        }

        public static void SaveDefaultLanguage()
        {
            StreamWriter lf = new StreamWriter(GKUtils.GetLangsPath() + "english.sample2", false, Encoding.UTF8);
            try {
                lf.WriteLine(";" + LS_DEF_CODE.ToString() + "," + LS_DEF_SIGN + "," + LS_DEF_NAME);
                for (LSID i = LSID.First; i <= LSID.Last; i++) {
                    string ls = LSDefList[(int)i - 1];
                    if (!string.IsNullOrEmpty(ls)) {
                        lf.WriteLine(ConvertHelper.AdjustNumber((int)i, 3) + "=" + ls);
                    }
                }
            } finally {
                lf.Close();
            }
        }
    }

    public class LangManager : ILangMan
    {
        private readonly Dictionary<int, string> fList;

        public LangManager()
        {
            fList = new Dictionary<int, string>();
        }

        public string LS(Enum lsid)
        {
            int idx = ((IConvertible)lsid).ToInt32(null);
            string res;
            return fList.TryGetValue(idx, out res) ? res : "?";
        }

        public bool LoadFromFile(string fileName, Assembly resAssembly)
        {
            bool result = false;

            if (resAssembly == null && !File.Exists(fileName)) return result;

            using (var inputStream = (resAssembly == null) ? new FileStream(fileName, FileMode.Open, FileAccess.Read) : resAssembly.GetManifestResourceStream(fileName)) {
                fList.Clear();

                using (StreamReader lngFile = new StreamReader(inputStream, Encoding.UTF8)) {
                    string st = lngFile.ReadLine();
                    if (!string.IsNullOrEmpty(st) && st[0] == ';') {
                        st = st.Remove(0, 1);
                        string[] lngParams = st.Split(',');
                        if (lngParams.Length < 3)
                            throw new GKException("Header is incorrect");
                    }

                    while (lngFile.Peek() != -1) {
                        st = lngFile.ReadLine();
                        if (string.IsNullOrEmpty(st)) continue;

                        // allowed empty and comment strings
                        int commentPos = st.IndexOf(";");
                        if (commentPos >= 0) st = st.Substring(0, commentPos);
                        st = st.Trim();
                        if (string.IsNullOrEmpty(st)) continue;

                        string[] parts = st.Split('=');
                        if (parts.Length == 2) {
                            int i = int.Parse(parts[0]);
                            fList.Add(i, parts[1]);
                        }
                    }
                    result = true;
                }
            }

            return result;
        }

        internal void DefInit(string[] source)
        {
            fList.Clear();

            for (LSID id = LSID.First; id <= LSID.Last; id++) {
                int idx = (int)id;
                fList.Add(idx, source[idx - 1]);
            }
        }
    }
}
