//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class GKResources {
	
	private static global::System.Resources.ResourceManager resourceMan;
	
	private static global::System.Globalization.CultureInfo resourceCulture;
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	internal GKResources() {
	}
	
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static global::System.Resources.ResourceManager ResourceManager {
		get {
			if (object.ReferenceEquals(resourceMan, null)) {
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKResources", typeof(GKResources).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	internal static global::System.Globalization.CultureInfo Culture {
		get {
			return resourceCulture;
		}
		set {
			resourceCulture = value;
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
	/// </summary>
	internal static System.Drawing.Icon GK2_Icon {
		get {
			object obj = ResourceManager.GetObject("GK2_Icon", resourceCulture);
			return ((System.Drawing.Icon)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iBtnAccept {
		get {
			object obj = ResourceManager.GetObject("iBtnAccept", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iBtnCancel {
		get {
			object obj = ResourceManager.GetObject("iBtnCancel", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iChartControls {
		get {
			object obj = ResourceManager.GetObject("iChartControls", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iChartControls_old {
		get {
			object obj = ResourceManager.GetObject("iChartControls_old", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iCopy {
		get {
			object obj = ResourceManager.GetObject("iCopy", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iDown {
		get {
			object obj = ResourceManager.GetObject("iDown", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iExcel {
		get {
			object obj = ResourceManager.GetObject("iExcel", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iExpand {
		get {
			object obj = ResourceManager.GetObject("iExpand", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iLeft1 {
		get {
			object obj = ResourceManager.GetObject("iLeft1", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Windows.Forms.ImageListStreamer.
	/// </summary>
	internal static System.Windows.Forms.ImageListStreamer ImageList_Buttons_ImageStream {
		get {
			object obj = ResourceManager.GetObject("ImageList_Buttons.ImageStream", resourceCulture);
			return ((System.Windows.Forms.ImageListStreamer)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRecDelete {
		get {
			object obj = ResourceManager.GetObject("iRecDelete", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRecEdit {
		get {
			object obj = ResourceManager.GetObject("iRecEdit", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRecNew {
		get {
			object obj = ResourceManager.GetObject("iRecNew", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRGShieldMax {
		get {
			object obj = ResourceManager.GetObject("iRGShieldMax", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRGShieldMid {
		get {
			object obj = ResourceManager.GetObject("iRGShieldMid", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRGShieldNone {
		get {
			object obj = ResourceManager.GetObject("iRGShieldNone", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iRight1 {
		get {
			object obj = ResourceManager.GetObject("iRight1", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iSizeToFit {
		get {
			object obj = ResourceManager.GetObject("iSizeToFit", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iSizeToFit2 {
		get {
			object obj = ResourceManager.GetObject("iSizeToFit2", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGBarbedWire {
		get {
			object obj = ResourceManager.GetObject("iTGBarbedWire", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGGeorgeCross {
		get {
			object obj = ResourceManager.GetObject("iTGGeorgeCross", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGIslamSym {
		get {
			object obj = ResourceManager.GetObject("iTGIslamSym", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGLatinCross {
		get {
			object obj = ResourceManager.GetObject("iTGLatinCross", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGOldRitualCross {
		get {
			object obj = ResourceManager.GetObject("iTGOldRitualCross", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGOrthodoxCross {
		get {
			object obj = ResourceManager.GetObject("iTGOrthodoxCross", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGSoldier {
		get {
			object obj = ResourceManager.GetObject("iTGSoldier", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGSoldierFall {
		get {
			object obj = ResourceManager.GetObject("iTGSoldierFall", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTGVeteranRear {
		get {
			object obj = ResourceManager.GetObject("iTGVeteranRear", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iTipsLight {
		get {
			object obj = ResourceManager.GetObject("iTipsLight", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iToMan {
		get {
			object obj = ResourceManager.GetObject("iToMan", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iUp {
		get {
			object obj = ResourceManager.GetObject("iUp", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iZoomIn {
		get {
			object obj = ResourceManager.GetObject("iZoomIn", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iZoomIn2 {
		get {
			object obj = ResourceManager.GetObject("iZoomIn2", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iZoomOut {
		get {
			object obj = ResourceManager.GetObject("iZoomOut", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
	
	/// <summary>
	///   Looks up a localized resource of type System.Drawing.Bitmap.
	/// </summary>
	internal static System.Drawing.Bitmap iZoomOut2 {
		get {
			object obj = ResourceManager.GetObject("iZoomOut2", resourceCulture);
			return ((System.Drawing.Bitmap)(obj));
		}
	}
}
