using System;

namespace GKCore
{
	public enum LSID : ushort
	{
		LSID_None,
		LSID_First,
		LSID_MIFile = 1,
		LSID_MIEdit,
		LSID_MIPedigree,
		LSID_MIService,
		LSID_MIWindow,
		LSID_MIHelp,
		LSID_MIFileNew,
		LSID_MIFileLoad,
		LSID_MIMRUFiles,
		LSID_MIFileSave,
		LSID_MIFileClose,
		LSID_MIFileProperties,
		LSID_MIExport,
		LSID_MIExportToWeb,
		LSID_MIExportToExcelApp,
		LSID_MIExportToExcelFile,
		LSID_MIExit,
		LSID_MIUndo,
		LSID_MIRedo,
		LSID_MIRecordAdd,
		LSID_MIRecordEdit,
		LSID_MIRecordDelete,
		LSID_MIStreamInput,
		LSID_MITreeAncestors,
		LSID_MITreeDescendants,
		LSID_MITreeBoth,
		LSID_MIPedigree_dAboville,
		LSID_MIPedigree_Konovalov,
		LSID_MIMap,
		LSID_MIStats,
		LSID_MICalc,
		LSID_MINamesBook,
		LSID_MICalendar,
		LSID_MITimeLine,
		LSID_MIOrganizer,
		LSID_MIScripts,
		LSID_MITreeTools = 38,
		LSID_MIFilter,
		LSID_MIOptions,
		LSID_MIWinCascade,
		LSID_MIWinHTile,
		LSID_MIWinVTile,
		LSID_MIWinMinimize,
		LSID_MIWinArrange,
		LSID_MIGenResources,
		LSID_MIKinshipTerms,
		LSID_MIFAQ,
		LSID_MIContext,
		LSID_MIAbout,
		LSID_SBRecords,
		LSID_SBFiltered,
		LSID_RPIndividuals,
		LSID_RPFamilies,
		LSID_RPNotes,
		LSID_RPMultimedia,
		LSID_RPSources,
		LSID_RPRepositories,
		LSID_RPGroups,
		LSID_RPResearches,
		LSID_RPTasks,
		LSID_RPCommunications,
		LSID_RPLocations,
		LSID_UnkFemale,
		LSID_UnkMale,
		LSID_SexN,
		LSID_SexM,
		LSID_SexF,
		LSID_SexU,
		LSID_FileSaveQuery,
		LSID_ParentsQuery,
		LSID_PersonDeleteQuery,
		LSID_FamilyDeleteQuery,
		LSID_NoteDeleteQuery,
		LSID_SourceDeleteQuery,
		LSID_MediaDeleteQuery,
		LSID_RepositoryDeleteQuery,
		LSID_GroupDeleteQuery,
		LSID_ResearchDeleteQuery,
		LSID_TaskDeleteQuery,
		LSID_CommunicationDeleteQuery,
		LSID_LocationDeleteQuery,
		LSID_Address,
		LSID_Events,
		LSID_Surname,
		LSID_Name,
		LSID_Patronymic,
		LSID_Sex,
		LSID_Nickname,
		LSID_SurnamePrefix,
		LSID_NamePrefix,
		LSID_NameSuffix,
		LSID_Patriarch,
		LSID_Bookmark,
		LSID_Association,
		LSID_Relation,
		LSID_Person,
		LSID_DlgAccept,
		LSID_DlgCancel,
		LSID_DlgClose,
		LSID_DlgSelect,
		LSID_DlgAppend,
		LSID_WinPersonNew,
		LSID_WinPersonEdit,
		LSID_WinCheckSex,
		LSID_WinRecordSelect,
		LSID_WinSourceCitEdit,
		LSID_WinUserRefEdit,
		LSID_Note,
		LSID_Source,
		LSID_Page,
		LSID_Certainty,
		LSID_Reference,
		LSID_Type,
		LSID_Family,
		LSID_Husband,
		LSID_Wife,
		LSID_Status,
		LSID_Childs,
		LSID_DetachHusbandQuery,
		LSID_DetachWifeQuery,
		LSID_DetachChildQuery,
		LSID_BirthDate,
		LSID_DeathDate,
		LSID_Restriction,
		LSID_Title,
		LSID_Members,
		LSID_WinGroupEdit,
		LSID_DetachMemberQuery,
		LSID_TimeScale,
		LSID_CurrentYear,
		LSID_Telephone,
		LSID_Mail,
		LSID_WebSite,
		LSID_Repository,
		LSID_Progress,
		LSID_TimePassed,
		LSID_TimeRemain,
		LSID_TimeTotal,
		LSID_Date,
		LSID_Text,
		LSID_ShortTitle,
		LSID_Author,
		LSID_Publication,
		LSID_Common,
		LSID_DetachRepositoryQuery,
		LSID_StoreType,
		LSID_File,
		LSID_View,
		LSID_AdvancedWarning,
		LSID_Father,
		LSID_Mother,
		LSID_Parents,
		LSID_Spouses,
		LSID_Associations,
		LSID_UserRefs,
		LSID_Cal_Gregorian,
		LSID_Cal_Julian,
		LSID_Cal_Hebrew,
		LSID_Cal_Islamic,
		LSID_Cal_Persian,
		LSID_Cal_Indian,
		LSID_Cal_Bahai,
		LSID_Cal_French,
		LSID_Cal_Roman,
		LSID_Unknown,
		LSID_CopyResultToClipboard,
		LSID_Advanced,
		LSID_AdvancedSupport,
		LSID_ExtName,
		LSID_Location,
		LSID_Latitude,
		LSID_Longitude,
		LSID_Show,
		LSID_SearchCoords,
		LSID_Search,
		LSID_SelectCoords,
		LSID_SelectName,
		LSID_Priority,
		LSID_Percent,
		LSID_StartDate,
		LSID_StopDate,
		LSID_Goal,
		LSID_Theme,
		LSID_Corresponder,
		LSID_Group,
		LSID_DetachTaskQuery,
		LSID_DetachCommunicationQuery,
		LSID_DetachGroupQuery,
		LSID_WinResearchEdit,
		LSID_WinTaskEdit,
		LSID_WinCommunicationEdit,
		LSID_Error,
		LSID_LuaStartFailed,
		LSID_DateFormatInvalid,
		LSID_AdCountry,
		LSID_AdState,
		LSID_AdCity,
		LSID_AdPostalCode,
		LSID_Telephones,
		LSID_EMails,
		LSID_WebSites,
		LSID_Value,
		LSID_Event,
		LSID_Place,
		LSID_Cause,
		LSID_Agency,
		LSID_PatFemale,
		LSID_PatMale,
		LSID_NotSelectedPerson,
		LSID_IsNotDefinedSex,
		LSID_IsNotFamilies,
		LSID_AncestorsNumberIsInvalid,
		LSID_DescendantsNumberIsInvalid,
		LSID_GenerationsVisible,
		LSID_Unlimited,
		LSID_Spouse,
		LSID_MarriageDate,
		LSID_DetachFatherQuery,
		LSID_DetachMotherQuery,
		LSID_DetachSpouseQuery,
		LSID_DetachParentsQuery,
		LSID_TM_Both,
		LSID_TM_Ancestors,
		LSID_TM_Descendants,
		LSID_TM_TraceRoot,
		LSID_DoEdit,
		LSID_FamilyAdd,
		LSID_SpouseAdd,
		LSID_SonAdd,
		LSID_DaughterAdd,
		LSID_DoDelete,
		LSID_RebuildTree,
		LSID_RebuildKinships,
		LSID_Links,
		LSID_PlaceAndAttribute,
		LSID_LMarriage,
		LSID_LFamily,
		LSID_Namesakes,
		LSID_RemoveEventQuery,
		LSID_DetachNoteQuery,
		LSID_DetachMultimediaQuery,
		LSID_DetachSourceQuery,
		LSID_RemoveAssociationQuery,
		LSID_RemoveUserRefQuery,
		LSID_LoadGedComFailed,
		LSID_CheckGedComFailed,
		LSID_BirthDays,
		LSID_DaysRemained,
		LSID_Interface,
		LSID_Trees,
		LSID_Pedigrees,
		LSID_SaveCoding,
		LSID_WorkMode,
		LSID_Simple,
		LSID_Expert,
		LSID_Internet,
		LSID_ProxyUse,
		LSID_ProxyServer,
		LSID_ProxyPort,
		LSID_ProxyLogin,
		LSID_ProxyPassword,
		LSID_Tips,
		LSID_StartupTips,
		LSID_Language,
		LSID_ListsAll,
		LSID_ListPersons,
		LSID_NamesFormat,
		LSID_NF1,
		LSID_NF2,
		LSID_NF3,
		LSID_DateFormat,
		LSID_PlacesWithAddress,
		LSID_HighlightUnparented,
		LSID_HighlightUnmarried,
		LSID_DefList,
		LSID_ViewTree,
		LSID_DiffLines,
		LSID_OnlyYears,
		LSID_Kinship,
		LSID_SignsVisible,
		LSID_TreeDecorative,
		LSID_PortraitsVisible,
		LSID_ChildlessExclude,
		LSID_Decor,
		LSID_Man,
		LSID_Woman,
		LSID_UnkSex,
		LSID_UnHusband,
		LSID_UnWife,
		LSID_Font,
		LSID_PedigreeGen,
		LSID_IncludeAttributes,
		LSID_IncludeNotes,
		LSID_IncludeSources,
		LSID_PedigreeFormat,
		LSID_PF1,
		LSID_PF2,
		LSID_RecordGoto,
		LSID_RecordMoveUp,
		LSID_RecordMoveDown,
		LSID_FullName,
		LSID_BirthPlace,
		LSID_DeathPlace,
		LSID_Residence,
		LSID_Age,
		LSID_LifeExpectancy,
		LSID_DaysForBirth,
		LSID_Religion,
		LSID_Nationality,
		LSID_Education,
		LSID_Occupation,
		LSID_Caste,
		LSID_Mili,
		LSID_MiliInd,
		LSID_MiliDis,
		LSID_MiliRank,
		LSID_Changed,
		LSID_MarrRegistered,
		LSID_MarrNotRegistered,
		LSID_MarrDivorced,
		LSID_Birth,
		LSID_Adoption,
		LSID_Christening,
		LSID_Graduation,
		LSID_Retirement,
		LSID_Naturalization,
		LSID_Emigration,
		LSID_Immigration,
		LSID_Census,
		LSID_LastWill,
		LSID_ProbateOfWill,
		LSID_Death,
		LSID_Burial,
		LSID_Cremation,
		LSID_Fact,
		LSID_PhysicalDesc,
		LSID_NationalIDNumber,
		LSID_SocialSecurityNumber,
		LSID_ChildsCount,
		LSID_MarriagesCount,
		LSID_Property,
		LSID_NobilityTitle,
		LSID_Travel,
		LSID_Hobby,
		LSID_Award,
		LSID_RK_Unk,
		LSID_RK_Father,
		LSID_RK_Mother,
		LSID_RK_Husband,
		LSID_RK_Wife,
		LSID_RK_Son,
		LSID_RK_Daughter,
		LSID_RK_Grandfather,
		LSID_RK_Grandmother,
		LSID_RK_Grandson,
		LSID_RK_Granddaughter,
		LSID_RK_Brother,
		LSID_RK_Sister,
		LSID_RK_SonInLaw,
		LSID_RK_DaughterInLaw,
		LSID_RK_HusbandFather,
		LSID_RK_HusbandMother,
		LSID_RK_WifeFather,
		LSID_RK_WifeMother,
		LSID_RK_Uncle,
		LSID_RK_Aunt,
		LSID_RK_Nephew,
		LSID_RK_Niece,
		LSID_RK_CousinM,
		LSID_RK_CousinF,
		LSID_RK_01,
		LSID_RK_02,
		LSID_RK_03,
		LSID_RK_04,
		LSID_RK_05,
		LSID_RK_06,
		LSID_RK_07,
		LSID_RK_08,
		LSID_RK_09,
		LSID_TooMuchWidth,
		LSID_Backward,
		LSID_Forward,
		LSID_Prev,
		LSID_Next,
		LSID_YouKnowWhat,
		LSID_LoadingLocations,
		LSID_NotSelected,
		LSID_MapSelection,
		LSID_MapSelOnAll,
		LSID_MSBirthPlaces,
		LSID_MSDeathPlaces,
		LSID_MSResiPlace,
		LSID_MapSelOnSelected,
		LSID_SaveImage,
		LSID_FormatUnsupported,
		LSID_DataLoadError,
		LSID_ParseError_LineSeq,
		LSID_PersonParsed,
		LSID_Generation,
		LSID_ParseError_AncNotFound,
		LSID_ParseError_DateInvalid,
		LSID_DK_0,
		LSID_DK_1,
		LSID_DK_2,
		LSID_DK_3,
		LSID_DK_4,
		LSID_DK_5,
		LSID_DK_6,
		LSID_DK_7,
		LSID_DK_8,
		LSID_DK_9,
		LSID_FEvt_1,
		LSID_FEvt_2,
		LSID_FEvt_3,
		LSID_FEvt_4,
		LSID_FEvt_5,
		LSID_FEvt_6,
		LSID_FEvt_7,
		LSID_FEvt_8,
		LSID_FEvt_9,
		LSID_STRef,
		LSID_STArc,
		LSID_STStg,
		LSID_MT_01,
		LSID_MT_02,
		LSID_MT_03,
		LSID_MT_04,
		LSID_MT_05,
		LSID_MT_06,
		LSID_MT_07,
		LSID_MT_08,
		LSID_MT_09,
		LSID_MT_10,
		LSID_MT_11,
		LSID_MT_12,
		LSID_MT_13,
		LSID_MT_14,
		LSID_MT_15,
		LSID_Prt_1,
		LSID_Prt_2,
		LSID_Prt_3,
		LSID_Prt_4,
		LSID_Prt_5,
		LSID_RStat_1,
		LSID_RStat_2,
		LSID_RStat_3,
		LSID_RStat_4,
		LSID_RStat_5,
		LSID_RStat_6,
		LSID_Com_1,
		LSID_Com_2,
		LSID_Com_3,
		LSID_Com_4,
		LSID_Com_5,
		LSID_Com_6,
		LSID_CD_1,
		LSID_CD_2,
		LSID_G_1,
		LSID_G_2,
		LSID_G_3,
		LSID_G_4,
		LSID_Cert_1,
		LSID_Cert_2,
		LSID_Cert_3,
		LSID_Cert_4,
		LSID_Research,
		LSID_Task,
		LSID_Communication,
		LSID_IDsCorrect,
		LSID_FormatCheck,
		LSID_IDsCorrectNeed,
		LSID_MainBaseSize,
		LSID_SyncFin,
		LSID_PatSearch,
		LSID_LinksSearch,
		LSID_ArcNotFound,
		LSID_GenDB,
		LSID_GenIndex,
		LSID_SurnamesIndex,
		LSID_NamesIndex,
		LSID_BirthIndex,
		LSID_DeathIndex,
		LSID_CommonStats,
		LSID_ExpPedigree,
		LSID_InputSimple,
		LSID_InputSource,
		LSID_SourceKind,
		LSID_SK_Rev,
		LSID_SK_Met,
		LSID_Year,
		LSID_Settlement,
		LSID_EventDate,
		LSID_EventType,
		LSID_Join,
		LSID_Comment,
		LSID_BranchCut,
		LSID_Not,
		LSID_BCut_Years,
		LSID_BCut_Persons,
		LSID_SrcAll,
		LSID_SrcNot,
		LSID_SrcAny,
		LSID_PLPerson,
		LSID_PLGodparent,
		LSID_Child,
		LSID_NameInvalid,
		LSID_BasePersonInvalid,
		LSID_SourceYearInvalid,
		LSID_ValueInvalid,
		LSID_Operation,
		LSID_ToolOp_1,
		LSID_ToolOp_2,
		LSID_ToolOp_3,
		LSID_ToolOp_4,
		LSID_ToolOp_5,
		LSID_ToolOp_6,
		LSID_ToolOp_7,
		LSID_ToolOp_8,
		LSID_ToolOp_9,
		LSID_SearchMatches,
		LSID_CheckFamiliesConnection,
		LSID_All,
		LSID_OnlyAlive,
		LSID_OnlyDied,
		LSID_AliveBefore,
		LSID_OnlyMans,
		LSID_OnlyWomans,
		LSID_NameMask,
		LSID_PlaceMask,
		LSID_EventMask,
		LSID_OnlyPatriarchs,
		LSID_DateInvalid,
		LSID_People,
		LSID_Years,
		LSID_Decennial,
		LSID_HowBirthes,
		LSID_HowDeads,
		LSID_Living,
		LSID_Deads,
		LSID_AvgAge,
		LSID_AvgLife,
		LSID_AvgChilds,
		LSID_AvgBorn,
		LSID_AvgMarriagesCount,
		LSID_AvgMarriagesAge,
		LSID_AncestorsCount,
		LSID_DescendantsCount,
		LSID_GenerationsCount,
		LSID_BirthYears,
		LSID_BirthYearsDec,
		LSID_DeathYears,
		LSID_DeathYearsDec,
		LSID_DistrChilds,
		LSID_AgeFirstborn,
		LSID_MarriagesAge,
		LSID_DiffSpouses,
		LSID_SelAll,
		LSID_SelFamily,
		LSID_SelAncestors,
		LSID_SelDescendants,
		LSID_RecMerge,
		LSID_RM_Search,
		LSID_RM_Skip,
		LSID_RM_Records,
		LSID_RM_SearchPersons,
		LSID_RM_DirectMatching,
		LSID_RM_IndistinctMatching,
		LSID_RM_OnlyNP,
		LSID_RM_BirthYear,
		LSID_RM_NameAccuracy,
		LSID_RM_YearInaccuracy,
		LSID_Repair,
		LSID_MinGenerations,
		LSID_SetPatFlag,
		LSID_InsertIntoBook,
		LSID_SimilarSurnames,
		LSID_SimilarNames,
		LSID_RecsDeleted,
		LSID_Record,
		LSID_Problem,
		LSID_Solve,
		LSID_PersonLonglived,
		LSID_PersonSexless,
		LSID_LiveYearsInvalid,
		LSID_StrangeSpouse,
		LSID_StrangeParent,
		LSID_Descendants,
		LSID_Generations,
		LSID_LinksCount,
		LSID_PlacesPrepare,
		LSID_PlaceAlreadyInBook,
		LSID_DNAMarkers,

		LSID_Last = LSID_DNAMarkers
	}

	public static class GKL
	{
		public static readonly string[] LSDefList = new string[]
		{
			"Файл", 
			"Правка", 
			"Родословная", 
			"Сервис", 
			"&Окна", 
			"Справка", 
			"Новый", 
			"Открыть...", 
			"Открыть последний", 
			"Сохранить...", 
			"Закрыть", 
			"Свойства файла...", 
			"Экспорт", 
			"Экспорт в Web...", 
			"Экспорт в Excel...", 
			"Экспорт в Excel-файл...", 
			"Выход", 
			"Отменить", 
			"Вернуть", 
			"Добавить запись", 
			"Изменить запись", 
			"Удалить запись", 
			"Поточный ввод", 
			"Древо предков", 
			"Древо потомков", 
			"Древо полное", 
			"Роспись по дАбовиллю", 
			"Роспись по Коновалову", 
			"Карты", 
			"Статистика", 
			"Калькулятор", 
			"Справочник имен", 
			"Календарь", 
			"Линия времени", 
			"Органайзер", 
			"Скрипты...", 
			"Импорт баз данных...", 
			"Инструменты...", 
			"Фильтр",						/* LSID_MIFilter */
			"Настройки", 
			"&Каскад", 
			"&Горизонтальная мозаика", 
			"&Вертикальная мозаика", 
			"&Свернуть все", 
			"&Разместить все", 
			"Ресурсы в Интернете...", 
			"Терминология родства...", 
			"Часто задаваемые вопросы...", 
			"Содержание", 
			"О программе", 
			"Записей", 
			"фильтрованных", 
			"Персоны", 
			"Семьи", 
			"Заметки", 
			"Мультимедиа", 
			"Источники", 
			"Архивы", 
			"Группы", 
			"Исследования", 
			"Задачи", 
			"Коммуникации", 
			"Места", 
			"неизвестная", 
			"неизвестный", 
			"?", 
			"Мужской", 
			"Женский", 
			"Неопределенный", 
			"Файл изменен. Сохранить?", 
			"У заданного родителя найдена семья \"{0}\". \\nВключить в неё ребенка?", 
			"Удалить персональную запись \"{0}\"?", 
			"Удалить семью \"{0}\"?", 
			"Удалить заметку?", 
			"Удалить источник \"{0}\"?", 
			"Удалить мультимедиа \"{0}\"?", 
			"Удалить архив \"{0}\"?", 
			"Удалить группу \"{0}\"?", 
			"Удалить исследование \"{0}\"?", 
			"Удалить задачу \"{0}\"?", 
			"Удалить коммуникацию \"{0}\"?", 
			"Удалить место \"{0}\"?", 
			"Адрес", 
			"Факты", 
			"Фамилия", 
			"Имя", 
			"Отчество", 
			"Пол", 
			"Прозвище", 
			"Префикс фамилии", 
			"Префикс имени", 
			"Суффикс имени", 
			"Патриарх", 
			"Закладка", 
			"Ассоциация", 
			"Отношение", 
			"Персона", 
			"Принять", 
			"Отменить", 
			"Закрыть", 
			"Выбрать", 
			"Добавить", 
			"Новая персональная запись", 
			"Редактирование персональной записи", 
			"Проверка пола", 
			"Выбор записи", 
			"Цитата источника", 
			"Пользовательская сноска", 
			"Заметка", 
			"Источник", 
			"Лист/Страница", 
			"Достоверность", 
			"Сноска/ссылка", 
			"Тип", 
			"Семья", 
			"Муж", 
			"Жена", 
			"Статус", 
			"Дети", 
			"Удалить ссылку на мужа?", 
			"Удалить ссылку на жену?", 
			"Удалить ссылку на ребенка?", 
			"Дата рождения", 
			"Дата смерти", 
			"Ограничение безопасности", 
			"Название", 
			"Участники", 
			"Редактирование группы", 
			"Удалить ссылку на участника группы?", 
			"Шкала времени", 
			"Текущий год", 
			"Телефон", 
			"Эл. почта", 
			"Сайт", 
			"Архив", 
			"Прогресс", 
			"Времени прошло", 
			"Времени осталось", 
			"Времени всего", 
			"Дата", 
			"Текст", 
			"Краткое название", 
			"Автор", 
			"Опубликовано", 
			"Общее", 
			"Удалить ссылку на архив?", 
			"Способ хранения", 
			"Файл", 
			"Просмотр", 
			"Для выбранного типа хранения не включен режим расширения", 
			"Отец", 
			"Мать", 
			"Родители", 
			"Супруги", 
			"Ассоциации", 
			"Сноски/Пометки", 
			"Григорианский", 
			"Юлианский", 
			"Еврейский", 
			"Исламский (Хиджры)", 
			"Иранский", 
			"Индийский", 
			"Бахаи", 
			"Французский", 
			"Римский", 
			"Неизвестно", 
			"Поместить результат в буфер обмена", 
			"Расширение проекта", 
			"Поддержка расширения (архив, хранилище файлов)", 
			"Название архива и папки хранилища", 
			"Местоположение", 
			"Широта", 
			"Долгота", 
			"Показать", 
			"Поиск координат", 
			"Поиск", 
			"Выбрать коорд.", 
			"Выбрать название", 
			"Приоритет", 
			"Процент", 
			"Запущено", 
			"Завершено", 
			"Цель", 
			"Тема", 
			"Корреспондент", 
			"Группа", 
			"Удалить ссылку на задачу?", 
			"Удалить ссылку на корреспонденцию?", 
			"Удалить ссылку на группу?", 
			"Редактирование исследования", 
			"Редактирование задачи", 
			"Редактирование коммуникации", 
			"Ошибка", 
			"Ошибка запуска Lua!", 
			"Некорректный формат даты", 
			"Страна", 
			"Штат/Область", 
			"Город", 
			"Почтовый код", 
			"Телефоны", 
			"Эл. почта", 
			"Веб-страницы", 
			"Значение", 
			"Событие", 
			"Место", 
			"Причина", 
			"Засвидетельствовавший орган", 
			"Женское", 
			"Мужское", 
			"Не выбрана персональная запись", 
			"У данной персоны не задан пол.", 
			"У данной персоны нет семей.", 
			"Расчетное количество предков {0} больше допустимых пределов.", 
			"Расчетное количество потомков {0} больше допустимых пределов.", 
			"Показывать поколений:", 
			"неограниченно", 
			"Cупруг(а)", 
			"Дата брака", 
			"Удалить ссылку на отца?", 
			"Удалить ссылку на мать?", 
			"Удалить ссылку на супруга?", 
			"Удалить персону из семьи родителей?", 
			"Всё", 
			"Только предки", 
			"Только потомки", 
			"Автосмена центра", 
			"Редактировать", 
			"Добавить семью", 
			"Добавить супруга(у)", 
			"Добавить сына", 
			"Добавить дочь", 
			"Удалить", 
			"Перестроить древо", 
			"Перестроить отношения", 
			"Ссылки", 
			"Место/Атрибут", 
			"брак", 
			"семья", 
			"Тёзки", 
			"Удалить факт?", 
			"Удалить ссылку на заметку?", 
			"Удалить ссылку на мультимедиа?", 
			"Удалить ссылку на источник?", 
			"Удалить ассоциацию?", 
			"Удалить пользовательскую сноску?", 
			"Ошибка загрузки файла", 
			"Ошибка проверки формата", 
			"Дни рождения", 
			"До дня рождения \"{0}\" осталось {1} дня(-ей)", 
			"Интерфейс", 
			"Родословные древа", 
			"Росписи", 
			"Кодировка сохранения файлов", 
			"Режим работы", 
			"Простой", 
			"Продвинутый", 
			"Загрузка из Интернета", 
			"Использовать прокси-сервер", 
			"Сервер", 
			"Порт", 
			"Логин", 
			"Пароль", 
			"Подсказки", 
			"Показывать при старте", 
			"Язык", 
			"Все списки", 
			"Список персон", 
			"Формат имен в списках", 
			"Фамилия_Имя_Отчество", 
			"Фамилия; Имя_Отчество", 
			"Фамилия; Имя; Отчество", 
			"Формат даты в списках", 
			"Включать адрес в строки мест", 
			"Подсвечивать персоны без родителей", 
			"Подсвечивать персоны без семьи", 
			"Значения по умолчанию", 
			"Отображение персон в древе", 
			"Разные строки (имя и отчество)", 
			"Только годы", 
			"Степень родства", 
			"Дополнительные символы", 
			"Декоративное оформление", 
			"Отображать портреты", 
			"Исключить умерших в детстве", 
			"Оформление", 
			"Мужчина", 
			"Женщина", 
			"Неизвестный пол", 
			"Разведенный супруг", 
			"Разведенная супруга", 
			"Шрифт", 
			"Генерация росписей", 
			"Включая атрибуты персон", 
			"Включая заметки", 
			"Включая источники", 
			"Формат", 
			"Избыточный", 
			"Традиционный", 
			"Перейти на запись", 
			"Поместить выше", 
			"Поместить ниже", 
			"Полное имя", 
			"Место рождения", 
			"Место смерти", 
			"Местожительство", 
			"Возраст", 
			"Продолжительность жизни", 
			"Дней до ДР", 
			"Вероисповедание", 
			"Национальность", 
			"Образование", 
			"Профессия", 
			"Социальное положение", 
			"Военная служба", 
			"Призван в ВС", 
			"Уволен из ВС", 
			"Звание в ВС", 
			"Изменено", 
			"Брак зарегистрирован", 
			"Брак не зарегистрирован", 
			"Разведены", 
			"Рождение", 
			"Усыновление", 
			"Крещение", 
			"Получение ученой степени", 
			"Уход на пенсию", 
			"Натурализация", 
			"Эмиграция", 
			"Иммиграция", 
			"Перепись", 
			"Завещание", 
			"Утверждение завещания", 
			"Смерть", 
			"Похороны", 
			"Кремация", 
			"Факт", 
			"Физическое описание", 
			"Идентификационный номер", 
			"Код социального страхования", 
			"Количество детей", 
			"Количество браков", 
			"Собственность", 
			"Титул", 
			"Путешествие", 
			"Хобби", 
			"Награда", 
			"?", 
			"отец", 
			"мать", 
			"муж", 
			"жена", 
			"сын", 
			"дочь", 
			"дед", 
			"бабушка", 
			"внук", 
			"внучка", 
			"брат", 
			"сестра", 
			"зять", 
			"невестка", 
			"свекор", 
			"свекровь", 
			"тесть", 
			"теща", 
			"дядя", 
			"тетя", 
			"племянник", 
			"племянница", 
			"кузен", 
			"кузина", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"<reserved>", 
			"Ширина изображения более 65 тыс. точек. Сохранить невозможно", 
			"Назад", 
			"Вперед", 
			"<reserved>", 
			"Далее", 
			"Вы знаете что...", 
			"Загрузка и поиск мест", 
			"( не выбран )", 
			"Выборка", 
			"По всем людям", 
			"Места рождения", 
			"Места смерти", 
			"Места проживания", 
			"Только по выбранному", 
			"Сохранить снимок...", 
			"Формат не поддерживается", 
			"Ошибка загрузки данных.", 
			"Ошибка разбора: номера записей содержат пропуск.", 
			"Распознана персональная запись", 
			"Поколение", 
			"Ошибка разбора: в списке не обнаружен предок с номером", 
			"Ошибка разбора: дата", 
			"Точно", 
			"Ранее", 
			"Позднее", 
			"Между", 
			"Период до", 
			"Период после", 
			"Период между", 
			"Около", 
			"По расчету", 
			"По оценке", 
			"Помолвка", 
			"Бракосочетание", 
			"Публичное объявление о бракосочетании", 
			"Заключение брачного контракта", 
			"Получение разрешения на брак", 
			"Заключение брачного соглашения", 
			"Аннулирование брака", 
			"Подача заявления о разводе", 
			"Развод", 
			"Ссылка на файл", 
			"Размещение в архиве", 
			"Размещение в хранилище", 
			"-", 
			"Звукозапись", 
			"Книга", 
			"Карточка", 
			"Электронный", 
			"Микрофиша", 
			"Фильм", 
			"Журнал", 
			"Рукопись", 
			"Карта", 
			"Газета", 
			"Фотография", 
			"Надгробие", 
			"Видео", 
			"- Другой -", 
			"Не задан", 
			"Низкий", 
			"Нормальный", 
			"Высокий", 
			"Срочный", 
			"Определено", 
			"Выполняется", 
			"Задержано", 
			"Осложнения", 
			"Завершено", 
			"Отозвано", 
			"Звонок", 
			"Эл.письмо", 
			"Факс", 
			"Письмо", 
			"Кассета", 
			"Визит", 
			"от", 
			"к", 
			"персона", 
			"семья", 
			"источник", 
			"иная", 
			"Ненадежное подтверждение или предполагаемые данные", 
			"Сомнительная надежность подтверждения", 
			"Косвенные доказательства", 
			"Прямые и первичные доказательства", 
			"Исследование", 
			"Задача", 
			"Корреспонденция", 
			"Коррекция идентификаторов", 
			"Проверка формата", 
			"Требуется коррекция идентификаторов записей, продолжить?", 
			"Количество объектов в основной базе: {0}", 
			"Синхронизация завершена.", 
			"Поиск патриархов", 
			"Поиск взаимосвязей", 
			"Архив не найден, данные не загружены", 
			"Генеалогическая база данных", 
			"Индекс", 
			"Индекс фамилий", 
			"Индекс имен", 
			"Индекс годов рождения", 
			"Индекс годов смерти", 
			"Общая статистика", 
			"Родословная роспись", 
			"Простой ввод", 
			"Источник (метрики/ревизии)", 
			"Тип источника", 
			"Ревизская сказка", 
			"Метрическая книга", 
			"Год", 
			"Населенный пункт", 
			"Дата события", 
			"Тип события", 
			"Связь", 
			"Примечание", 
			"Отсечение ветвей", 
			"нет", 
			"по границе лет", 
			"по заданным лицам", 
			"- всё -", 
			"- нет -", 
			"- любые -", 
			"Лицо", 
			"Крестный", 
			"Ребенок", 
			"Количество компонентов имени меньше трех.", 
			"Базовая персона (\"Лицо\") не определена первой", 
			"Год источника задан неверно", 
			"Значение неверно", 
			"Операция", 
			"Сравнить базы данных", 
			"Объединить базы данных", 
			"Разделить базу данных", 
			"Объединить дубликаты записей", 
			"Импорт росписей из внешних форматов", 
			"Проверка связности семей", 
			"Проверка базы данных", 
			"Поиск патриархов", 
			"Управление местами", 
			"Поиск совпадений...", 
			"Проверка связности семей", 
			"все", 
			"только живые", 
			"только умершие", 
			"В живых до", 
			"только мужчины", 
			"только женщины", 
			"Маска имени", 
			"Маска местожительства", 
			"Маска фактов", 
			"Только главы семей", 
			"Дата неверна", 
			"Люди", 
			"Годы", 
			"Десятилетия", 
			"Родилось", 
			"Умерло", 
			"Живущие", 
			"Умершие", 
			"Средний возраст", 
			"Средняя продолжительность жизни", 
			"Среднее число детей", 
			"Средний возраст рождения первенца", 
			"Среднее количество браков", 
			"Средний возраст заключения брака", 
			"Количество предков", 
			"Количество потомков", 
			"Количество поколений потомков", 
			"Годы рождения", 
			"Годы рождения (десятилетиями)", 
			"Годы смерти", 
			"Годы смерти (десятилетиями)", 
			"Распределение количества детей", 
			"Возраст рождения первенца", 
			"Возраст вступления в брак", 
			"Разница возрастов супругов", 
			"Выбрать все связи", 
			"Выбрать семью", 
			"Выбрать предков", 
			"Выбрать потомков", 
			"Объединение", 
			"Автопоиск", 
			"Пропустить", 
			"Записи", 
			"Поиск персон", 
			"Прямое сравнение", 
			"Нечеткое сравнение", 
			"Только по имени/отчеству (только женщины)", 
			"Учитывать год рождения", 
			"Точность имени, %", 
			"Погрешность лет", 
			"Исправить", 
			"Поколений потомков не менее", 
			"Установить признак", 
			"Внести в справочник", 
			"Схожие фамилии:", 
			"Схожие имена:", 
			"Выбранные персональные записи удалены", 
			"Запись", 
			"Проблема", 
			"Решение", 
			"Возможно умерший (возраст {0})", 
			"Не задан пол", 
			"Год рождения больше года смерти", 
			"Первый брак в возрасте {0} лет?", 
			"Первый ребенок родился в возрасте {0} лет?", 
			"Потомков", 
			"Поколений", 
			"Количество ссылок", 
			"Обработка мест", 
			"Место уже есть в справочнике",
			"Маркеры ДНК"
		};

		public static string[] LSList = new string[593];

		public static string GetLS(LSID lsid)
		{
			return LSList[(int)lsid - 1];
		}
	}
}
