using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

using GKSys;

/// <summary>
/// Localization: clean
/// </summary>

namespace GKCore
{
	[Guid("F7295BF7-EE01-4DD7-8C44-3BDFEAA9E318")]
	public interface ILocalization
	{
		void SetLang();
	}

	public enum LSID : ushort
	{
		/* 000 */ LSID_None,
		/* 001 */ LSID_First,
		/* 001 */ LSID_MIFile = 1,
		/* 002 */ LSID_MIEdit = 2,
		/* 003 */ LSID_MIPedigree,
		/* 004 */ LSID_MIService,
		/* 005 */ LSID_MIWindow,
		/* 006 */ LSID_MIHelp,
		/* 007 */ LSID_MIFileNew,
		/* 008 */ LSID_MIFileLoad,
		/* 009 */ LSID_MIMRUFiles,
		/* 010 */ LSID_MIFileSave,
		/* 011 */ LSID_MIFileClose,
		/* 012 */ LSID_MIFileProperties,
		/* 013 */ LSID_MIExport,
		/* 014 */ LSID_MIExportToWeb,
		/* 015 */ LSID_MIExportToExcelApp,
		/* 016 */ LSID_MIExportToExcelFile,
		/* 017 */ LSID_MIExit,
		/* 018 */ LSID_MIUndo,
		/* 019 */ LSID_MIRedo,
		/* 020 */ LSID_MIRecordAdd,
		/* 021 */ LSID_MIRecordEdit,
		/* 022 */ LSID_MIRecordDelete,
		/* 023 */ LSID_MIStreamInput,
		/* 024 */ LSID_MITreeAncestors,
		/* 025 */ LSID_MITreeDescendants,
		/* 026 */ LSID_MITreeBoth,
		/* 027 */ LSID_MIPedigree_dAboville,
		/* 028 */ LSID_MIPedigree_Konovalov,
		/* 029 */ LSID_MIMap,
		/* 030 */ LSID_MIStats,
		/* 031 */ LSID_MICalc,
		/* 032 */ LSID_MINamesBook,
		/* 033 */ LSID_MICalendar,
		/* 034 */ LSID_MITimeLine,
		/* 035 */ LSID_MIOrganizer,
		/* 036 */ LSID_MIScripts,

		/* 037 */ LSID_Deprecated_01,

		/* 038 */ LSID_MITreeTools = 38,
		/* 039 */ LSID_MIFilter,
		/* 040 */ LSID_MIOptions,
		/* 041 */ LSID_MIWinCascade,
		/* 042 */ LSID_MIWinHTile,
		/* 043 */ LSID_MIWinVTile,
		/* 044 */ LSID_MIWinMinimize,
		/* 045 */ LSID_MIWinArrange,
		/* 046 */ LSID_MIGenResources,
		/* 047 */ LSID_MIKinshipTerms,
		/* 048 */ LSID_MIFAQ,
		/* 049 */ LSID_MIContext,
		/* 050 */ LSID_MIAbout,
		/* 051 */ LSID_SBRecords,
		/* 052 */ LSID_SBFiltered,
		/* 053 */ LSID_RPIndividuals,
		/* 054 */ LSID_RPFamilies,
		/* 055 */ LSID_RPNotes,
		/* 056 */ LSID_RPMultimedia,
		/* 057 */ LSID_RPSources,
		/* 058 */ LSID_RPRepositories,
		/* 059 */ LSID_RPGroups,
		/* 060 */ LSID_RPResearches,
		/* 061 */ LSID_RPTasks,
		/* 062 */ LSID_RPCommunications,
		/* 063 */ LSID_RPLocations,
		/* 064 */ LSID_UnkFemale,
		/* 065 */ LSID_UnkMale,
		/* 066 */ LSID_SexN,
		/* 067 */ LSID_SexM,
		/* 068 */ LSID_SexF,
		/* 069 */ LSID_SexU,
		/* 070 */ LSID_FileSaveQuery,
		/* 071 */ LSID_ParentsQuery,
		/* 072 */ LSID_PersonDeleteQuery,
		/* 073 */ LSID_FamilyDeleteQuery,
		/* 074 */ LSID_NoteDeleteQuery,
		/* 075 */ LSID_SourceDeleteQuery,
		/* 076 */ LSID_MediaDeleteQuery,
		/* 077 */ LSID_RepositoryDeleteQuery,
		/* 078 */ LSID_GroupDeleteQuery,
		/* 079 */ LSID_ResearchDeleteQuery,
		/* 080 */ LSID_TaskDeleteQuery,
		/* 081 */ LSID_CommunicationDeleteQuery,
		/* 082 */ LSID_LocationDeleteQuery,
		/* 083 */ LSID_Address,
		/* 084 */ LSID_Events,
		/* 085 */ LSID_Surname,
		/* 086 */ LSID_Name,
		/* 087 */ LSID_Patronymic,
		/* 088 */ LSID_Sex,
		/* 089 */ LSID_Nickname,
		/* 090 */ LSID_SurnamePrefix,
		/* 091 */ LSID_NamePrefix,
		/* 092 */ LSID_NameSuffix,
		/* 093 */ LSID_Patriarch,
		/* 094 */ LSID_Bookmark,
		/* 095 */ LSID_Association,
		/* 096 */ LSID_Relation,
		/* 097 */ LSID_Person,
		/* 098 */ LSID_DlgAccept,
		/* 099 */ LSID_DlgCancel,
		/* 100 */ LSID_DlgClose,
		/* 101 */ LSID_DlgSelect,
		/* 102 */ LSID_DlgAppend,
		/* 103 */ LSID_WinPersonNew,
		/* 104 */ LSID_WinPersonEdit,
		/* 105 */ LSID_WinCheckSex,
		/* 106 */ LSID_WinRecordSelect,
		/* 107 */ LSID_WinSourceCitEdit,
		/* 108 */ LSID_WinUserRefEdit,
		/* 109 */ LSID_Note,
		/* 110 */ LSID_Source,
		/* 111 */ LSID_Page,
		/* 112 */ LSID_Certainty,
		/* 113 */ LSID_Reference,
		/* 114 */ LSID_Type,
		/* 115 */ LSID_Family,
		/* 116 */ LSID_Husband,
		/* 117 */ LSID_Wife,
		/* 118 */ LSID_Status,
		/* 119 */ LSID_Childs,
		/* 120 */ LSID_DetachHusbandQuery,
		/* 121 */ LSID_DetachWifeQuery,
		/* 122 */ LSID_DetachChildQuery,
		/* 123 */ LSID_BirthDate,
		/* 124 */ LSID_DeathDate,
		/* 125 */ LSID_Restriction,
		/* 126 */ LSID_Title,
		/* 127 */ LSID_Members,
		/* 128 */ LSID_WinGroupEdit,
		/* 129 */ LSID_DetachMemberQuery,
		/* 130 */ LSID_TimeScale,
		/* 131 */ LSID_CurrentYear,
		/* 132 */ LSID_Telephone,
		/* 133 */ LSID_Mail,
		/* 134 */ LSID_WebSite,
		/* 135 */ LSID_Repository,
		/* 136 */ LSID_Progress,
		/* 137 */ LSID_TimePassed,
		/* 138 */ LSID_TimeRemain,
		/* 139 */ LSID_TimeTotal,
		/* 140 */ LSID_Date,
		/* 141 */ LSID_Text,
		/* 142 */ LSID_ShortTitle,
		/* 143 */ LSID_Author,
		/* 144 */ LSID_Publication,
		/* 145 */ LSID_Common,
		/* 146 */ LSID_DetachRepositoryQuery,
		/* 147 */ LSID_StoreType,
		/* 148 */ LSID_File,
		/* 149 */ LSID_View,
		/* 150 */ LSID_AdvancedWarning,
		/* 151 */ LSID_Father,
		/* 152 */ LSID_Mother,
		/* 153 */ LSID_Parents,
		/* 154 */ LSID_Spouses,
		/* 155 */ LSID_Associations,
		/* 156 */ LSID_UserRefs,
		/* 157 */ LSID_Cal_Gregorian,
		/* 158 */ LSID_Cal_Julian,
		/* 159 */ LSID_Cal_Hebrew,
		/* 160 */ LSID_Cal_Islamic,
		/* 161 */ LSID_Cal_Persian,
		/* 162 */ LSID_Cal_Indian,
		/* 163 */ LSID_Cal_Bahai,
		/* 164 */ LSID_Cal_French,
		/* 165 */ LSID_Cal_Roman,
		/* 166 */ LSID_Unknown,
		/* 167 */ LSID_CopyResultToClipboard,
		/* 168 */ LSID_Other,

		/* 169 */ LSID_Deprecated_03,
		/* 170 */ LSID_Deprecated_04,

		/* 171 */ LSID_Location,
		/* 172 */ LSID_Latitude,
		/* 173 */ LSID_Longitude,
		/* 174 */ LSID_Show,
		/* 175 */ LSID_SearchCoords,
		/* 176 */ LSID_Search,
		/* 177 */ LSID_SelectCoords,
		/* 178 */ LSID_SelectName,
		/* 179 */ LSID_Priority,
		/* 180 */ LSID_Percent,
		/* 181 */ LSID_StartDate,
		/* 182 */ LSID_StopDate,
		/* 183 */ LSID_Goal,
		/* 184 */ LSID_Theme,
		/* 185 */ LSID_Corresponder,
		/* 186 */ LSID_Group,
		/* 187 */ LSID_DetachTaskQuery,
		/* 188 */ LSID_DetachCommunicationQuery,
		/* 189 */ LSID_DetachGroupQuery,
		/* 190 */ LSID_WinResearchEdit,
		/* 191 */ LSID_WinTaskEdit,
		/* 192 */ LSID_WinCommunicationEdit,
		/* 193 */ LSID_Error,
		/* 194 */ LSID_LuaStartFailed,
		/* 195 */ LSID_DateFormatInvalid,
		/* 196 */ LSID_AdCountry,
		/* 197 */ LSID_AdState,
		/* 198 */ LSID_AdCity,
		/* 199 */ LSID_AdPostalCode,
		/* 200 */ LSID_Telephones,
		/* 201 */ LSID_EMails,
		/* 202 */ LSID_WebSites,
		/* 203 */ LSID_Value,
		/* 204 */ LSID_Event,
		/* 205 */ LSID_Place,
		/* 206 */ LSID_Cause,
		/* 207 */ LSID_Agency,
		/* 208 */ LSID_PatFemale,
		/* 209 */ LSID_PatMale,
		/* 210 */ LSID_NotSelectedPerson,
		/* 211 */ LSID_IsNotDefinedSex,
		/* 212 */ LSID_IsNotFamilies,
		/* 213 */ LSID_AncestorsNumberIsInvalid,
		/* 214 */ LSID_DescendantsNumberIsInvalid,
		/* 215 */ LSID_GenerationsVisible,
		/* 216 */ LSID_Unlimited,
		/* 217 */ LSID_Spouse,
		/* 218 */ LSID_MarriageDate,
		/* 219 */ LSID_DetachFatherQuery,
		/* 220 */ LSID_DetachMotherQuery,
		/* 221 */ LSID_DetachSpouseQuery,
		/* 222 */ LSID_DetachParentsQuery,
		/* 223 */ LSID_TM_Both,
		/* 224 */ LSID_TM_Ancestors,
		/* 225 */ LSID_TM_Descendants,
		/* 226 */ LSID_TM_TraceRoot,
		/* 227 */ LSID_DoEdit,
		/* 228 */ LSID_FamilyAdd,
		/* 229 */ LSID_SpouseAdd,
		/* 230 */ LSID_SonAdd,
		/* 231 */ LSID_DaughterAdd,
		/* 232 */ LSID_DoDelete,
		/* 233 */ LSID_RebuildTree,
		/* 234 */ LSID_RebuildKinships,
		/* 235 */ LSID_Links,
		/* 236 */ LSID_PlaceAndAttribute,
		/* 237 */ LSID_LMarriage,
		/* 238 */ LSID_LFamily,
		/* 239 */ LSID_Namesakes,
		/* 240 */ LSID_RemoveEventQuery,
		/* 241 */ LSID_DetachNoteQuery,
		/* 242 */ LSID_DetachMultimediaQuery,
		/* 243 */ LSID_DetachSourceQuery,
		/* 244 */ LSID_RemoveAssociationQuery,
		/* 245 */ LSID_RemoveUserRefQuery,
		/* 246 */ LSID_LoadGedComFailed,
		/* 247 */ LSID_CheckGedComFailed,
		/* 248 */ LSID_BirthDays,
		/* 249 */ LSID_DaysRemained,
		/* 250 */ LSID_Interface,
		/* 251 */ LSID_Trees,
		/* 252 */ LSID_Pedigrees,
		/* 253 */ LSID_SaveCoding,

		/* 254 */ LSID_WorkMode,		// may be deprecated
		/* 255 */ LSID_Simple,			// may be deprecated
		/* 256 */ LSID_Expert,			// may be deprecated

		/* 257 */ LSID_Internet,
		/* 258 */ LSID_ProxyUse,
		/* 259 */ LSID_ProxyServer,
		/* 260 */ LSID_ProxyPort,
		/* 261 */ LSID_ProxyLogin,
		/* 262 */ LSID_ProxyPassword,
		/* 263 */ LSID_Tips,			// may be deprecated
		/* 264 */ LSID_StartupTips,
		/* 265 */ LSID_Language,
		/* 266 */ LSID_ListsAll,
		/* 267 */ LSID_ListPersons,
		/* 268 */ LSID_NamesFormat,
		/* 269 */ LSID_NF1,
		/* 270 */ LSID_NF2,
		/* 271 */ LSID_NF3,
		/* 272 */ LSID_DateFormat,
		/* 273 */ LSID_PlacesWithAddress,
		/* 274 */ LSID_HighlightUnparented,
		/* 275 */ LSID_HighlightUnmarried,
		/* 276 */ LSID_DefList,
		/* 277 */ LSID_ViewTree,
		/* 278 */ LSID_DiffLines,
		/* 279 */ LSID_OnlyYears,
		/* 280 */ LSID_Kinship,
		/* 281 */ LSID_SignsVisible,
		/* 282 */ LSID_TreeDecorative,
		/* 283 */ LSID_PortraitsVisible,
		/* 284 */ LSID_ChildlessExclude,
		/* 285 */ LSID_Decor,
		/* 286 */ LSID_Man,
		/* 287 */ LSID_Woman,
		/* 288 */ LSID_UnkSex,
		/* 289 */ LSID_UnHusband,
		/* 290 */ LSID_UnWife,
		/* 291 */ LSID_Font,
		/* 292 */ LSID_PedigreeGen,
		/* 293 */ LSID_IncludeAttributes,
		/* 294 */ LSID_IncludeNotes,
		/* 295 */ LSID_IncludeSources,
		/* 296 */ LSID_PedigreeFormat,
		/* 297 */ LSID_PF1,
		/* 298 */ LSID_PF2,
		/* 299 */ LSID_RecordGoto,
		/* 300 */ LSID_RecordMoveUp,
		/* 301 */ LSID_RecordMoveDown,
		/* 302 */ LSID_FullName,
		/* 303 */ LSID_BirthPlace,
		/* 304 */ LSID_DeathPlace,
		/* 305 */ LSID_Residence,
		/* 306 */ LSID_Age,
		/* 307 */ LSID_LifeExpectancy,
		/* 308 */ LSID_DaysForBirth,
		/* 309 */ LSID_Religion,
		/* 310 */ LSID_Nationality,
		/* 311 */ LSID_Education,
		/* 312 */ LSID_Occupation,
		/* 313 */ LSID_Caste,
		/* 314 */ LSID_Mili,
		/* 315 */ LSID_MiliInd,
		/* 316 */ LSID_MiliDis,
		/* 317 */ LSID_MiliRank,
		/* 318 */ LSID_Changed,
		/* 319 */ LSID_MarrRegistered,
		/* 320 */ LSID_MarrNotRegistered,
		/* 321 */ LSID_MarrDivorced,
		/* 322 */ LSID_Birth,
		/* 323 */ LSID_Adoption,
		/* 324 */ LSID_Christening,
		/* 325 */ LSID_Graduation,
		/* 326 */ LSID_Retirement,
		/* 327 */ LSID_Naturalization,
		/* 328 */ LSID_Emigration,
		/* 329 */ LSID_Immigration,
		/* 330 */ LSID_Census,
		/* 331 */ LSID_LastWill,
		/* 332 */ LSID_ProbateOfWill,
		/* 333 */ LSID_Death,
		/* 334 */ LSID_Burial,
		/* 335 */ LSID_Cremation,
		/* 336 */ LSID_Fact,
		/* 337 */ LSID_PhysicalDesc,
		/* 338 */ LSID_NationalIDNumber,
		/* 339 */ LSID_SocialSecurityNumber,
		/* 340 */ LSID_ChildsCount,
		/* 341 */ LSID_MarriagesCount,
		/* 342 */ LSID_Property,
		/* 343 */ LSID_NobilityTitle,
		/* 344 */ LSID_Travel,
		/* 345 */ LSID_Hobby,
		/* 346 */ LSID_Award,
		/* 347 */ LSID_RK_Unk,
		/* 348 */ LSID_RK_Father,
		/* 349 */ LSID_RK_Mother,
		/* 350 */ LSID_RK_Husband,
		/* 351 */ LSID_RK_Wife,
		/* 352 */ LSID_RK_Son,
		/* 353 */ LSID_RK_Daughter,
		/* 354 */ LSID_RK_Grandfather,
		/* 355 */ LSID_RK_Grandmother,
		/* 356 */ LSID_RK_Grandson,
		/* 357 */ LSID_RK_Granddaughter,
		/* 358 */ LSID_RK_Brother,
		/* 359 */ LSID_RK_Sister,
		/* 360 */ LSID_RK_SonInLaw,
		/* 361 */ LSID_RK_DaughterInLaw,
		/* 362 */ LSID_RK_HusbandFather,
		/* 363 */ LSID_RK_HusbandMother,
		/* 364 */ LSID_RK_WifeFather,
		/* 365 */ LSID_RK_WifeMother,
		/* 366 */ LSID_RK_Uncle,
		/* 367 */ LSID_RK_Aunt,
		/* 368 */ LSID_RK_Nephew,
		/* 369 */ LSID_RK_Niece,
		/* 370 */ LSID_RK_CousinM,
		/* 371 */ LSID_RK_CousinF,
		/* 372 */ LSID_RK_01,
		/* 373 */ LSID_RK_02,
		/* 374 */ LSID_RK_03,
		/* 375 */ LSID_RK_04,
		/* 376 */ LSID_RK_05,
		/* 377 */ LSID_RK_06,
		/* 378 */ LSID_RK_07,
		/* 379 */ LSID_RK_08,
		/* 380 */ LSID_RK_09,
		/* 381 */ LSID_TooMuchWidth,
		/* 382 */ LSID_Backward,
		/* 383 */ LSID_Forward,
		/* 384 */ LSID_Prev,
		/* 385 */ LSID_Next,
		/* 386 */ LSID_YouKnowWhat,
		/* 387 */ LSID_LoadingLocations,
		/* 388 */ LSID_NotSelected,
		/* 389 */ LSID_MapSelection,
		/* 390 */ LSID_MapSelOnAll,
		/* 391 */ LSID_MSBirthPlaces,
		/* 392 */ LSID_MSDeathPlaces,
		/* 393 */ LSID_MSResiPlace,
		/* 394 */ LSID_MapSelOnSelected,
		/* 395 */ LSID_SaveImage,
		/* 396 */ LSID_FormatUnsupported,
		/* 397 */ LSID_DataLoadError,
		/* 398 */ LSID_ParseError_LineSeq,
		/* 399 */ LSID_PersonParsed,
		/* 400 */ LSID_Generation,
		/* 401 */ LSID_ParseError_AncNotFound,
		/* 402 */ LSID_ParseError_DateInvalid,
		/* 403 */ LSID_DK_0,
		/* 404 */ LSID_DK_1,
		/* 405 */ LSID_DK_2,
		/* 406 */ LSID_DK_3,
		/* 407 */ LSID_DK_4,
		/* 408 */ LSID_DK_5,
		/* 409 */ LSID_DK_6,
		/* 410 */ LSID_DK_7,
		/* 411 */ LSID_DK_8,
		/* 412 */ LSID_DK_9,
		/* 413 */ LSID_FEvt_1,
		/* 414 */ LSID_FEvt_2,
		/* 415 */ LSID_FEvt_3,
		/* 416 */ LSID_FEvt_4,
		/* 417 */ LSID_FEvt_5,
		/* 418 */ LSID_FEvt_6,
		/* 419 */ LSID_FEvt_7,
		/* 420 */ LSID_FEvt_8,
		/* 421 */ LSID_FEvt_9,
		/* 422 */ LSID_STRef,
		/* 423 */ LSID_STArc,
		/* 424 */ LSID_STStg,
		/* 425 */ LSID_MT_01,
		/* 426 */ LSID_MT_02,
		/* 427 */ LSID_MT_03,
		/* 428 */ LSID_MT_04,
		/* 429 */ LSID_MT_05,
		/* 430 */ LSID_MT_06,
		/* 431 */ LSID_MT_07,
		/* 432 */ LSID_MT_08,
		/* 433 */ LSID_MT_09,
		/* 434 */ LSID_MT_10,
		/* 435 */ LSID_MT_11,
		/* 436 */ LSID_MT_12,
		/* 437 */ LSID_MT_13,
		/* 438 */ LSID_MT_14,
		/* 439 */ LSID_MT_15,
		/* 440 */ LSID_Prt_1,
		/* 441 */ LSID_Prt_2,
		/* 442 */ LSID_Prt_3,
		/* 443 */ LSID_Prt_4,
		/* 444 */ LSID_Prt_5,
		/* 445 */ LSID_RStat_1,
		/* 446 */ LSID_RStat_2,
		/* 447 */ LSID_RStat_3,
		/* 448 */ LSID_RStat_4,
		/* 449 */ LSID_RStat_5,
		/* 450 */ LSID_RStat_6,
		/* 451 */ LSID_Com_1,
		/* 452 */ LSID_Com_2,
		/* 453 */ LSID_Com_3,
		/* 454 */ LSID_Com_4,
		/* 455 */ LSID_Com_5,
		/* 456 */ LSID_Com_6,
		/* 457 */ LSID_CD_1,
		/* 458 */ LSID_CD_2,
		/* 459 */ LSID_G_1,
		/* 460 */ LSID_G_2,
		/* 461 */ LSID_G_3,
		/* 462 */ LSID_G_4,
		/* 463 */ LSID_Cert_1,
		/* 464 */ LSID_Cert_2,
		/* 465 */ LSID_Cert_3,
		/* 466 */ LSID_Cert_4,
		/* 467 */ LSID_Research,
		/* 468 */ LSID_Task,
		/* 469 */ LSID_Communication,
		/* 470 */ LSID_IDsCorrect,
		/* 471 */ LSID_FormatCheck,
		/* 472 */ LSID_IDsCorrectNeed,
		/* 473 */ LSID_MainBaseSize,
		/* 474 */ LSID_SyncFin,
		/* 475 */ LSID_PatSearch,
		/* 476 */ LSID_LinksSearch,
		/* 477 */ LSID_ArcNotFound,
		/* 478 */ LSID_GenDB,
		/* 479 */ LSID_GenIndex,
		/* 480 */ LSID_SurnamesIndex,
		/* 481 */ LSID_NamesIndex,

		/* 000 */ LSID_BirthIndex,
		/* 000 */ LSID_DeathIndex,
		/* 000 */ LSID_CommonStats,
		/* 000 */ LSID_ExpPedigree,
		/* 000 */ LSID_InputSimple,
		/* 000 */ LSID_InputSource,
		/* 000 */ LSID_SourceKind,
		/* 000 */ LSID_SK_Rev,
		/* 000 */ LSID_SK_Met,
		/* 000 */ LSID_Year,
		/* 000 */ LSID_Settlement,
		/* 000 */ LSID_EventDate,
		/* 000 */ LSID_EventType,
		/* 000 */ LSID_Join,
		/* 000 */ LSID_Comment,
		/* 000 */ LSID_BranchCut,
		/* 000 */ LSID_Not,
		/* 000 */ LSID_BCut_Years,
		/* 000 */ LSID_BCut_Persons,
		/* 000 */ LSID_SrcAll,
		/* 000 */ LSID_SrcNot,
		/* 000 */ LSID_SrcAny,
		/* 000 */ LSID_PLPerson,
		/* 000 */ LSID_PLGodparent,
		/* 000 */ LSID_Child,
		/* 000 */ LSID_NameInvalid,
		/* 000 */ LSID_BasePersonInvalid,
		/* 000 */ LSID_SourceYearInvalid,
		/* 000 */ LSID_ValueInvalid,
		/* 000 */ LSID_Operation,
		/* 000 */ LSID_ToolOp_1,
		/* 000 */ LSID_ToolOp_2,
		/* 000 */ LSID_ToolOp_3,
		/* 000 */ LSID_ToolOp_4,
		/* 000 */ LSID_ToolOp_5,
		/* 000 */ LSID_ToolOp_6,
		/* 000 */ LSID_ToolOp_7,
		/* 000 */ LSID_ToolOp_8,
		/* 000 */ LSID_ToolOp_9,
		/* 000 */ LSID_SearchMatches,
		/* 000 */ LSID_CheckFamiliesConnection,
		/* 000 */ LSID_All,
		/* 000 */ LSID_OnlyAlive,
		/* 000 */ LSID_OnlyDied,
		/* 000 */ LSID_AliveBefore,
		/* 000 */ LSID_OnlyMans,
		/* 000 */ LSID_OnlyWomans,
		/* 000 */ LSID_NameMask,
		/* 000 */ LSID_PlaceMask,
		/* 000 */ LSID_EventMask,
		/* 000 */ LSID_OnlyPatriarchs,
		/* 000 */ LSID_DateInvalid,
		/* 000 */ LSID_People,
		/* 000 */ LSID_Years,
		/* 000 */ LSID_Decennial,
		/* 000 */ LSID_HowBirthes,
		/* 000 */ LSID_HowDeads,
		/* 000 */ LSID_Living,
		/* 000 */ LSID_Deads,
		/* 000 */ LSID_AvgAge,
		/* 000 */ LSID_AvgLife,
		/* 000 */ LSID_AvgChilds,
		/* 000 */ LSID_AvgBorn,
		/* 000 */ LSID_AvgMarriagesCount,
		/* 000 */ LSID_AvgMarriagesAge,
		/* 000 */ LSID_AncestorsCount,
		/* 000 */ LSID_DescendantsCount,
		/* 000 */ LSID_GenerationsCount,
		/* 000 */ LSID_BirthYears,
		/* 000 */ LSID_BirthYearsDec,
		/* 000 */ LSID_DeathYears,
		/* 000 */ LSID_DeathYearsDec,
		/* 000 */ LSID_DistrChilds,
		/* 000 */ LSID_AgeFirstborn,
		/* 000 */ LSID_MarriagesAge,
		/* 000 */ LSID_DiffSpouses,
		/* 000 */ LSID_SelAll,
		/* 000 */ LSID_SelFamily,
		/* 000 */ LSID_SelAncestors,
		/* 000 */ LSID_SelDescendants,
		/* 000 */ LSID_RecMerge,
		/* 000 */ LSID_RM_Search,
		/* 000 */ LSID_RM_Skip,
		/* 000 */ LSID_RM_Records,
		/* 000 */ LSID_RM_SearchPersons,
		/* 000 */ LSID_RM_DirectMatching,
		/* 000 */ LSID_RM_IndistinctMatching,
		/* 000 */ LSID_RM_OnlyNP,
		/* 000 */ LSID_RM_BirthYear,
		/* 000 */ LSID_RM_NameAccuracy,
		/* 000 */ LSID_RM_YearInaccuracy,
		/* 000 */ LSID_Repair,
		/* 000 */ LSID_MinGenerations,
		/* 000 */ LSID_SetPatFlag,
		/* 000 */ LSID_InsertIntoBook,
		/* 000 */ LSID_SimilarSurnames,
		/* 000 */ LSID_SimilarNames,
		/* 000 */ LSID_RecsDeleted,
		/* 000 */ LSID_Record,
		/* 000 */ LSID_Problem,
		/* 000 */ LSID_Solve,
		/* 000 */ LSID_PersonLonglived,
		/* 000 */ LSID_PersonSexless,
		/* 000 */ LSID_LiveYearsInvalid,
		/* 000 */ LSID_StrangeSpouse,
		/* 000 */ LSID_StrangeParent,
		/* 000 */ LSID_Descendants,
		/* 000 */ LSID_Generations,
		/* 000 */ LSID_LinksCount,
		/* 000 */ LSID_PlacesPrepare,
		/* 000 */ LSID_PlaceAlreadyInBook,
		/* 000 */ LSID_DNAMarkers,
		/* 000 */ LSID_AAF_1,
		/* 000 */ LSID_AAF_2,
		/* 000 */ LSID_EmptyFamily,
		/* 000 */ LSID_RevisionsBackup,
		/* 000 */ LSID_Loading,
		/* 000 */ LSID_FileSaveError,
		/* 000 */ LSID_FillColor,
		/* 000 */ LSID_FillImage,

		/* 000 */ LSID_Last = LSID_FillImage
	}

	public static class LangMan
	{
		private static readonly string[] LSDefList = new string[]
		{
			/* 001 */ "Файл", 
			/* 002 */ "Правка", 
			/* 003 */ "Родословная", 
			/* 000 */ "Сервис", 
			/* 000 */ "&Окна", 
			/* 000 */ "Справка", 
			/* 000 */ "Новый", 
			/* 000 */ "Открыть...", 
			/* 000 */ "Открыть последний", 
			/* 000 */ "Сохранить...", 
			/* 000 */ "Закрыть", 
			/* 000 */ "Свойства файла...", 
			/* 000 */ "Экспорт", 
			/* 000 */ "Экспорт в Web...", 
			/* 000 */ "Экспорт в Excel...", 
			/* 000 */ "Экспорт в Excel-файл...", 
			/* 000 */ "Выход", 
			/* 000 */ "Отменить", 
			/* 000 */ "Вернуть", 
			/* 000 */ "Добавить запись", 
			/* 000 */ "Изменить запись", 
			/* 000 */ "Удалить запись", 
			/* 000 */ "Поточный ввод", 
			/* 000 */ "Древо предков", 
			/* 000 */ "Древо потомков", 
			/* 000 */ "Древо полное", 
			/* 000 */ "Роспись по дАбовиллю", 
			/* 000 */ "Роспись по Коновалову", 
			/* 000 */ "Карты", 
			/* 000 */ "Статистика", 
			/* 000 */ "Калькулятор", 
			/* 000 */ "Справочник имен", 
			/* 000 */ "Календарь", 
			/* 000 */ "Линия времени", 
			/* 000 */ "Органайзер", 
			/* 036 */ "Скрипты...", 

			/* 037 */ "<->",

			/* 038 */ "Инструменты...",
			/* 000 */ "Фильтр",
			/* 000 */ "Настройки", 
			/* 000 */ "&Каскад", 
			/* 000 */ "&Горизонтальная мозаика", 
			/* 000 */ "&Вертикальная мозаика", 
			/* 000 */ "&Свернуть все", 
			/* 000 */ "&Разместить все", 
			/* 000 */ "Ресурсы в Интернете...", 
			/* 000 */ "Терминология родства...", 
			/* 000 */ "Часто задаваемые вопросы...", 
			/* 000 */ "Содержание", 
			/* 000 */ "О программе", 
			/* 000 */ "Записей", 
			/* 000 */ "фильтрованных", 
			/* 000 */ "Персоны", 
			/* 000 */ "Семьи", 
			/* 000 */ "Заметки", 
			/* 000 */ "Мультимедиа", 
			/* 000 */ "Источники", 
			/* 000 */ "Архивы", 
			/* 000 */ "Группы", 
			/* 000 */ "Исследования", 
			/* 000 */ "Задачи", 
			/* 000 */ "Коммуникации", 
			/* 000 */ "Места", 
			/* 000 */ "неизвестная", 
			/* 000 */ "неизвестный", 
			/* 000 */ "?", 
			/* 000 */ "Мужской", 
			/* 000 */ "Женский", 
			/* 000 */ "Неопределенный", 
			/* 000 */ "Файл изменен. Сохранить?", 
			/* 000 */ "У заданного родителя найдена семья \"{0}\". \\nВключить в неё ребенка?", 
			/* 000 */ "Удалить персональную запись \"{0}\"?", 
			/* 000 */ "Удалить семью \"{0}\"?", 
			/* 000 */ "Удалить заметку?", 
			/* 000 */ "Удалить источник \"{0}\"?", 
			/* 000 */ "Удалить мультимедиа \"{0}\"?", 
			/* 000 */ "Удалить архив \"{0}\"?", 
			/* 000 */ "Удалить группу \"{0}\"?", 
			/* 000 */ "Удалить исследование \"{0}\"?", 
			/* 000 */ "Удалить задачу \"{0}\"?", 
			/* 000 */ "Удалить коммуникацию \"{0}\"?", 
			/* 000 */ "Удалить место \"{0}\"?", 
			/* 000 */ "Адрес", 
			/* 000 */ "Факты", 
			/* 000 */ "Фамилия", 
			/* 000 */ "Имя", 
			/* 000 */ "Отчество", 
			/* 000 */ "Пол", 
			/* 000 */ "Прозвище", 
			/* 000 */ "Префикс фамилии", 
			/* 000 */ "Префикс имени", 
			/* 000 */ "Суффикс имени", 
			/* 000 */ "Патриарх", 
			/* 000 */ "Закладка", 
			/* 000 */ "Ассоциация", 
			/* 000 */ "Отношение", 
			/* 000 */ "Персона", 
			/* 000 */ "Принять", 
			/* 000 */ "Отменить", 
			/* 000 */ "Закрыть", 
			/* 000 */ "Выбрать", 
			/* 000 */ "Добавить", 
			/* 000 */ "Новая персональная запись", 
			/* 000 */ "Редактирование персональной записи", 
			/* 000 */ "Проверка пола", 
			/* 000 */ "Выбор записи", 
			/* 000 */ "Цитата источника", 
			/* 000 */ "Пользовательская сноска", 
			/* 000 */ "Заметка", 
			/* 000 */ "Источник", 
			/* 000 */ "Лист/Страница", 
			/* 000 */ "Достоверность", 
			/* 000 */ "Сноска/ссылка", 
			/* 000 */ "Тип", 
			/* 000 */ "Семья", 
			/* 000 */ "Муж", 
			/* 000 */ "Жена", 
			/* 000 */ "Статус", 
			/* 000 */ "Дети", 
			/* 000 */ "Удалить ссылку на мужа?", 
			/* 000 */ "Удалить ссылку на жену?", 
			/* 000 */ "Удалить ссылку на ребенка?", 
			/* 000 */ "Дата рождения", 
			/* 000 */ "Дата смерти", 
			/* 000 */ "Ограничение безопасности", 
			/* 000 */ "Название", 
			/* 000 */ "Участники", 
			/* 000 */ "Редактирование группы", 
			/* 000 */ "Удалить ссылку на участника группы?", 
			/* 000 */ "Шкала времени", 
			/* 000 */ "Текущий год", 
			/* 000 */ "Телефон", 
			/* 000 */ "Эл. почта", 
			/* 000 */ "Сайт", 
			/* 000 */ "Архив", 
			/* 000 */ "Прогресс", 
			/* 000 */ "Времени прошло", 
			/* 000 */ "Времени осталось", 
			/* 000 */ "Времени всего", 
			/* 000 */ "Дата", 
			/* 000 */ "Текст", 
			/* 000 */ "Краткое название", 
			/* 000 */ "Автор", 
			/* 000 */ "Опубликовано", 
			/* 000 */ "Общее", 
			/* 000 */ "Удалить ссылку на архив?", 
			/* 000 */ "Способ хранения", 
			/* 000 */ "Файл", 
			/* 000 */ "Просмотр", 
			/* 000 */ "Для выбранного типа хранения не включен режим расширения", 
			/* 000 */ "Отец", 
			/* 000 */ "Мать", 
			/* 000 */ "Родители", 
			/* 000 */ "Супруги", 
			/* 000 */ "Ассоциации", 
			/* 000 */ "Сноски/Пометки", 
			/* 000 */ "Григорианский", 
			/* 000 */ "Юлианский", 
			/* 000 */ "Еврейский", 
			/* 000 */ "Исламский (Хиджры)", 
			/* 000 */ "Иранский", 
			/* 000 */ "Индийский", 
			/* 000 */ "Бахаи", 
			/* 000 */ "Французский", 
			/* 000 */ "Римский", 
			/* 000 */ "Неизвестно", 

			/* 167 */ "Поместить результат в буфер обмена",
			/* 168 */ "Прочее",

			/* 169 */ "<->",
			/* 170 */ "<->",

			/* 000 */ "Местоположение",
			/* 000 */ "Широта", 
			/* 000 */ "Долгота", 
			/* 000 */ "Показать", 
			/* 000 */ "Поиск координат", 
			/* 000 */ "Поиск", 
			/* 000 */ "Выбрать коорд.", 
			/* 000 */ "Выбрать название", 
			/* 000 */ "Приоритет", 
			/* 000 */ "Процент", 
			/* 000 */ "Запущено", 
			/* 000 */ "Завершено", 
			/* 000 */ "Цель", 
			/* 000 */ "Тема", 
			/* 000 */ "Корреспондент", 
			/* 000 */ "Группа", 
			/* 000 */ "Удалить ссылку на задачу?", 
			/* 000 */ "Удалить ссылку на корреспонденцию?", 
			/* 000 */ "Удалить ссылку на группу?", 
			/* 000 */ "Редактирование исследования", 
			/* 000 */ "Редактирование задачи", 
			/* 000 */ "Редактирование коммуникации", 
			/* 000 */ "Ошибка", 
			/* 000 */ "Ошибка запуска Lua!", 
			/* 000 */ "Некорректный формат даты", 
			/* 000 */ "Страна", 
			/* 000 */ "Штат/Область", 
			/* 000 */ "Город", 
			/* 000 */ "Почтовый код", 
			/* 000 */ "Телефоны", 
			/* 000 */ "Эл. почта", 
			/* 000 */ "Веб-страницы", 
			/* 000 */ "Значение", 
			/* 000 */ "Событие", 
			/* 000 */ "Место", 
			/* 000 */ "Причина", 
			/* 000 */ "Засвидетельствовавший орган", 
			/* 000 */ "Женское", 
			/* 000 */ "Мужское", 
			/* 000 */ "Не выбрана персональная запись", 
			/* 000 */ "У данной персоны не задан пол.", 
			/* 000 */ "У данной персоны нет семей.", 
			/* 000 */ "Расчетное количество предков {0} больше допустимых пределов.", 
			/* 000 */ "Расчетное количество потомков {0} больше допустимых пределов.", 
			/* 000 */ "Показывать поколений:", 
			/* 000 */ "неограниченно", 
			/* 000 */ "Cупруг(а)", 
			/* 000 */ "Дата брака", 
			/* 000 */ "Удалить ссылку на отца?", 
			/* 000 */ "Удалить ссылку на мать?", 
			/* 000 */ "Удалить ссылку на супруга?", 
			/* 000 */ "Удалить персону из семьи родителей?", 
			/* 000 */ "Всё", 
			/* 000 */ "Только предки", 
			/* 000 */ "Только потомки", 
			/* 000 */ "Автосмена центра", 
			/* 000 */ "Редактировать", 
			/* 000 */ "Добавить семью", 
			/* 000 */ "Добавить супруга(у)", 
			/* 000 */ "Добавить сына", 
			/* 000 */ "Добавить дочь", 
			/* 000 */ "Удалить", 
			/* 000 */ "Перестроить древо", 
			/* 000 */ "Перестроить отношения", 
			/* 000 */ "Ссылки", 
			/* 000 */ "Место/Атрибут", 
			/* 000 */ "брак", 
			/* 000 */ "семья", 
			/* 000 */ "Тёзки", 
			/* 000 */ "Удалить факт?", 
			/* 000 */ "Удалить ссылку на заметку?", 
			/* 000 */ "Удалить ссылку на мультимедиа?", 
			/* 000 */ "Удалить ссылку на источник?", 
			/* 000 */ "Удалить ассоциацию?", 
			/* 045 */ "Удалить пользовательскую сноску?", 
			/* 046 */ "Ошибка загрузки файла", 
			/* 047 */ "Ошибка проверки формата", 
			/* 048 */ "Дни рождения", 
			/* 049 */ "До дня рождения \"{0}\" осталось {1} дня(-ей)", 
			/* 050 */ "Интерфейс", 
			/* 051 */ "Родословные древа", 
			/* 052 */ "Росписи", 
			/* 053 */ "Кодировка сохранения файлов", 
			/* 054 */ "Режим работы", 
			/* 055 */ "Простой", 
			/* 056 */ "Продвинутый", 
			/* 057 */ "Загрузка из Интернета", 
			/* 058 */ "Использовать прокси-сервер", 
			/* 059 */ "Сервер", 
			/* 260 */ "Порт", 
			/* 261 */ "Логин", 
			/* 262 */ "Пароль", 
			/* 000 */ "Подсказки", 
			/* 000 */ "Показывать при старте подсказки", 
			/* 000 */ "Язык", 
			/* 000 */ "Все списки", 
			/* 000 */ "Список персон", 
			/* 000 */ "Формат имен в списках", 
			/* 000 */ "Фамилия_Имя_Отчество", 
			/* 000 */ "Фамилия; Имя_Отчество", 
			/* 000 */ "Фамилия; Имя; Отчество", 
			/* 000 */ "Формат даты в списках", 
			/* 000 */ "Включать адрес в строки мест", 
			/* 000 */ "Подсвечивать персоны без родителей", 
			/* 000 */ "Подсвечивать персоны без семьи", 
			/* 000 */ "Значения по умолчанию", 
			/* 000 */ "Отображение персон в древе", 
			/* 000 */ "Разные строки (имя и отчество)", 
			/* 000 */ "Только годы", 
			/* 000 */ "Степень родства", 
			/* 000 */ "Дополнительные символы", 
			/* 000 */ "Декоративное оформление", 
			/* 000 */ "Отображать портреты", 
			/* 000 */ "Исключить умерших в детстве", 
			/* 000 */ "Оформление", 
			/* 000 */ "Мужчина", 
			/* 000 */ "Женщина", 
			/* 000 */ "Неизвестный пол", 
			/* 000 */ "Разведенный супруг", 
			/* 000 */ "Разведенная супруга", 
			/* 000 */ "Шрифт", 
			/* 000 */ "Генерация росписей", 
			/* 000 */ "Включая атрибуты персон", 
			/* 000 */ "Включая заметки", 
			/* 000 */ "Включая источники", 
			/* 000 */ "Формат", 
			/* 000 */ "Избыточный", 
			/* 000 */ "Традиционный", 
			/* 000 */ "Перейти на запись", 
			/* 000 */ "Поместить выше", 
			/* 000 */ "Поместить ниже", 
			/* 000 */ "Полное имя", 
			/* 000 */ "Место рождения", 
			/* 000 */ "Место смерти", 
			/* 000 */ "Местожительство", 
			/* 000 */ "Возраст", 
			/* 000 */ "Продолжительность жизни", 
			/* 000 */ "Дней до ДР", 
			/* 000 */ "Вероисповедание", 
			/* 000 */ "Национальность", 
			/* 000 */ "Образование", 
			/* 000 */ "Профессия", 
			/* 000 */ "Социальное положение", 
			/* 000 */ "Военная служба", 
			/* 000 */ "Призван в ВС", 
			/* 000 */ "Уволен из ВС", 
			/* 000 */ "Звание в ВС", 
			/* 000 */ "Изменено", 
			/* 000 */ "Брак зарегистрирован", 
			/* 000 */ "Брак не зарегистрирован", 
			/* 000 */ "Разведены", 
			/* 000 */ "Рождение", 
			/* 000 */ "Усыновление", 
			/* 000 */ "Крещение", 
			/* 000 */ "Получение ученой степени", 
			/* 000 */ "Уход на пенсию", 
			/* 000 */ "Натурализация", 
			/* 000 */ "Эмиграция", 
			/* 000 */ "Иммиграция", 
			/* 000 */ "Перепись", 
			/* 000 */ "Завещание", 
			/* 000 */ "Утверждение завещания", 
			/* 000 */ "Смерть", 
			/* 000 */ "Похороны", 
			/* 000 */ "Кремация", 
			/* 000 */ "Факт", 
			/* 000 */ "Физическое описание", 
			/* 000 */ "Идентификационный номер", 
			/* 000 */ "Код социального страхования", 
			/* 000 */ "Количество детей", 
			/* 000 */ "Количество браков", 
			/* 000 */ "Собственность", 
			/* 000 */ "Титул", 
			/* 000 */ "Путешествие", 
			/* 000 */ "Хобби", 
			/* 000 */ "Награда", 
			/* 000 */ "?", 
			/* 000 */ "отец", 
			/* 000 */ "мать", 
			/* 000 */ "муж", 
			/* 000 */ "жена", 
			/* 000 */ "сын", 
			/* 000 */ "дочь", 
			/* 000 */ "дед", 
			/* 000 */ "бабушка", 
			/* 000 */ "внук", 
			/* 000 */ "внучка", 
			/* 000 */ "брат", 
			/* 000 */ "сестра", 
			/* 000 */ "зять", 
			/* 000 */ "невестка", 
			/* 000 */ "свекор", 
			/* 000 */ "свекровь", 
			/* 000 */ "тесть", 
			/* 000 */ "теща", 
			/* 000 */ "дядя", 
			/* 000 */ "тетя", 
			/* 000 */ "племянник", 
			/* 000 */ "племянница", 
			/* 000 */ "кузен", 
			/* 000 */ "кузина", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "<reserved>", 
			/* 000 */ "Ширина изображения более 65 тыс. точек. Сохранить невозможно", 
			/* 000 */ "Назад", 
			/* 000 */ "Вперед", 
			/* 000 */ "<reserved>", 
			/* 000 */ "Далее", 
			/* 000 */ "Вы знаете что...", 
			/* 000 */ "Загрузка и поиск мест", 
			/* 000 */ "( не выбран )", 
			/* 000 */ "Выборка", 
			/* 000 */ "По всем людям", 
			/* 000 */ "Места рождения", 
			/* 000 */ "Места смерти", 
			/* 000 */ "Места проживания", 
			/* 000 */ "Только по выбранному", 
			/* 000 */ "Сохранить снимок...", 
			/* 000 */ "Формат не поддерживается", 
			/* 000 */ "Ошибка загрузки данных.", 
			/* 000 */ "Ошибка разбора: номера записей содержат пропуск.", 
			/* 000 */ "Распознана персональная запись", 
			/* 000 */ "Поколение", 
			/* 000 */ "Ошибка разбора: в списке не обнаружен предок с номером", 
			/* 000 */ "Ошибка разбора: дата", 
			/* 000 */ "Точно", 
			/* 000 */ "Ранее", 
			/* 000 */ "Позднее", 
			/* 000 */ "Между", 
			/* 000 */ "Период до", 
			/* 000 */ "Период после", 
			/* 000 */ "Период между", 
			/* 000 */ "Около", 
			/* 000 */ "По расчету", 
			/* 000 */ "По оценке", 
			/* 000 */ "Помолвка", 
			/* 000 */ "Бракосочетание", 
			/* 000 */ "Публичное объявление о бракосочетании", 
			/* 000 */ "Заключение брачного контракта", 
			/* 000 */ "Получение разрешения на брак", 
			/* 000 */ "Заключение брачного соглашения", 
			/* 000 */ "Аннулирование брака", 
			/* 000 */ "Подача заявления о разводе", 
			/* 000 */ "Развод", 
			/* 000 */ "Ссылка на файл", 
			/* 000 */ "Размещение в архиве", 
			/* 000 */ "Размещение в хранилище", 
			/* 000 */ "-", 
			/* 000 */ "Звукозапись", 
			/* 000 */ "Книга", 
			/* 000 */ "Карточка", 
			/* 000 */ "Электронный", 
			/* 000 */ "Микрофиша", 
			/* 000 */ "Фильм", 
			/* 000 */ "Журнал", 
			/* 000 */ "Рукопись", 
			/* 000 */ "Карта", 
			/* 000 */ "Газета", 
			/* 000 */ "Фотография", 
			/* 000 */ "Надгробие", 
			/* 000 */ "Видео", 
			/* 000 */ "- Другой -", 
			/* 000 */ "Не задан", 
			/* 000 */ "Низкий", 
			/* 000 */ "Нормальный", 
			/* 000 */ "Высокий", 
			/* 000 */ "Срочный", 
			/* 000 */ "Определено", 
			/* 000 */ "Выполняется", 
			/* 000 */ "Задержано", 
			/* 000 */ "Осложнения", 
			/* 000 */ "Завершено", 
			/* 000 */ "Отозвано", 
			/* 000 */ "Звонок", 
			/* 000 */ "Эл.письмо", 
			/* 000 */ "Факс", 
			/* 000 */ "Письмо", 
			/* 000 */ "Кассета", 
			/* 000 */ "Визит", 
			/* 000 */ "от", 
			/* 000 */ "к", 
			/* 000 */ "персона", 
			/* 000 */ "семья", 
			/* 000 */ "источник", 
			/* 000 */ "иная", 
			/* 000 */ "Ненадежное подтверждение или предполагаемые данные", 
			/* 000 */ "Сомнительная надежность подтверждения", 
			/* 000 */ "Косвенные доказательства", 
			/* 000 */ "Прямые и первичные доказательства", 
			/* 000 */ "Исследование", 
			/* 000 */ "Задача", 
			/* 000 */ "Корреспонденция", 
			/* 000 */ "Коррекция идентификаторов", 
			/* 000 */ "Проверка формата", 
			/* 000 */ "Требуется коррекция идентификаторов записей, продолжить?", 
			/* 000 */ "Количество объектов в основной базе: {0}", 
			/* 000 */ "Синхронизация завершена.", 
			/* 000 */ "Поиск патриархов", 
			/* 000 */ "Поиск взаимосвязей", 
			/* 000 */ "Медиа-файл не загружен, т.к. отсутствует в медиа-контейнере (хранилище или архиве)", 
			/* 000 */ "Генеалогическая база данных", 
			/* 000 */ "Индекс", 
			/* 000 */ "Индекс фамилий", 
			/* 000 */ "Индекс имен", 
			/* 000 */ "Индекс годов рождения", 
			/* 000 */ "Индекс годов смерти", 
			/* 000 */ "Общая статистика", 
			/* 000 */ "Родословная роспись", 
			/* 000 */ "Простой ввод", 
			/* 000 */ "Источник (метрики/ревизии)", 
			/* 000 */ "Тип источника", 
			/* 000 */ "Ревизская сказка", 
			/* 000 */ "Метрическая книга", 
			/* 000 */ "Год", 
			/* 000 */ "Населенный пункт", 
			/* 000 */ "Дата события", 
			/* 000 */ "Тип события", 
			/* 000 */ "Связь", 
			/* 000 */ "Примечание", 
			/* 000 */ "Отсечение ветвей", 
			/* 000 */ "нет", 
			/* 000 */ "по границе лет", 
			/* 000 */ "по заданным лицам", 
			/* 000 */ "- всё -", 
			/* 000 */ "- нет -", 
			/* 000 */ "- любые -", 
			/* 000 */ "Лицо", 
			/* 000 */ "Крестный", 
			/* 000 */ "Ребенок", 
			/* 000 */ "Количество компонентов имени меньше трех.", 
			/* 000 */ "Базовая персона (\"Лицо\") не определена первой", 
			/* 000 */ "Год источника задан неверно", 
			/* 000 */ "Значение неверно", 
			/* 000 */ "Операция", 
			/* 000 */ "Сравнить базы данных", 
			/* 000 */ "Объединить базы данных", 
			/* 000 */ "Разделить базу данных", 
			/* 000 */ "Объединить дубликаты записей", 
			/* 000 */ "Импорт росписей из внешних форматов", 
			/* 000 */ "Проверка связности семей", 
			/* 000 */ "Проверка базы данных", 
			/* 000 */ "Поиск патриархов", 
			/* 000 */ "Управление местами", 
			/* 000 */ "Поиск совпадений...", 
			/* 000 */ "Проверка связности семей", 
			/* 000 */ "все", 
			/* 000 */ "только живые", 
			/* 000 */ "только умершие", 
			/* 000 */ "В живых до", 
			/* 000 */ "только мужчины", 
			/* 000 */ "только женщины", 
			/* 000 */ "Маска имени", 
			/* 000 */ "Маска местожительства", 
			/* 000 */ "Маска фактов", 
			/* 000 */ "Только главы семей", 
			/* 000 */ "Дата неверна", 
			/* 000 */ "Люди", 
			/* 000 */ "Годы", 
			/* 000 */ "Десятилетия", 
			/* 000 */ "Родилось", 
			/* 000 */ "Умерло", 
			/* 000 */ "Живущие", 
			/* 000 */ "Умершие", 
			/* 000 */ "Средний возраст", 
			/* 000 */ "Средняя продолжительность жизни", 
			/* 000 */ "Среднее число детей", 
			/* 000 */ "Средний возраст рождения первенца", 
			/* 000 */ "Среднее количество браков", 
			/* 000 */ "Средний возраст заключения брака", 
			/* 000 */ "Количество предков", 
			/* 000 */ "Количество потомков", 
			/* 000 */ "Количество поколений потомков", 
			/* 000 */ "Годы рождения", 
			/* 000 */ "Годы рождения (десятилетиями)", 
			/* 000 */ "Годы смерти", 
			/* 000 */ "Годы смерти (десятилетиями)", 
			/* 000 */ "Распределение количества детей", 
			/* 000 */ "Возраст рождения первенца", 
			/* 000 */ "Возраст вступления в брак", 
			/* 000 */ "Разница возрастов супругов", 
			/* 000 */ "Выбрать все связи", 
			/* 000 */ "Выбрать семью", 
			/* 000 */ "Выбрать предков", 
			/* 000 */ "Выбрать потомков", 
			/* 000 */ "Объединение", 
			/* 000 */ "Автопоиск", 
			/* 000 */ "Пропустить", 
			/* 000 */ "Записи", 
			/* 000 */ "Поиск персон", 
			/* 000 */ "Прямое сравнение", 
			/* 000 */ "Нечеткое сравнение", 
			/* 000 */ "Только по имени/отчеству (только женщины)", 
			/* 000 */ "Учитывать год рождения", 
			/* 000 */ "Точность имени, %", 
			/* 000 */ "Погрешность лет", 
			/* 000 */ "Исправить", 
			/* 000 */ "Поколений потомков не менее", 
			/* 000 */ "Установить признак", 
			/* 000 */ "Внести в справочник", 
			/* 000 */ "Схожие фамилии:", 
			/* 000 */ "Схожие имена:", 
			/* 000 */ "Выбранные персональные записи удалены", 
			/* 000 */ "Запись", 
			/* 000 */ "Проблема", 
			/* 000 */ "Решение", 
			/* 000 */ "Возможно умерший (возраст {0})", 
			/* 000 */ "Не задан пол", 
			/* 000 */ "Год рождения больше года смерти", 
			/* 000 */ "Первый брак в возрасте {0} лет?", 
			/* 000 */ "Первый ребенок родился в возрасте {0} лет?", 
			/* 000 */ "Потомков", 
			/* 000 */ "Поколений", 
			/* 000 */ "Количество ссылок", 
			/* 000 */ "Обработка мест", 
			/* 000 */ "Место уже есть в справочнике",
			/* 000 */ "Маркеры ДНК",
			/* 000 */ "Ср.возр.рождения первенца на ДР родителя",
			/* 000 */ "Ср.возр.рождения первенца на ДР ребенка",
			/* 000 */ "Пустая запись семьи",
			/* 000 */ "Сохранять версии файлов",
			/* 000 */ "Загрузка",
			/* 000 */ "Ошибка сохранения файла \"{0}\"{1}.",
			/* 000 */ "Цвет фона...",
			/* 000 */ "Изображение фона..."
		};

		public static string[] LSList = new string[(int)LSID.LSID_Last + 1];

		public static string LS(LSID lsid)
		{
			return LSList[(int)lsid - 1];
		}

		public static bool LoadFromFile([In] string aFileName)
		{
			bool Result = false;
			if (File.Exists(aFileName))
			{
				StreamReader lng_file = new StreamReader(aFileName, Encoding.UTF8);
				try
				{
					lng_file.ReadLine();
					int i = 0;
					while (lng_file.Peek() != -1)
					{
						string st = lng_file.ReadLine();
						LSList[i] = st.Trim();
						i++;
					}
					Result = true;
				}
				finally
				{
					lng_file.Close();
				}
			}
			return Result;
		}

		public static void DefInit()
		{
			for (LSID id = LSID.LSID_First; id <= LSID.LSID_Last; id++)
			{
				LSList[(int)id - 1] = LSDefList[(int)id - 1];
			}
		}

		public static void SaveDefaultLanguage()
		{
			StreamWriter lf = new StreamWriter(SysUtils.GetAppPath() + "langs\\russian.sample", false, Encoding.UTF8);
			try
			{
				lf.WriteLine(";" + 1049.ToString() + "," + "Русский");
				for (LSID i = LSID.LSID_First; i <= LSID.LSID_Last; i++)
				{
					lf.WriteLine(LSDefList[(int)i - 1]);
				}
			}
			finally
			{
				lf.Close();
			}
		}
	}

}
