/*
 *  "GEDKeeper", the personal genealogical database editor.
 *  Copyright (C) 2009-2016 by Serg V. Zhdanovskih (aka Alchemist, aka Norseman).
 *
 *  This file is part of "GEDKeeper".
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

using GKCore.Interfaces;

namespace GKCore
{
    public enum LSID
    {
        /* 000 */ LSID_None,
        /* 001 */ LSID_First,

        /* 001 */ LSID_MIFile = 1,
        /* 002 */ LSID_MIEdit = 2,
        /* 003 */ LSID_MIPedigree,
        /* 004 */ LSID_MIService,
        /* 005 */ LSID_MIWindow,
        /* 006 */ LSID_MIHelp,
        /* 007 */ LSID_MIFileNew,
        /* 008 */ LSID_MIFileLoad,
        /* 009 */ LSID_MIMRUFiles,
        /* 010 */ LSID_MIFileSave,
        /* 011 */ LSID_MIFileClose,
        /* 012 */ LSID_MIFileProperties,
        /* 013 */ LSID_MIExport,
        /* 014 */ LSID_MIExportToFamilyBook,

        /* 015 */ LSID_Deprecated_00,

        /* 016 */ LSID_MIExportToExcelFile,
        /* 017 */ LSID_MIExit,

        /* 018 */ LSID_Deprecated_01,
        /* 019 */ LSID_Deprecated_02,

        /* 020 */ LSID_MIRecordAdd,
        /* 021 */ LSID_MIRecordEdit,
        /* 022 */ LSID_MIRecordDelete,

        /* 023 */ LSID_Deprecated_03,

        /* 024 */ LSID_MITreeAncestors,
        /* 025 */ LSID_MITreeDescendants,
        /* 026 */ LSID_MITreeBoth,
        /* 027 */ LSID_MIPedigree_dAboville,
        /* 028 */ LSID_MIPedigree_Konovalov,
        /* 029 */ LSID_MIMap,
        /* 030 */ LSID_MIStats,

        /* 031 */ LSID_MICalc, // deprecated
        /* 032 */ LSID_MINamesBook, // deprecated
        /* 033 */ LSID_MICalendar, // deprecated
        /* 034 */ LSID_MITimeLine, // deprecated

        /* 035 */ LSID_MIOrganizer,
        /* 036 */ LSID_MIScripts,

        /* 037 */ LSID_Deprecated_04,

        /* 038 */ LSID_MITreeTools = 38,
        /* 039 */ LSID_MIFilter,
        /* 040 */ LSID_MIOptions,
        /* 041 */ LSID_MIWinCascade,
        /* 042 */ LSID_MIWinHTile,
        /* 043 */ LSID_MIWinVTile,
        /* 044 */ LSID_MIWinMinimize,
        /* 045 */ LSID_MIWinArrange,

        /* 046 */ LSID_MIGenResources, // deprecated
        /* 047 */ LSID_MIKinshipTerms, // deprecated
        /* 048 */ LSID_MIFAQ, // deprecated

        /* 049 */ LSID_MIContext,
        /* 050 */ LSID_MIAbout,
        /* 051 */ LSID_SBRecords,
        /* 052 */ LSID_SBFiltered,

        /* 053 */ LSID_RPIndividuals,
        /* 054 */ LSID_RPFamilies,
        /* 055 */ LSID_RPNotes,
        /* 056 */ LSID_RPMultimedia,
        /* 057 */ LSID_RPSources,
        /* 058 */ LSID_RPRepositories,
        /* 059 */ LSID_RPGroups,
        /* 060 */ LSID_RPResearches,
        /* 061 */ LSID_RPTasks,
        /* 062 */ LSID_RPCommunications,
        /* 063 */ LSID_RPLocations,

        /* 064 */ LSID_UnkFemale,
        /* 065 */ LSID_UnkMale,
        /* 066 */ LSID_SexN,
        /* 067 */ LSID_SexM,
        /* 068 */ LSID_SexF,
        /* 069 */ LSID_SexU,
        /* 070 */ LSID_FileSaveQuery,
        /* 071 */ LSID_ParentsQuery,
        /* 072 */ LSID_PersonDeleteQuery,
        /* 073 */ LSID_FamilyDeleteQuery,
        /* 074 */ LSID_NoteDeleteQuery,
        /* 075 */ LSID_SourceDeleteQuery,
        /* 076 */ LSID_MediaDeleteQuery,
        /* 077 */ LSID_RepositoryDeleteQuery,
        /* 078 */ LSID_GroupDeleteQuery,
        /* 079 */ LSID_ResearchDeleteQuery,
        /* 080 */ LSID_TaskDeleteQuery,
        /* 081 */ LSID_CommunicationDeleteQuery,
        /* 082 */ LSID_LocationDeleteQuery,
        /* 083 */ LSID_Address,
        /* 084 */ LSID_Events,
        /* 085 */ LSID_Surname,
        /* 086 */ LSID_Name,
        /* 087 */ LSID_Patronymic,
        /* 088 */ LSID_Sex,
        /* 089 */ LSID_Nickname,
        /* 090 */ LSID_SurnamePrefix,
        /* 091 */ LSID_NamePrefix,
        /* 092 */ LSID_NameSuffix,
        /* 093 */ LSID_Patriarch,
        /* 094 */ LSID_Bookmark,
        /* 095 */ LSID_Association,
        /* 096 */ LSID_Relation,
        /* 097 */ LSID_Person,

        /* 098 */ LSID_DlgAccept,
        /* 099 */ LSID_DlgCancel,
        /* 100 */ LSID_DlgClose,

        /* 101 */ LSID_DlgSelect,
        /* 102 */ LSID_DlgAppend,
        /* 103 */ LSID_WinPersonNew,
        /* 104 */ LSID_WinPersonEdit,
        /* 105 */ LSID_WinCheckSex,
        /* 106 */ LSID_WinRecordSelect,
        /* 107 */ LSID_WinSourceCitEdit,
        /* 108 */ LSID_WinUserRefEdit,
        /* 109 */ LSID_Note,
        /* 110 */ LSID_Source,
        /* 111 */ LSID_Page,
        /* 112 */ LSID_Certainty,
        /* 113 */ LSID_Reference,
        /* 114 */ LSID_Type,
        /* 115 */ LSID_Family,
        /* 116 */ LSID_Husband,
        /* 117 */ LSID_Wife,
        /* 118 */ LSID_Status,
        /* 119 */ LSID_Childs,
        /* 120 */ LSID_DetachHusbandQuery,
        /* 121 */ LSID_DetachWifeQuery,
        /* 122 */ LSID_DetachChildQuery,
        /* 123 */ LSID_BirthDate,
        /* 124 */ LSID_DeathDate,
        /* 125 */ LSID_Restriction,
        /* 126 */ LSID_Title,
        /* 127 */ LSID_Members,
        /* 128 */ LSID_WinGroupEdit,
        /* 129 */ LSID_DetachMemberQuery,
        /* 130 */ LSID_MediaView,
        /* 131 */ LSID_Stage,
        /* 132 */ LSID_Telephone,
        /* 133 */ LSID_Mail,
        /* 134 */ LSID_WebSite,
        /* 135 */ LSID_Repository,
        /* 136 */ LSID_Progress,
        /* 137 */ LSID_TimePassed,
        /* 138 */ LSID_TimeRemain,
        /* 139 */ LSID_TimeTotal,
        /* 140 */ LSID_Date,
        /* 141 */ LSID_Text,
        /* 142 */ LSID_ShortTitle,
        /* 143 */ LSID_Author,
        /* 144 */ LSID_Publication,
        /* 145 */ LSID_Common,
        /* 146 */ LSID_DetachRepositoryQuery,
        /* 147 */ LSID_StoreType,
        /* 148 */ LSID_File,
        /* 149 */ LSID_View,
        /* 150 */ LSID_AdvancedWarning,
        /* 151 */ LSID_Father,
        /* 152 */ LSID_Mother,
        /* 153 */ LSID_Parents,
        /* 154 */ LSID_Spouses,
        /* 155 */ LSID_Associations,
        /* 156 */ LSID_UserRefs,
        /* 157 */ LSID_Cal_Gregorian,
        /* 158 */ LSID_Cal_Julian,
        /* 159 */ LSID_Cal_Hebrew,
        /* 160 */ LSID_Cal_Islamic,
        /* 161 */ LSID_Cal_Persian,
        /* 162 */ LSID_Cal_Indian,
        /* 163 */ LSID_Cal_Bahai,
        /* 164 */ LSID_Cal_French,
        /* 165 */ LSID_Cal_Roman,
        /* 166 */ LSID_Unknown,
        /* 167 */ LSID_Summary,
        /* 168 */ LSID_Other,
        /* 169 */ LSID_Submission,
        /* 170 */ LSID_Submitter,
        /* 171 */ LSID_Location,
        /* 172 */ LSID_Latitude,
        /* 173 */ LSID_Longitude,
        /* 174 */ LSID_Show,
        /* 175 */ LSID_SearchCoords,
        /* 176 */ LSID_Search,
        /* 177 */ LSID_SelectCoords,
        /* 178 */ LSID_SelectName,
        /* 179 */ LSID_Priority,
        /* 180 */ LSID_Percent,
        /* 181 */ LSID_StartDate,
        /* 182 */ LSID_StopDate,
        /* 183 */ LSID_Goal,
        /* 184 */ LSID_Theme,
        /* 185 */ LSID_Corresponder,
        /* 186 */ LSID_Group,
        /* 187 */ LSID_DetachTaskQuery,
        /* 188 */ LSID_DetachCommunicationQuery,
        /* 189 */ LSID_DetachGroupQuery,
        /* 190 */ LSID_WinResearchEdit,
        /* 191 */ LSID_WinTaskEdit,
        /* 192 */ LSID_WinCommunicationEdit,
        /* 193 */ LSID_Error,
        /* 194 */ LSID_LuaStartFailed,
        /* 195 */ LSID_DateFormatInvalid,
        /* 196 */ LSID_AdCountry,
        /* 197 */ LSID_AdState,
        /* 198 */ LSID_AdCity,
        /* 199 */ LSID_AdPostalCode,
        /* 200 */ LSID_Telephones,

        /* 201 */ LSID_EMails,
        /* 202 */ LSID_WebSites,
        /* 203 */ LSID_Value,
        /* 204 */ LSID_Event,
        /* 205 */ LSID_Place,
        /* 206 */ LSID_Cause,
        /* 207 */ LSID_Agency,
        /* 208 */ LSID_PatFemale,
        /* 209 */ LSID_PatMale,
        /* 210 */ LSID_NotSelectedPerson,
        /* 211 */ LSID_IsNotDefinedSex,
        /* 212 */ LSID_IsNotFamilies,
        /* 213 */ LSID_AncestorsNumberIsInvalid,
        /* 214 */ LSID_DescendantsNumberIsInvalid,
        /* 215 */ LSID_GenerationsVisible,
        /* 216 */ LSID_Unlimited,
        /* 217 */ LSID_Spouse,
        /* 218 */ LSID_MarriageDate,
        /* 219 */ LSID_DetachFatherQuery,
        /* 220 */ LSID_DetachMotherQuery,
        /* 221 */ LSID_DetachSpouseQuery,
        /* 222 */ LSID_DetachParentsQuery,
        /* 223 */ LSID_TM_Both,
        /* 224 */ LSID_TM_Ancestors,
        /* 225 */ LSID_TM_Descendants,
        /* 226 */ LSID_TM_TraceSelected,
        /* 227 */ LSID_DoEdit,
        /* 228 */ LSID_FamilyAdd,
        /* 229 */ LSID_SpouseAdd,
        /* 230 */ LSID_SonAdd,
        /* 231 */ LSID_DaughterAdd,
        /* 232 */ LSID_DoDelete,
        /* 233 */ LSID_RebuildTree,
        /* 234 */ LSID_RebuildKinships,
        /* 235 */ LSID_Links,
        /* 236 */ LSID_PlaceAndAttribute,
        /* 237 */ LSID_LMarriage,
        /* 238 */ LSID_LFamily,
        /* 239 */ LSID_Namesakes,
        /* 240 */ LSID_RemoveEventQuery,
        /* 241 */ LSID_DetachNoteQuery,
        /* 242 */ LSID_DetachMultimediaQuery,
        /* 243 */ LSID_DetachSourceQuery,
        /* 244 */ LSID_RemoveAssociationQuery,
        /* 245 */ LSID_RemoveUserRefQuery,
        /* 246 */ LSID_LoadGedComFailed,
        /* 247 */ LSID_CheckGedComFailed,
        /* 248 */ LSID_BirthDays,
        /* 249 */ LSID_DaysRemained,
        /* 250 */ LSID_Interface,
        /* 251 */ LSID_Trees,
        /* 252 */ LSID_Pedigrees,
        /* 253 */ LSID_SaveCoding,

        /* 254 */ LSID_Deprecated_07,
        /* 255 */ LSID_Deprecated_08,
        /* 256 */ LSID_Deprecated_09,

        /* 257 */ LSID_Internet,
        /* 258 */ LSID_ProxyUse,
        /* 259 */ LSID_ProxyServer,
        /* 260 */ LSID_ProxyPort,
        /* 261 */ LSID_ProxyLogin,
        /* 262 */ LSID_Password,
        /* 263 */ LSID_PasswordIsNotSpecified,
        /* 264 */ LSID_StartupTips,
        /* 265 */ LSID_Language,
        /* 266 */ LSID_ListsAll,
        /* 267 */ LSID_ListPersons,
        /* 268 */ LSID_NamesFormat,
        /* 269 */ LSID_NF1,
        /* 270 */ LSID_NF2,
        /* 271 */ LSID_NF3,
        /* 272 */ LSID_DateFormat,
        /* 273 */ LSID_PlacesWithAddress,
        /* 274 */ LSID_HighlightUnparented,
        /* 275 */ LSID_HighlightUnmarried,
        /* 276 */ LSID_DefList,
        /* 277 */ LSID_ViewTree,
        /* 278 */ LSID_DiffLines,
        /* 279 */ LSID_OnlyYears,
        /* 280 */ LSID_Kinship,
        /* 281 */ LSID_SignsVisible,
        /* 282 */ LSID_TreeDecorative,
        /* 283 */ LSID_PortraitsVisible,
        /* 284 */ LSID_ChildlessExclude,
        /* 285 */ LSID_Decor,
        /* 286 */ LSID_Man,
        /* 287 */ LSID_Woman,
        /* 288 */ LSID_UnkSex,
        /* 289 */ LSID_UnHusband,
        /* 290 */ LSID_UnWife,
        /* 291 */ LSID_Font,
        /* 292 */ LSID_PedigreeGen,
        /* 293 */ LSID_IncludeAttributes,
        /* 294 */ LSID_IncludeNotes,
        /* 295 */ LSID_IncludeSources,
        /* 296 */ LSID_PedigreeFormat,
        /* 297 */ LSID_PF1,
        /* 298 */ LSID_PF2,
        /* 299 */ LSID_RecordGoto,
        /* 300 */ LSID_RecordMoveUp,

        /* 301 */ LSID_RecordMoveDown,
        /* 302 */ LSID_FullName,
        /* 303 */ LSID_BirthPlace,
        /* 304 */ LSID_DeathPlace,
        /* 305 */ LSID_Residence,
        /* 306 */ LSID_Age,
        /* 307 */ LSID_LifeExpectancy,
        /* 308 */ LSID_DaysForBirth,
        /* 309 */ LSID_Religion,
        /* 310 */ LSID_Nationality,
        /* 311 */ LSID_Education,
        /* 312 */ LSID_Occupation,
        /* 313 */ LSID_Caste,
        /* 314 */ LSID_Mili,
        /* 315 */ LSID_MiliInd,
        /* 316 */ LSID_MiliDis,
        /* 317 */ LSID_MiliRank,
        /* 318 */ LSID_Changed,
        /* 319 */ LSID_MarrRegistered,
        /* 320 */ LSID_MarrNotRegistered,
        /* 321 */ LSID_MarrDivorced,
        /* 322 */ LSID_Birth,
        /* 323 */ LSID_Adoption,
        /* 324 */ LSID_Christening,
        /* 325 */ LSID_Graduation,
        /* 326 */ LSID_Retirement,
        /* 327 */ LSID_Naturalization,
        /* 328 */ LSID_Emigration,
        /* 329 */ LSID_Immigration,
        /* 330 */ LSID_Census,
        /* 331 */ LSID_LastWill,
        /* 332 */ LSID_ProbateOfWill,
        /* 333 */ LSID_Death,
        /* 334 */ LSID_Burial,
        /* 335 */ LSID_Cremation,
        /* 336 */ LSID_Fact,
        /* 337 */ LSID_PhysicalDesc,
        /* 338 */ LSID_NationalIDNumber,
        /* 339 */ LSID_SocialSecurityNumber,
        /* 340 */ LSID_ChildsCount,
        /* 341 */ LSID_MarriagesCount,
        /* 342 */ LSID_Property,
        /* 343 */ LSID_NobilityTitle,
        /* 344 */ LSID_Travel,
        /* 345 */ LSID_Hobby,
        /* 346 */ LSID_Award,
        /* 347 */ LSID_RK_Unk,
        /* 348 */ LSID_RK_Father,
        /* 349 */ LSID_RK_Mother,
        /* 350 */ LSID_RK_Husband,
        /* 351 */ LSID_RK_Wife,
        /* 352 */ LSID_RK_Son,
        /* 353 */ LSID_RK_Daughter,
        /* 354 */ LSID_RK_Grandfather,
        /* 355 */ LSID_RK_Grandmother,
        /* 356 */ LSID_RK_Grandson,
        /* 357 */ LSID_RK_Granddaughter,
        /* 358 */ LSID_RK_Brother,
        /* 359 */ LSID_RK_Sister,
        /* 360 */ LSID_RK_SonInLaw,
        /* 361 */ LSID_RK_DaughterInLaw,
        /* 362 */ LSID_RK_HusbandFather,
        /* 363 */ LSID_RK_HusbandMother,
        /* 364 */ LSID_RK_WifeFather,
        /* 365 */ LSID_RK_WifeMother,
        /* 366 */ LSID_RK_Uncle,
        /* 367 */ LSID_RK_Aunt,
        /* 368 */ LSID_RK_Nephew,
        /* 369 */ LSID_RK_Niece,
        /* 370 */ LSID_RK_CousinM,
        /* 371 */ LSID_RK_CousinF,
        /* 372 */ LSID_RK_01,
        /* 373 */ LSID_RK_02,
        /* 374 */ LSID_RK_03,
        /* 375 */ LSID_RK_04,
        /* 376 */ LSID_RK_05,
        /* 377 */ LSID_RK_06,
        /* 378 */ LSID_RK_07,
        /* 379 */ LSID_RK_08,
        /* 380 */ LSID_RK_09,
        /* 381 */ LSID_TooMuchWidth,
        /* 382 */ LSID_Backward,
        /* 383 */ LSID_Forward,
        /* 384 */ LSID_Prev,
        /* 385 */ LSID_Next,
        /* 386 */ LSID_YouKnowWhat,
        /* 387 */ LSID_LoadingLocations,
        /* 388 */ LSID_NotSelected,
        /* 389 */ LSID_MapSelection,
        /* 390 */ LSID_MapSelOnAll,
        /* 391 */ LSID_MSBirthPlaces,
        /* 392 */ LSID_MSDeathPlaces,
        /* 393 */ LSID_MSResiPlace,
        /* 394 */ LSID_MapSelOnSelected,
        /* 395 */ LSID_SaveImage,

        /* 396 */ LSID_FormatUnsupported, // may be deprecated
        /* 397 */ LSID_DataLoadError, // may be deprecated

        /* 398 */ LSID_DocPrint,
        /* 399 */ LSID_DocPreview,
        /* 400 */ LSID_Generation,

        /* 401 */ LSID_Deprecated_13,
        /* 402 */ LSID_Deprecated_14,

        /* 403 */ LSID_DK_0,
        /* 404 */ LSID_DK_1,
        /* 405 */ LSID_DK_2,
        /* 406 */ LSID_DK_3,
        /* 407 */ LSID_DK_4,
        /* 408 */ LSID_DK_5,
        /* 409 */ LSID_DK_6,
        /* 410 */ LSID_DK_7,
        /* 411 */ LSID_DK_8,
        /* 412 */ LSID_DK_9,
        /* 413 */ LSID_FEvt_1,
        /* 414 */ LSID_FEvt_2,
        /* 415 */ LSID_FEvt_3,
        /* 416 */ LSID_FEvt_4,
        /* 417 */ LSID_FEvt_5,
        /* 418 */ LSID_FEvt_6,
        /* 419 */ LSID_FEvt_7,
        /* 420 */ LSID_FEvt_8,
        /* 421 */ LSID_FEvt_9,
        /* 422 */ LSID_STRef,
        /* 423 */ LSID_STArc,
        /* 424 */ LSID_STStg,
        /* 425 */ LSID_DefaultValue,
        /* 426 */ LSID_MT_02,
        /* 427 */ LSID_MT_03,
        /* 428 */ LSID_MT_04,
        /* 429 */ LSID_MT_05,
        /* 430 */ LSID_MT_06,
        /* 431 */ LSID_MT_07,
        /* 432 */ LSID_MT_08,
        /* 433 */ LSID_MT_09,
        /* 434 */ LSID_MT_10,
        /* 435 */ LSID_MT_11,
        /* 436 */ LSID_MT_12,
        /* 437 */ LSID_MT_13,
        /* 438 */ LSID_MT_14,
        /* 439 */ LSID_MT_15,
        /* 440 */ LSID_Prt_1,
        /* 441 */ LSID_Prt_2,
        /* 442 */ LSID_Prt_3,
        /* 443 */ LSID_Prt_4,
        /* 444 */ LSID_Prt_5,
        /* 445 */ LSID_RStat_1,
        /* 446 */ LSID_RStat_2,
        /* 447 */ LSID_RStat_3,
        /* 448 */ LSID_RStat_4,
        /* 449 */ LSID_RStat_5,
        /* 450 */ LSID_RStat_6,
        /* 451 */ LSID_Com_1,
        /* 452 */ LSID_Com_2,
        /* 453 */ LSID_Com_3,
        /* 454 */ LSID_Com_4,
        /* 455 */ LSID_Com_5,
        /* 456 */ LSID_Com_6,
        /* 457 */ LSID_CD_1,
        /* 458 */ LSID_CD_2,
        /* 459 */ LSID_G_1,
        /* 460 */ LSID_G_2,
        /* 461 */ LSID_G_3,
        /* 462 */ LSID_G_4,
        /* 463 */ LSID_Cert_1,
        /* 464 */ LSID_Cert_2,
        /* 465 */ LSID_Cert_3,
        /* 466 */ LSID_Cert_4,
        /* 467 */ LSID_Research,
        /* 468 */ LSID_Task,
        /* 469 */ LSID_Communication,
        /* 470 */ LSID_IDsCorrect,
        /* 471 */ LSID_FormatCheck,
        /* 472 */ LSID_IDsCorrectNeed,
        /* 473 */ LSID_MainBaseSize,
        /* 474 */ LSID_SyncFin,
        /* 475 */ LSID_PatSearch,
        /* 476 */ LSID_LinksSearch,
        /* 477 */ LSID_ArcNotFound,
        /* 478 */ LSID_Scale,
        /* 479 */ LSID_GEDCOMFilter,
        /* 480 */ LSID_AllFilter,
        /* 481 */ LSID_ImagesFilter,
        /* 482 */ LSID_ScriptsFilter,
        /* 483 */ LSID_TreeImagesFilter,

        /* 484 */ LSID_CommonStats, // deprecated

        /* 485 */ LSID_ExpPedigree,

        /* 486 */ LSID_InputSimple, // deprecated?
        /* 487 */ LSID_InputSource, // deprecated?
        /* 488 */ LSID_SourceKind, // deprecated?
        /* 489 */ LSID_SK_Rev, // deprecated?
        /* 490 */ LSID_SK_Met, // deprecated?
        /* 491 */ LSID_Year, // deprecated?
        /* 492 */ LSID_Settlement, // deprecated?
        /* 493 */ LSID_EventDate, // deprecated?
        /* 494 */ LSID_EventType, // deprecated?
        /* 495 */ LSID_Join, // deprecated?
        /* 496 */ LSID_Comment, // deprecated?

        /* 497 */ LSID_BranchCut,
        /* 498 */ LSID_Not,
        /* 499 */ LSID_BCut_Years,
        /* 500 */ LSID_BCut_Persons,
        /* 501 */ LSID_SrcAll,
        /* 502 */ LSID_SrcNot,
        /* 503 */ LSID_SrcAny,

        /* 504 */ LSID_MasterBase,
        /* 505 */ LSID_OtherBase,
        /* 506 */ LSID_CurrentBase,
        /* 507 */ LSID_IncludedSourceFilter,
        /* 508 */ LSID_IncludedGroupFilter,
        /* 509 */ LSID_DuplicatesSearch,
        /* 510 */ LSID_ValueInvalid,
        /* 511 */ LSID_Operation,
        /* 512 */ LSID_ToolOp_1,
        /* 513 */ LSID_ToolOp_2,
        /* 514 */ LSID_ToolOp_3,
        /* 515 */ LSID_ToolOp_4,

        /* 516 */ LSID_ToolOp_5, // deprecated

        /* 517 */ LSID_ToolOp_6,
        /* 518 */ LSID_ToolOp_7,
        /* 519 */ LSID_ToolOp_8,
        /* 520 */ LSID_ToolOp_9,
        /* 521 */ LSID_SearchMatches,
        /* 522 */ LSID_CheckFamiliesConnection,
        /* 523 */ LSID_All,
        /* 524 */ LSID_OnlyAlive,
        /* 525 */ LSID_OnlyDied,
        /* 526 */ LSID_AliveBefore,
        /* 527 */ LSID_OnlyMans,
        /* 528 */ LSID_OnlyWomans,
        /* 529 */ LSID_NameMask,
        /* 530 */ LSID_PlaceMask,
        /* 531 */ LSID_EventMask,
        /* 532 */ LSID_OnlyPatriarchs,
        /* 533 */ LSID_DateInvalid,
        /* 534 */ LSID_People,
        /* 535 */ LSID_Years,
        /* 536 */ LSID_Decennial,

        /* 537 */ LSID_HowBirthes,
        /* 538 */ LSID_HowDeads,

        /* 539 */ LSID_Living,
        /* 540 */ LSID_Deads,
        /* 541 */ LSID_AvgAge,
        /* 542 */ LSID_AvgLife,
        /* 543 */ LSID_AvgChilds,
        /* 544 */ LSID_AvgBorn,
        /* 545 */ LSID_AvgMarriagesCount,
        /* 546 */ LSID_AvgMarriagesAge,
        /* 547 */ LSID_AncestorsCount,
        /* 548 */ LSID_DescendantsCount,
        /* 549 */ LSID_GenerationsCount,
        /* 550 */ LSID_BirthYears,
        /* 551 */ LSID_BirthYearsDec,
        /* 552 */ LSID_DeathYears,
        /* 553 */ LSID_DeathYearsDec,
        /* 554 */ LSID_DistrChilds,
        /* 555 */ LSID_AgeFirstborn,
        /* 556 */ LSID_MarriagesAge,
        /* 557 */ LSID_DiffSpouses,
        /* 558 */ LSID_SelAll,
        /* 559 */ LSID_SelFamily,
        /* 560 */ LSID_SelAncestors,
        /* 561 */ LSID_SelDescendants,
        /* 562 */ LSID_RecMerge,
        /* 563 */ LSID_RM_Search,
        /* 564 */ LSID_RM_Skip,
        /* 565 */ LSID_RM_Records,
        /* 566 */ LSID_RM_SearchPersons,

        /* 567 */ LSID_RM_DirectMatching, // deprecated
        /* 568 */ LSID_RM_IndistinctMatching,
        /* 569 */ LSID_RM_OnlyNP, // deprecated

        /* 570 */ LSID_RM_BirthYear,
        /* 571 */ LSID_RM_NameAccuracy,
        /* 572 */ LSID_RM_YearInaccuracy,
        /* 573 */ LSID_Repair,
        /* 574 */ LSID_MinGenerations,
        /* 575 */ LSID_SetPatFlag,
        /* 576 */ LSID_InsertIntoBook,
        /* 577 */ LSID_SimilarSurnames,
        /* 578 */ LSID_SimilarNames,
        /* 579 */ LSID_RecsDeleted,
        /* 580 */ LSID_Record,
        /* 581 */ LSID_Problem,
        /* 582 */ LSID_Solve,
        /* 583 */ LSID_PersonLonglived,
        /* 584 */ LSID_PersonSexless,
        /* 585 */ LSID_LiveYearsInvalid,
        /* 586 */ LSID_StrangeSpouse,
        /* 587 */ LSID_StrangeParent,
        /* 588 */ LSID_Descendants,
        /* 589 */ LSID_Generations,
        /* 590 */ LSID_LinksCount,
        /* 591 */ LSID_PlacesPrepare,
        /* 592 */ LSID_PlaceAlreadyInBook,

        /* 593 */ LSID_DNAMarkers,
        /* 594 */ LSID_AAF_1,
        /* 595 */ LSID_AAF_2,
        /* 596 */ LSID_EmptyFamily,
        /* 597 */ LSID_RevisionsBackup,
        /* 598 */ LSID_Loading,
        /* 599 */ LSID_FileSaveError,
        /* 600 */ LSID_FillColor,
        /* 601 */ LSID_FillImage,
        /* 602 */ LSID_TreeIndividualsCount,
        /* 603 */ LSID_LogView,

        /* 604 */ LSID_AncestorsCircle,
        /* 605 */ LSID_Circle,
        /* 606 */ LSID_TextColor,
        /* 607 */ LSID_BackColor,
        /* 608 */ LSID_LinesColor,

        /* 609 */ LSID_RestrictNone,
        /* 610 */ LSID_RestrictLocked,
        /* 611 */ LSID_RestrictConfidential,
        /* 612 */ LSID_RestrictPrivacy,

        /* 613 */ LSID_LogSend,
        /* 614 */ LSID_Charts,
        /* 615 */ LSID_SizeToFit,
        /* 616 */ LSID_ZoomIn,
        /* 617 */ LSID_ZoomOut,
        /* 618 */ LSID_SetIsDead,
        /* 619 */ LSID_DefineSex,
        /* 620 */ LSID_Plugins,
        /* 621 */ LSID_TM_TraceKinships,
        
        /* 622 */ LSID_NoMatchesFound,
        /* 623 */ LSID_FindPrevious,
        /* 624 */ LSID_FindNext,
        /* 625 */ LSID_CertaintyIndex,
        /* 626 */ LSID_BirthByMonth,
        /* 627 */ LSID_Month,
        
        /* 628 */ LSID_DlgReset,
        /* 629 */ LSID_Field,
        /* 630 */ LSID_Condition,
        
        /* 631 */ LSID_DoNotSetSource,
        /* 632 */ LSID_Slideshow,
        /* 633 */ LSID_PrevRec,
        /* 634 */ LSID_NextRec,

        /* 635 */ LSID_GenerationFailed,
        /* 636 */ LSID_Start,
        /* 637 */ LSID_Stop,
        /* 638 */ LSID_Demography,
        /* 639 */ LSID_Names,

        /* 640 */ LSID_NTAka,
        /* 641 */ LSID_NTBirth,
        /* 642 */ LSID_NTImmigrant,
        /* 643 */ LSID_NTMaiden,
        /* 644 */ LSID_NTMarried,
        /* 645 */ LSID_RemoveNameQuery,
        /* 646 */ LSID_RemoveNameFailed,
        /* 647 */ LSID_Quote,
        /* 648 */ LSID_BookmarkMerged,
        /* 649 */ LSID_ShowDatesCalendar,
        /* 650 */ LSID_RecordDuplicate,
        /* 651 */ LSID_DuplicateWarning,
        /* 652 */ LSID_ShowDatesSigns,

        /* 653 */ LSID_FileNewTip,
        /* 654 */ LSID_FileLoadTip,
        /* 655 */ LSID_FileSaveTip,
        /* 656 */ LSID_RecordAddTip,
        /* 657 */ LSID_RecordEditTip,
        /* 658 */ LSID_RecordDeleteTip,
        /* 659 */ LSID_FilterTip,
        /* 660 */ LSID_TreeAncestorsTip,
        /* 661 */ LSID_TreeDescendantsTip,
        /* 662 */ LSID_TreeBothTip,
        /* 663 */ LSID_PedigreeTip,
        /* 664 */ LSID_Pedigree_dAbovilleTip,
        /* 665 */ LSID_Pedigree_KonovalovTip,
        /* 666 */ LSID_StatsTip,
        /* 667 */ LSID_ImageSaveTip,
        /* 668 */ LSID_ModesTip,
        /* 669 */ LSID_NewScriptTip,
        /* 670 */ LSID_LoadScriptTip,
        /* 671 */ LSID_SaveScriptTip,
        /* 672 */ LSID_RunScriptTip,
        /* 673 */ LSID_PortraitAddTip,
        /* 674 */ LSID_PortraitDeleteTip,
        /* 675 */ LSID_ParentsAddTip,
        /* 676 */ LSID_ParentsEditTip,
        /* 677 */ LSID_ParentsDeleteTip,
        /* 678 */ LSID_FatherAddTip,
        /* 679 */ LSID_FatherDeleteTip,
        /* 680 */ LSID_FatherSelTip,
        /* 681 */ LSID_MotherAddTip,
        /* 682 */ LSID_MotherDeleteTip,
        /* 683 */ LSID_MotherSelTip,
        /* 684 */ LSID_NameCopyTip,
        /* 685 */ LSID_HusbandAddTip,
        /* 686 */ LSID_HusbandDeleteTip,
        /* 687 */ LSID_HusbandSelTip,
        /* 688 */ LSID_WifeAddTip,
        /* 689 */ LSID_WifeDeleteTip,
        /* 690 */ LSID_WifeSelTip,

        /* 691 */ LSID_PersonAttachTip,
        /* 692 */ LSID_PlaceAddTip,
        /* 693 */ LSID_PlaceDeleteTip,
        /* 694 */ LSID_ShowOnMapTip,
        /* 695 */ LSID_SourceAddTip,
        /* 696 */ LSID_GoalSelectTip,
        /* 697 */ LSID_NewDBFileNeedToSave,
        /* 698 */ LSID_FileWithSameNameAlreadyExistsInStorage,
        /* 699 */ LSID_ItsNotGEDSECCompatibleFile,

        /* 000 */ LSID_Last = LSID_ItsNotGEDSECCompatibleFile
    }

    public static class LangMan
    {
        public const int LS_DEF_CODE = 1049;
        public const string LS_DEF_SIGN = "rus";
        public const string LS_DEF_NAME = "Русский";

        private static readonly string[] LSDefList = new string[]
        {
            /* 001 */ "Файл",
            /* 002 */ "Правка",
            /* 003 */ "Родословная",
            /* 004 */ "Сервис",
            /* 005 */ "&Окна",
            /* 006 */ "Справка",
            /* 007 */ "Новый",
            /* 008 */ "Открыть...",
            /* 009 */ "Открыть последний",
            /* 010 */ "Сохранить...",
            /* 011 */ "Закрыть",
            /* 012 */ "Свойства файла...",
            /* 013 */ "Экспорт",
            /* 014 */ "Фамильная книга...",

            /* 015 */ "<?>",

            /* 016 */ "Экспорт в Excel-файл...",
            /* 017 */ "Выход",

            /* 018 */ "<?>",
            /* 019 */ "<?>",

            /* 020 */ "Добавить запись",
            /* 021 */ "Изменить запись",
            /* 022 */ "Удалить запись",

            /* 023 */ "<?>",

            /* 024 */ "Древо предков",
            /* 025 */ "Древо потомков",
            /* 026 */ "Древо полное",
            /* 027 */ "Роспись по дАбовиллю",
            /* 028 */ "Роспись по Коновалову",
            /* 029 */ "Карты",
            /* 030 */ "Статистика",
            /* 031 */ "Калькулятор",
            /* 032 */ "Справочник имен",
            /* 033 */ "Календарь",
            /* 034 */ "Линия времени",
            /* 035 */ "Органайзер",
            /* 036 */ "Скрипты...",

            /* 037 */ "<?>",

            /* 038 */ "Инструменты...",
            /* 039 */ "Фильтр",
            /* 040 */ "Настройки",
            /* 041 */ "&Каскад",
            /* 042 */ "&Горизонтальная мозаика",
            /* 043 */ "&Вертикальная мозаика",
            /* 044 */ "&Свернуть все",
            /* 045 */ "&Разместить все",

            /* 046 */ "Ресурсы в Интернете...", // deprecated
            /* 047 */ "Терминология родства...", // deprecated
            /* 048 */ "Часто задаваемые вопросы...", // deprecated

            /* 049 */ "Содержание",
            /* 050 */ "О программе",
            /* 051 */ "Записей",
            /* 052 */ "фильтрованных",
            /* 053 */ "Персоны",
            /* 054 */ "Семьи",
            /* 055 */ "Заметки",
            /* 056 */ "Мультимедиа",
            /* 057 */ "Источники",
            /* 058 */ "Архивы",
            /* 059 */ "Группы",
            /* 060 */ "Исследования",
            /* 061 */ "Задачи",
            /* 062 */ "Коммуникации",
            /* 063 */ "Места",
            /* 064 */ "неизвестная",
            /* 065 */ "неизвестный",
            /* 066 */ "?",
            /* 067 */ "Мужской",
            /* 068 */ "Женский",
            /* 069 */ "Неопределенный",
            /* 070 */ "Файл изменен. Сохранить?",
            /* 071 */ "У заданного родителя найдена семья \"{0}\". Включить в неё ребенка?",
            /* 072 */ "Удалить персональную запись \"{0}\"?",
            /* 073 */ "Удалить семью \"{0}\"?",
            /* 074 */ "Удалить заметку?",
            /* 075 */ "Удалить источник \"{0}\"?",
            /* 076 */ "Удалить мультимедиа \"{0}\"?",
            /* 077 */ "Удалить архив \"{0}\"?",
            /* 078 */ "Удалить группу \"{0}\"?",
            /* 079 */ "Удалить исследование \"{0}\"?",
            /* 080 */ "Удалить задачу \"{0}\"?",
            /* 081 */ "Удалить коммуникацию \"{0}\"?",
            /* 082 */ "Удалить место \"{0}\"?",
            /* 083 */ "Адрес",
            /* 084 */ "Факты",
            /* 085 */ "Фамилия",
            /* 086 */ "Имя",
            /* 087 */ "Отчество",
            /* 088 */ "Пол",
            /* 089 */ "Прозвище",
            /* 090 */ "Префикс фамилии",
            /* 091 */ "Префикс имени",
            /* 092 */ "Суффикс имени",
            /* 093 */ "Патриарх",
            /* 094 */ "Закладка",
            /* 095 */ "Ассоциация",
            /* 096 */ "Отношение",
            /* 097 */ "Персона",
            /* 098 */ "Принять",
            /* 099 */ "Отменить",
            /* 100 */ "Закрыть",
            /* 101 */ "Выбрать",
            /* 102 */ "Добавить",
            /* 103 */ "Новая персональная запись",
            /* 104 */ "Редактирование персональной записи",
            /* 105 */ "Проверка пола",
            /* 106 */ "Выбор записи",
            /* 107 */ "Цитата источника",
            /* 108 */ "Пользовательская сноска",
            /* 109 */ "Заметка",
            /* 110 */ "Источник",
            /* 111 */ "Лист/Страница",
            /* 112 */ "Достоверность",
            /* 113 */ "Сноска/ссылка",
            /* 114 */ "Тип",
            /* 115 */ "Семья",
            /* 116 */ "Муж",
            /* 117 */ "Жена",
            /* 118 */ "Статус",
            /* 119 */ "Дети",
            /* 120 */ "Удалить ссылку на мужа?",
            /* 121 */ "Удалить ссылку на жену?",
            /* 122 */ "Удалить ссылку на ребенка?",
            /* 123 */ "Дата рождения",
            /* 124 */ "Дата смерти",
            /* 125 */ "Ограничение безопасности",
            /* 126 */ "Название",
            /* 127 */ "Участники",
            /* 128 */ "Редактирование группы",
            /* 129 */ "Удалить ссылку на участника группы?",
            /* 130 */ "просмотр",
            /* 131 */ "Этап",
            /* 132 */ "Телефон",
            /* 133 */ "Эл. почта",
            /* 134 */ "Сайт",
            /* 135 */ "Архив",
            /* 136 */ "Прогресс",
            /* 137 */ "Времени прошло",
            /* 138 */ "Времени осталось",
            /* 139 */ "Времени всего",
            /* 140 */ "Дата",
            /* 141 */ "Текст",
            /* 142 */ "Краткое название",
            /* 143 */ "Автор",
            /* 144 */ "Опубликовано",
            /* 145 */ "Общее",
            /* 146 */ "Удалить ссылку на архив?",
            /* 147 */ "Способ хранения",
            /* 148 */ "Файл",
            /* 149 */ "Просмотр",
            /* 150 */ "Для выбранного типа хранения не включен режим расширения",
            /* 151 */ "Отец",
            /* 152 */ "Мать",
            /* 153 */ "Родители",
            /* 154 */ "Супруги",
            /* 155 */ "Ассоциации",
            /* 156 */ "Сноски/Пометки",
            /* 157 */ "Григорианский",
            /* 158 */ "Юлианский",
            /* 159 */ "Еврейский",
            /* 160 */ "Исламский (Хиджры)",
            /* 161 */ "Иранский",
            /* 162 */ "Индийский",
            /* 163 */ "Бахаи",
            /* 164 */ "Французский",
            /* 165 */ "Римский",
            /* 166 */ "Неизвестно",
            /* 167 */ "Сводка",
            /* 168 */ "Прочее",
            /* 169 */ "Предоставление",
            /* 170 */ "Податель",
            /* 171 */ "Местоположение",
            /* 172 */ "Широта",
            /* 173 */ "Долгота",
            /* 174 */ "Показать",
            /* 175 */ "Поиск координат",
            /* 176 */ "Поиск",
            /* 177 */ "Выбрать коорд.",
            /* 178 */ "Выбрать название",
            /* 179 */ "Приоритет",
            /* 180 */ "Процент",
            /* 181 */ "Запущено",
            /* 182 */ "Завершено",
            /* 183 */ "Цель",
            /* 184 */ "Тема",
            /* 185 */ "Корреспондент",
            /* 186 */ "Группа",
            /* 187 */ "Удалить ссылку на задачу?",
            /* 188 */ "Удалить ссылку на корреспонденцию?",
            /* 189 */ "Удалить ссылку на группу?",
            /* 190 */ "Редактирование исследования",
            /* 191 */ "Редактирование задачи",
            /* 192 */ "Редактирование коммуникации",
            /* 193 */ "Ошибка",
            /* 194 */ "Ошибка запуска Lua!",
            /* 195 */ "Некорректный формат даты",
            /* 196 */ "Страна",
            /* 197 */ "Штат/Область",
            /* 198 */ "Город",
            /* 199 */ "Почтовый код",
            /* 200 */ "Телефоны",
            /* 201 */ "Эл. почта",
            /* 202 */ "Веб-страницы",
            /* 203 */ "Значение",
            /* 204 */ "Событие",
            /* 205 */ "Место",
            /* 206 */ "Причина",
            /* 207 */ "Засвидетельствовавший орган",
            /* 208 */ "Женское",
            /* 209 */ "Мужское",
            /* 210 */ "Не выбрана персональная запись",
            /* 211 */ "У данной персоны не задан пол.",
            /* 212 */ "У данной персоны нет семей.",
            /* 213 */ "Расчетное количество предков {0} больше допустимых пределов.",
            /* 214 */ "Расчетное количество потомков {0} больше допустимых пределов.",
            /* 215 */ "Показывать поколений:",
            /* 216 */ "неограниченно",
            /* 217 */ "Cупруг(а)",
            /* 218 */ "Дата брака",
            /* 219 */ "Удалить ссылку на отца?",
            /* 220 */ "Удалить ссылку на мать?",
            /* 221 */ "Удалить ссылку на супруга?",
            /* 222 */ "Удалить персону из семьи родителей?",
            /* 223 */ "Всё",
            /* 224 */ "Только предки",
            /* 225 */ "Только потомки",
            /* 226 */ "Автосмена центра",
            /* 227 */ "Редактировать",
            /* 228 */ "Добавить семью",
            /* 229 */ "Добавить супруга(у)",
            /* 230 */ "Добавить сына",
            /* 231 */ "Добавить дочь",
            /* 232 */ "Удалить",
            /* 233 */ "Перестроить древо",
            /* 234 */ "Перестроить отношения",
            /* 235 */ "Ссылки",
            /* 236 */ "Место/Атрибут",
            /* 237 */ "брак",
            /* 238 */ "семья",
            /* 239 */ "Тёзки",
            /* 240 */ "Удалить факт?",
            /* 241 */ "Удалить ссылку на заметку?",
            /* 242 */ "Удалить ссылку на мультимедиа?",
            /* 243 */ "Удалить ссылку на источник?",
            /* 244 */ "Удалить ассоциацию?",
            /* 245 */ "Удалить пользовательскую сноску?",
            /* 246 */ "Ошибка загрузки файла",
            /* 247 */ "Ошибка проверки формата",
            /* 248 */ "Дни рождения",
            /* 249 */ "До дня рождения \"{0}\" осталось {1} дня(-ей)",
            /* 250 */ "Интерфейс",
            /* 251 */ "Родословные древа",
            /* 252 */ "Росписи",
            /* 253 */ "Кодировка сохранения файлов",

            /* 254 */ "<?>",
            /* 255 */ "<?>",
            /* 256 */ "<?>",

            /* 257 */ "Загрузка из Интернета",
            /* 258 */ "Использовать прокси-сервер",
            /* 259 */ "Сервер",
            /* 260 */ "Порт",
            /* 261 */ "Логин",
            /* 262 */ "Пароль",
            /* 263 */ "Пароль не задан",
            /* 264 */ "Показывать при старте подсказки",
            /* 265 */ "Язык",
            /* 266 */ "Все списки",
            /* 267 */ "Список персон",
            /* 268 */ "Формат имен в списках",
            /* 269 */ "Фамилия_Имя_Отчество",
            /* 270 */ "Фамилия; Имя_Отчество",
            /* 271 */ "Фамилия; Имя; Отчество",
            /* 272 */ "Формат даты в списках",
            /* 273 */ "Включать адрес в строки мест",
            /* 274 */ "Подсвечивать персоны без родителей",
            /* 275 */ "Подсвечивать персоны без семьи",
            /* 276 */ "Значения по умолчанию",
            /* 277 */ "Отображение персон в древе",
            /* 278 */ "Разные строки (имя и отчество)",
            /* 279 */ "Только годы",
            /* 280 */ "Степень родства",
            /* 281 */ "Дополнительные символы",
            /* 282 */ "Декоративное оформление",
            /* 283 */ "Отображать портреты",
            /* 284 */ "Исключить умерших в детстве",
            /* 285 */ "Оформление",
            /* 286 */ "Мужчина",
            /* 287 */ "Женщина",
            /* 288 */ "Неизвестный пол",
            /* 289 */ "Разведенный супруг",
            /* 290 */ "Разведенная супруга",
            /* 291 */ "Шрифт",
            /* 292 */ "Генерация росписей",
            /* 293 */ "Включая атрибуты персон",
            /* 294 */ "Включая заметки",
            /* 295 */ "Включая источники",
            /* 296 */ "Формат",
            /* 297 */ "Избыточный",
            /* 298 */ "Традиционный",
            /* 299 */ "Перейти на запись",
            /* 300 */ "Поместить выше",
            /* 301 */ "Поместить ниже",
            /* 302 */ "Полное имя",
            /* 303 */ "Место рождения",
            /* 304 */ "Место смерти",
            /* 305 */ "Местожительство",
            /* 306 */ "Возраст",
            /* 307 */ "Продолжительность жизни",
            /* 308 */ "Дней до ДР",
            /* 309 */ "Вероисповедание",
            /* 310 */ "Национальность",
            /* 311 */ "Образование",
            /* 312 */ "Профессия",
            /* 313 */ "Социальное положение",
            /* 314 */ "Военная служба",
            /* 315 */ "Призван в ВС",
            /* 316 */ "Уволен из ВС",
            /* 317 */ "Звание в ВС",
            /* 318 */ "Изменено",
            /* 319 */ "Брак зарегистрирован",
            /* 320 */ "Брак не зарегистрирован",
            /* 321 */ "Разведены",
            /* 322 */ "Рождение",
            /* 323 */ "Усыновление",
            /* 324 */ "Крещение",
            /* 325 */ "Получение ученой степени",
            /* 326 */ "Уход на пенсию",
            /* 327 */ "Натурализация",
            /* 328 */ "Эмиграция",
            /* 329 */ "Иммиграция",
            /* 330 */ "Перепись",
            /* 331 */ "Завещание",
            /* 332 */ "Утверждение завещания",
            /* 333 */ "Смерть",
            /* 334 */ "Похороны",
            /* 335 */ "Кремация",
            /* 336 */ "Факт",
            /* 337 */ "Физическое описание",
            /* 338 */ "Идентификационный номер",
            /* 339 */ "Код социального страхования",
            /* 340 */ "Количество детей",
            /* 341 */ "Количество браков",
            /* 342 */ "Собственность",
            /* 243 */ "Титул",
            /* 344 */ "Путешествие",
            /* 345 */ "Хобби",
            /* 346 */ "Награда",
            /* 347 */ "?",
            /* 348 */ "отец",
            /* 349 */ "мать",
            /* 350 */ "муж",
            /* 351 */ "жена",
            /* 352 */ "сын",
            /* 353 */ "дочь",
            /* 354 */ "дед",
            /* 355 */ "бабушка",
            /* 356 */ "внук",
            /* 357 */ "внучка",
            /* 358 */ "брат",
            /* 359 */ "сестра",
            /* 360 */ "зять",
            /* 361 */ "невестка",
            /* 362 */ "свекор",
            /* 363 */ "свекровь",
            /* 364 */ "тесть",
            /* 365 */ "теща",
            /* 366 */ "дядя",
            /* 367 */ "тетя",
            /* 368 */ "племянник",
            /* 369 */ "племянница",
            /* 370 */ "кузен",
            /* 371 */ "кузина",
            /* 372 */ "<?>",
            /* 373 */ "<?>",
            /* 374 */ "<?>",
            /* 375 */ "<?>",
            /* 376 */ "<?>",
            /* 377 */ "<?>",
            /* 378 */ "<?>",
            /* 379 */ "<?>",
            /* 380 */ "<?>",
            /* 381 */ "Ширина изображения более 65 тыс. точек. Сохранить невозможно",
            /* 382 */ "Назад",
            /* 383 */ "Вперед",
            /* 384 */ "<?>",
            /* 385 */ "Далее",
            /* 386 */ "Вы знаете что...",
            /* 387 */ "Загрузка и поиск мест",
            /* 388 */ "( не выбран )",
            /* 389 */ "Выборка",
            /* 390 */ "По всем людям",
            /* 391 */ "Места рождения",
            /* 392 */ "Места смерти",
            /* 393 */ "Места проживания",
            /* 394 */ "Только по выбранному",
            /* 395 */ "Сохранить снимок...",
            /* 396 */ "Формат не поддерживается",
            /* 397 */ "Ошибка загрузки данных.",
            /* 398 */ "Печать",
            /* 399 */ "Предварительный просмотр",

            /* 400 */ "Поколение",

            /* 401 */ "<?>",
            /* 402 */ "<?>",

            /* 403 */ "Точно",
            /* 404 */ "Ранее",
            /* 405 */ "Позднее",
            /* 406 */ "Между",
            /* 407 */ "Период до",
            /* 408 */ "Период после",
            /* 409 */ "Период между",
            /* 410 */ "Около",
            /* 411 */ "По расчету",
            /* 412 */ "По оценке",
            /* 413 */ "Помолвка",
            /* 414 */ "Бракосочетание",
            /* 415 */ "Публичное объявление о бракосочетании",
            /* 416 */ "Заключение брачного контракта",
            /* 417 */ "Получение разрешения на брак",
            /* 418 */ "Заключение брачного соглашения",
            /* 449 */ "Аннулирование брака",
            /* 420 */ "Подача заявления о разводе",
            /* 421 */ "Развод",
            /* 422 */ "Ссылка на файл",
            /* 423 */ "Размещение в архиве",
            /* 424 */ "Размещение в хранилище",
            /* 425 */ "-",
            /* 426 */ "Звукозапись",
            /* 427 */ "Книга",
            /* 428 */ "Карточка",
            /* 429 */ "Электронный",
            /* 430 */ "Микрофиша",
            /* 431 */ "Фильм",
            /* 432 */ "Журнал",
            /* 433 */ "Рукопись",
            /* 434 */ "Карта",
            /* 435 */ "Газета",
            /* 436 */ "Фотография",
            /* 437 */ "Надгробие",
            /* 438 */ "Видео",
            /* 439 */ "- Другой -",
            /* 440 */ "Не задан",
            /* 441 */ "Низкий",
            /* 442 */ "Нормальный",
            /* 443 */ "Высокий",
            /* 444 */ "Срочный",
            /* 445 */ "Определено",
            /* 446 */ "Выполняется",
            /* 447 */ "Задержано",
            /* 448 */ "Осложнения",
            /* 449 */ "Завершено",
            /* 450 */ "Отозвано",
            /* 451 */ "Звонок",
            /* 452 */ "Эл.письмо",
            /* 453 */ "Факс",
            /* 454 */ "Письмо",
            /* 455 */ "Кассета",
            /* 456 */ "Визит",
            /* 457 */ "от",
            /* 458 */ "к",
            /* 459 */ "персона",
            /* 460 */ "семья",
            /* 461 */ "источник",
            /* 462 */ "иная",
            /* 463 */ "Ненадежное подтверждение или предполагаемые данные",
            /* 464 */ "Сомнительная надежность подтверждения",
            /* 465 */ "Косвенные доказательства",
            /* 466 */ "Прямые и первичные доказательства",
            /* 467 */ "Исследование",
            /* 468 */ "Задача",
            /* 469 */ "Корреспонденция",
            /* 470 */ "Коррекция идентификаторов",
            /* 471 */ "Проверка формата",
            /* 472 */ "Требуется коррекция идентификаторов записей, продолжить?",
            /* 473 */ "Количество объектов в основной базе: {0}",
            /* 474 */ "Синхронизация завершена.",
            /* 475 */ "Поиск патриархов",
            /* 476 */ "Поиск взаимосвязей",
            /* 477 */ "Медиа-файл не загружен, т.к. отсутствует в медиа-контейнере (хранилище или архиве)",
            /* 478 */ "Масштаб",
            /* 479 */ "GEDKeeper GEDCOM файлы (*.ged)|*.ged|GEDKeeper шифрованные GEDCOM файлы (*.geds)|*.geds",
            /* 480 */ "Все файлы (*.*)|*.*",
            /* 481 */ "Изображения (*.bmp;*.gif;*.png;*.jpg)|*.bmp;*.gif;*.png;*.jpg", //Image Files|
            /* 482 */ "Скрипты (*.lua)|*.lua",
            /* 483 */ "Файлы BMP (*.bmp)|*.bmp|Файлы JPEG (*.jpg)|*.jpg|Файлы EMF (*.emf)|*.emf|Файлы PNG (*.png)|*.png|Файлы GIF (*.gif)|*.gif",

            /* 484 */ "<?>",

            /* 485 */ "Родословная роспись",
            /* 486 */ "Простой ввод",
            /* 487 */ "Источник (метрики/ревизии)",
            /* 488 */ "Тип источника",
            /* 489 */ "Ревизская сказка",
            /* 490 */ "Метрическая книга",
            /* 491 */ "Год",
            /* 492 */ "Населенный пункт",
            /* 493 */ "Дата события",
            /* 494 */ "Тип события",
            /* 495 */ "Связь",
            /* 496 */ "Примечание",
            /* 497 */ "Отсечение ветвей",
            /* 498 */ "нет",
            /* 499 */ "по границе лет",
            /* 500 */ "по заданным лицам",
            /* 501 */ "- всё -",
            /* 502 */ "- нет -",
            /* 503 */ "- любые -",

            /* 504 */ "Мастер-база",
            /* 505 */ "Обновление базы",
            /* 506 */ "[текущая база данных]",
            /* 507 */ "Установлен фильтр по источнику. Внести источник в новую персональную запись?",
            /* 508 */ "Установлен фильтр по группе. Внести группу в новую персональную запись?",
            /* 509 */ "Поиск дубликатов",
            /* 510 */ "Значение неверно",
            /* 511 */ "Операция",
            /* 512 */ "Сравнить базы данных",
            /* 513 */ "Объединить базы данных",
            /* 514 */ "Разделить базу данных",
            /* 515 */ "Объединить дубликаты записей",
            /* 516 */ "Импорт росписей из внешних форматов",
            /* 517 */ "Проверка связности семей",
            /* 518 */ "Проверка базы данных",
            /* 519 */ "Поиск патриархов",
            /* 520 */ "Управление местами",
            /* 521 */ "Поиск совпадений...",
            /* 522 */ "Проверка связности семей",
            /* 523 */ "все",
            /* 524 */ "только живые",
            /* 525 */ "только умершие",
            /* 526 */ "В живых до",
            /* 527 */ "только мужчины",
            /* 528 */ "только женщины",
            /* 529 */ "Маска имени",
            /* 530 */ "Маска местожительства",
            /* 531 */ "Маска фактов",
            /* 532 */ "Только главы семей",
            /* 533 */ "Дата неверна",
            /* 534 */ "Люди",
            /* 535 */ "Годы",
            /* 536 */ "Десятилетия",

            /* 537 */ "Родилось",
            /* 538 */ "Умерло",

            /* 539 */ "Живущие",
            /* 540 */ "Умершие",
            /* 541 */ "Средний возраст",
            /* 542 */ "Средняя продолжительность жизни",
            /* 543 */ "Среднее число детей",
            /* 544 */ "Средний возраст рождения первенца",
            /* 545 */ "Среднее количество браков",
            /* 546 */ "Средний возраст заключения брака",
            /* 547 */ "Количество предков",
            /* 548 */ "Количество потомков",
            /* 549 */ "Количество поколений потомков",
            /* 550 */ "Годы рождения",
            /* 551 */ "Годы рождения (десятилетиями)",
            /* 552 */ "Годы смерти",
            /* 553 */ "Годы смерти (десятилетиями)",
            /* 554 */ "Распределение количества детей",
            /* 555 */ "Возраст рождения первенца",
            /* 556 */ "Возраст вступления в брак",
            /* 557 */ "Разница возрастов супругов",
            /* 558 */ "Выбрать все связи",
            /* 559 */ "Выбрать семью",
            /* 560 */ "Выбрать предков",
            /* 561 */ "Выбрать потомков",
            /* 562 */ "Объединение",
            /* 563 */ "Автопоиск",
            /* 564 */ "Пропустить",
            /* 565 */ "Записи",
            /* 566 */ "Поиск персон",
            /* 567 */ "Прямое сравнение", // deprecated
            /* 568 */ "Нечеткое сравнение имен",
            /* 569 */ "Только по имени/отчеству (только женщины)", // deprecated
            /* 570 */ "Учитывать год рождения",
            /* 571 */ "Точность имени, %",
            /* 572 */ "Погрешность лет",
            /* 573 */ "Исправить",
            /* 574 */ "Поколений потомков не менее",
            /* 575 */ "Установить признак",
            /* 576 */ "Внести в справочник",
            /* 577 */ "Схожие фамилии:",
            /* 578 */ "Схожие имена:",
            /* 579 */ "Выбранные персональные записи удалены",
            /* 580 */ "Запись",
            /* 581 */ "Проблема",
            /* 582 */ "Решение",
            /* 583 */ "Возможно умерший (возраст {0})",
            /* 584 */ "Не задан пол",
            /* 585 */ "Год рождения больше года смерти",
            /* 586 */ "Первый брак в возрасте {0} лет?",
            /* 587 */ "Первый ребенок родился в возрасте {0} лет?",
            /* 588 */ "Потомков",
            /* 589 */ "Поколений",
            /* 590 */ "Количество ссылок",
            /* 591 */ "Обработка мест",
            /* 592 */ "Место уже есть в справочнике",
            /* 593 */ "Маркеры ДНК",
            /* 594 */ "Ср.возр.рождения первенца на ДР родителя",
            /* 595 */ "Ср.возр.рождения первенца на ДР ребенка",
            /* 596 */ "Пустая запись семьи",
            /* 597 */ "Сохранять версии файлов",
            /* 598 */ "Загрузка",
            /* 599 */ "Ошибка сохранения файла \"{0}\"{1}.",
            /* 600 */ "Цвет фона...",
            /* 601 */ "Изображение фона...",
            /* 602 */ "Персон в древе: {0}",
            /* 603 */ "Просмотреть журнал ошибок",

            /* 604 */ "Круг предков",
            /* 605 */ "Круг",
            /* 606 */ "Цвет текста",
            /* 607 */ "Цвет фона",
            /* 608 */ "Цвет линии",

            /* 609 */ "нет",
            /* 610 */ "заперто",
            /* 611 */ "конфиденциально",
            /* 612 */ "секретно",

            /* 613 */ "Отправить журнал ошибок",
            /* 614 */ "Диаграммы",
            /* 615 */ "Под размер окна",
            /* 616 */ "Увеличить",
            /* 617 */ "Уменьшить",
            /* 618 */ "Установить факт смерти",
            /* 619 */ "Определить пол",
            /* 620 */ "Дополнения",
            /* 621 */ "Автопересчет родства",
            
            /* 622 */ "Не найдено соответствий",
            /* 623 */ "Найти предыдущее",
            /* 624 */ "Найти следующее",
            /* 625 */ "Индекс достоверности",
            /* 626 */ "Месяца рождений",
            /* 627 */ "Месяц",

            /* 628 */ "Сбросить",
            /* 629 */ "Поле",
            /* 630 */ "Условие",

            /* 631 */ "Не задан источник",
            /* 632 */ "Слайдшоу",
            /* 633 */ "Предыдущая запись",
            /* 634 */ "Следующая запись",

            /* 635 */ "Генерация не удалась",
            /* 636 */ "Старт",
            /* 637 */ "Стоп",
            /* 638 */ "Демография",
            /* 639 */ "Имена",

            /* 640 */ "Имя-псевдоним",
            /* 641 */ "Урожденное",
            /* 642 */ "В иммиграции",
            /* 643 */ "Девичье",
            /* 644 */ "В замужестве",
            /* 645 */ "Удалить имя?",
            /* 646 */ "Нельзя удалить единственное имя",
            /* 647 */ "Цитата",
            /* 648 */ "Помечать закладкой объединенное",
            /* 649 */ "Показывать у дат календарь",
            /* 650 */ "Дублировать запись",
            /* 651 */ "Внимание: при дублировании персональных записей, родственные связи и ассоциации не копируются",
            /* 652 */ "Показывать у дат обозначения типа",

            /* 653 */ "Создать новый файл древа",
            /* 654 */ "Открыть файл древа",
            /* 655 */ "Сохранить файл древа",
            /* 656 */ "Добавить запись (Ctrl+I)",
            /* 657 */ "Изменить запись (Ctrl+Enter)",
            /* 658 */ "Удалить запись (Ctrl+L)",
            /* 659 */ "Фильтрация списка записей",
            /* 660 */ "Показать древо предков",
            /* 661 */ "Показать древо потомков",
            /* 662 */ "Показать полное древо",
            /* 663 */ "Родословная роспись",
            /* 664 */ "Роспись по д\'Абовиллю",
            /* 665 */ "Роспись по Коновалову",
            /* 666 */ "Статистический анализ данных",
            /* 667 */ "Сохранить изображение",
            /* 668 */ "Режимы отображения",
            /* 669 */ "Создать новый скрипт",
            /* 670 */ "Открыть скрипт",
            /* 671 */ "Сохранить скрипт",
            /* 672 */ "Выполнить скрипт",

            /* 673 */ "Присоединить портрет",
            /* 674 */ "Отсоединить портрет",
            /* 675 */ "Присоединить семью родителей",
            /* 676 */ "Правка семьи родителей",
            /* 677 */ "Отсоединить семью родителей",
            /* 678 */ "Выбрать или добавить отца",
            /* 679 */ "Отсоединить отца",
            /* 680 */ "Перейти на запись отца",
            /* 681 */ "Выбрать или добавить мать",
            /* 682 */ "Отсоединить мать",
            /* 683 */ "Перейти на запись матери",
            /* 684 */ "Скопировать имя в буфер обмена",

            /* 685 */ "Выбрать или добавить мужа",
            /* 686 */ "Отсоединить мужа",
            /* 687 */ "Перейти на запись мужа",
            /* 688 */ "Выбрать или добавить жену",
            /* 689 */ "Отсоединить жену",
            /* 690 */ "Перейти на запись жены",

            /* 691 */ "Выбрать персональную запись",
            /* 692 */ "Выбрать или добавить место",
            /* 693 */ "Удалить ссылку на место",
            /* 694 */ "Показать на карте",
            /* 695 */ "Выбрать или добавить запись источника",
            /* 696 */ "Выбрать запись цели",
            /* 697 */ "Для типов хранения \"архив\" и \"хранилище\" новый файл БД нужно предварительно сохранить",
            /* 698 */ "Файл с таким именем уже есть в хранилище",
            /* 699 */ "Это не GEDSEC-совместимый файл"
        };

        private static readonly string[] LSList = new string[(int)LSID.LSID_Last + 1];

        public static string LS(LSID lsid)
        {
            return LSList[(int)lsid - 1];
        }

        public static bool LoadFromFile(string fileName)
        {
            bool result = false;

            if (File.Exists(fileName))
            {
                using (StreamReader lngFile = new StreamReader(fileName, Encoding.UTF8))
                {
                    lngFile.ReadLine();
                    int i = 0;
                    while (lngFile.Peek() != -1)
                    {
                        string st = lngFile.ReadLine();
                        LSList[i] = st.Trim();
                        i++;
                    }
                    result = true;
                }
            }

            return result;
        }

        public static void DefInit()
        {
            for (LSID id = LSID.LSID_First; id <= LSID.LSID_Last; id++)
            {
                LSList[(int)id - 1] = LSDefList[(int)id - 1];
            }
        }

        public static void SaveDefaultLanguage()
        {
            StreamWriter lf = new StreamWriter(GKUtils.GetLangsPath() + "russian.sample", false, Encoding.UTF8);
            try
            {
                lf.WriteLine(";" + LS_DEF_CODE.ToString() + "," + LS_DEF_SIGN + "," + LS_DEF_NAME);
                for (LSID i = LSID.LSID_First; i <= LSID.LSID_Last; i++)
                {
                    lf.WriteLine(LSDefList[(int)i - 1]);
                }
            }
            finally
            {
                lf.Close();
            }
        }
    }

    public class LangManager : ILangMan
    {
        private readonly Dictionary<int, string> fList;

        public LangManager()
        {
            this.fList = new Dictionary<int, string>();
        }

        public string LS(Enum lsid)
        {
            int idx = ((IConvertible)lsid).ToInt32(null);
            string res;
            return (this.fList.TryGetValue(idx, out res)) ? res : "?";
        }

        public bool LoadFromFile(string fileName)
        {
            bool result = false;

            if (File.Exists(fileName))
            {
                StreamReader lngFile = new StreamReader(fileName, Encoding.UTF8);
                try
                {
                    lngFile.ReadLine(); // skip declaration line
                    int i = 0;
                    while (lngFile.Peek() != -1)
                    {
                        string st = lngFile.ReadLine().Trim();
                        this.fList.Add(i, st);
                        i++;
                    }
                    result = true;
                }
                finally
                {
                    lngFile.Close();
                }
            }

            return result;
        }
    }
}
